'use strict';
// Stable v6.1 official-evidence module. Loads after stable-v6 core.
const OFFICIAL_DB='rescue6-official-v1', OFFICIAL_DOC='ems-2026';
let officialPages=[];
let officialMeta={fileName:'',pageCount:0,verified:false,at:0};
function officialDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(OFFICIAL_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('docs'))db.createObjectStore('docs',{keyPath:'id'});if(!db.objectStoreNames.contains('pages'))db.createObjectStore('pages',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function officialStoreGetAll(name){const db=await officialDb();return new Promise((resolve,reject)=>{const tx=db.transaction(name,'readonly'),r=tx.objectStore(name).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function officialStoreClear(){const db=await officialDb();return new Promise((resolve,reject)=>{const tx=db.transaction(['docs','pages'],'readwrite');tx.objectStore('docs').clear();tx.objectStore('pages').clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IDB_ABORT'))})}
async function officialReplace(doc,pages){const db=await officialDb();return new Promise((resolve,reject)=>{const tx=db.transaction(['docs','pages'],'readwrite'),ds=tx.objectStore('docs'),ps=tx.objectStore('pages');ds.clear();ps.clear();ds.put(doc);pages.forEach(row=>ps.put(row));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IDB_ABORT'))})}
async function restoreOfficial(){try{const [docs,pages]=await Promise.all([officialStoreGetAll('docs'),officialStoreGetAll('pages')]);officialMeta=docs.find(x=>x.id===OFFICIAL_DOC)||{fileName:'',pageCount:0,verified:false,at:0};officialPages=pages.filter(x=>x.docId===OFFICIAL_DOC).sort((a,b)=>a.page-b.page);if(state.page==='resources')render()}catch(e){console.warn('OFFICIAL_RESTORE',e)}}
function officialHits(query,limit=6){const words=tokenize(query);if(!words.length)return[];return officialPages.map(p=>{const low=p.text.toLowerCase();let score=0,first=-1;for(const w of words){let pos=0,c=0;while((pos=low.indexOf(w.toLowerCase(),pos))>=0&&c<8){score+=w.length>=3?2:1;if(first<0||pos<first)first=pos;pos+=w.length;c++}}const at=first<0?0:Math.max(0,first-120);return{...p,score,snippet:p.text.replace(/\s+/g,' ').slice(at,at+650)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.page-b.page).slice(0,limit)}
function officialGrounding(query,limit=3){return officialHits(query,limit).map(x=>`[공식 PDF ${x.page}쪽]\n${x.snippet}`).join('\n\n---\n\n')}
function officialFallback(query){const hits=officialHits(query,3);if(!hits.length)return'';return `공식 PDF 근거검색 결과\n\n${hits.map((x,i)=>`${i+1}. PDF ${x.page}쪽\n${x.snippet}`).join('\n\n')}\n\n※ 이 브라우저에 저장된 공식 PDF 로컬 색인에서 찾았습니다. 원문 페이지를 최종 확인하세요.`}
function officialQuestionsFromPage(pageNo){const p=officialPages.find(x=>x.page===Number(pageNo));if(!p)return[];const text=p.text.replace(/\s+/g,' '),chunks=text.split(/[.!?。]\s+|다\.\s+|한다\.\s+|이다\.\s+/).map(x=>x.trim()).filter(x=>x.length>=35&&x.length<=220),allTerms=[...new Set(tokenize(text).filter(x=>x.length>=2&&!/^\d+$/.test(x)))],out=[];for(const sentence of chunks){if(out.length>=3)break;const terms=[...new Set(tokenize(sentence).filter(x=>x.length>=2&&!/^\d+$/.test(x)))].sort((a,b)=>b.length-a.length),ans=terms[0];if(!ans)continue;const distract=allTerms.filter(x=>x!==ans&&x.length>=2).slice(0,24);if(distract.length<3)continue;const stem=sentence.replace(ans,'_____');if(stem===sentence)continue;const seed=(p.page+out.length)%distract.length,choices=[ans,distract[seed],distract[(seed+7)%distract.length],distract[(seed+13)%distract.length]];if(new Set(choices).size!==4)continue;const shift=(p.page+out.length)%4,rot=choices.map((_,i)=>choices[(i+shift)%4]);out.push({id:uid('oq'),subject:'응급처치학개론',chapter:'공식교재',q:`[공식교재 원문회상 · PDF ${p.page}쪽] 가려진 원문 단어는?\n${stem}`,choices:rot,a:rot.indexOf(ans),ex:sentence,source:`${officialMeta.fileName||'공식 PDF'} ${p.page}쪽`,grade:officialMeta.verified?'B':'D',sourcePage:p.page})}return out}
async function deleteOfficialIndex(){if(!confirm('이 브라우저의 공식 PDF 색인을 삭제할까요?'))return;await officialStoreClear();officialPages=[];officialMeta={fileName:'',pageCount:0,verified:false,at:0};render();toast('공식 PDF 색인 삭제 완료')}
async function officialRead(f){if(!f)return;const status=$('#officialStatus');if(status)status.textContent='색인 중…';try{const p=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.worker.min.mjs';const pdf=await p.getDocument({data:await f.arrayBuffer()}).promise,pages=[];let signal='';for(let x=1;x<=pdf.numPages;x++){const pg=await pdf.getPage(x),tc=await pg.getTextContent(),text=tc.items.map(z=>z.str).join(' ').replace(/\s+/g,' ').trim();pages.push({key:`${OFFICIAL_DOC}:${x}`,docId:OFFICIAL_DOC,page:x,text});if(x<=20)signal+=' '+text.slice(0,2500);if(status&&x%5===0)status.textContent=`${x}/${pdf.numPages}쪽 색인 중…`}const nameOk=/소방전술3/i.test(f.name)&&/구급/i.test(f.name),textOk=/(구급|응급의료|환자평가|심폐소생술|기도)/.test(signal),meta={id:OFFICIAL_DOC,fileName:f.name,pageCount:pdf.numPages,verified:nameOk&&textOk,at:Date.now()};await officialReplace(meta,pages);officialPages=pages;officialMeta=meta;if(status)status.textContent=`${pages.length}쪽 로컬 색인 완료 · ${meta.verified?'B 검증사본':'D 출처확인 필요'} · 새로고침 후 유지`;toast('공식 PDF 로컬 색인 완료')}catch(e){if(status)status.textContent='색인 실패 · 기존 색인은 유지됨';toast('PDF 색인 실패: '+String(e.message||e).slice(0,60))}}
function officialSearch(){const q=$('#officialSearch')?.value.trim(),box=$('#officialResults');if(!q||!box)return;const hits=officialHits(q,8);box.innerHTML=hits.length?hits.map(x=>`<div class="note"><div class="row"><b>PDF ${x.page}쪽</b><span class="spacer"></span>${tag(officialMeta.verified?'B':'D')}</div><p class="muted">${esc(x.snippet)}</p><div class="toolbar"><button class="btn small" data-official-tutor="${x.page}">이 페이지로 과외</button><button class="btn small ghost" data-official-question="${x.page}">근거문제 만들기</button></div></div>`).join(''):'<div class="empty">검색 결과 없음</div>';bindOfficialResultButtons()}
function bindOfficialResultButtons(){$$('[data-official-tutor]').forEach(b=>b.onclick=()=>tutorOfficialPage(Number(b.dataset.officialTutor)));$$('[data-official-question]').forEach(b=>b.onclick=()=>addOfficialQuestions(Number(b.dataset.officialQuestion)))}
async function tutorOfficialPage(pageNo){const p=officialPages.find(x=>x.page===Number(pageNo));if(!p)return;const snippet=p.text.replace(/\s+/g,' ').slice(0,1800);state.chat.push({role:'user',text:`공식 PDF ${p.page}쪽 내용을 시험 과외처럼 설명해줘.`});state.chat.push({role:'assistant',text:'생각 중…'});save();state.page='tutor';render();let out;try{out=await askAI(`[공식 PDF ${p.page}쪽]\n${snippet}\n\n위 근거만 사용해 핵심개념 → 시험포인트 → 확인질문 순서로 설명해줘.`)}catch{out=`공식 PDF ${p.page}쪽 근거\n\n${snippet}\n\n[복습]\n- 위 원문에서 정의·숫자·예외를 직접 표시하세요.\n- 이해한 내용을 말로 설명한 뒤 문제로 확인하세요.`}state.chat[state.chat.length-1]={role:'assistant',text:out};save();render()}
function addOfficialQuestions(pageNo){const qs=officialQuestionsFromPage(pageNo);if(!qs.length)return toast('문제를 만들 수 있는 충분한 원문 문장을 찾지 못했습니다.');const existing=new Set(allQ().map(q=>q.q)),fresh=qs.filter(q=>!existing.has(q.q));state.generated.push(...fresh);save();toast(`공식 근거문제 ${fresh.length}개 생성`);go('bank')}

const _resourcesV6=resources;
resources=function(){const status=officialPages.length?`${officialMeta.fileName||'공식 PDF'} · ${officialPages.length}쪽 · ${officialMeta.verified?'B 검증사본':'D 출처확인 필요'} · 새로고침 후 유지`:'미색인',base=_resourcesV6();const panel=`<div class="section"><h2>공식 PDF 로컬 색인</h2><span>IndexedDB 페이지별 영구 저장</span></div><div class="card"><p class="muted">공식 사이트에서 받은 PDF를 선택하면 브라우저 안에서만 페이지별 텍스트를 추출합니다. 서버 업로드 없음.</p><div class="toolbar"><label class="btn primary">PDF 선택<input id="officialPdf" type="file" accept="application/pdf,.pdf" hidden></label>${officialPages.length?'<button class="btn ghost" id="officialDelete">색인 삭제</button>':''}</div><div id="officialStatus" class="tiny muted" style="margin-top:9px">${esc(status)}</div><div class="row stack-mobile" style="margin-top:10px"><input id="officialSearch" class="input" placeholder="예: 쇼크, 기도폐쇄, 소아"><button class="btn" id="officialSearchBtn">검색</button></div><div id="officialResults"></div></div>`;return base.replace('</main>',panel+'</main>')};
const _fallbackTutorV6=fallbackTutor;
fallbackTutor=function(q){return officialFallback(q)||_fallbackTutorV6(q)};
sendChat=async function(){const i=$('#chatInput'),t=i?.value.trim();if(!t)return;state.chat.push({role:'user',text:t});state.chat.push({role:'assistant',text:'생각 중…'});save();render();let out;try{const official=officialGrounding(t,3),notes=retrieve(t).map(n=>(n.summary||n.text).slice(0,1100)).join('\n---\n');out=await askAI(`${official?`[공식 PDF 근거]\n${official}\n\n`:''}${notes?`[내 노트 근거]\n${notes}\n\n`:''}[질문]\n${t}\n\n근거에 있는 사실만 사용해 쉬운 설명 → 시험포인트 → 확인질문 순서로 답해줘. 근거가 부족하면 부족하다고 표시해.`)}catch{out=fallbackTutor(t)}state.chat[state.chat.length-1]={role:'assistant',text:out};save();render()};
const _bindV6=bind;
bind=function(){_bindV6();$('#officialPdf')?.addEventListener('change',e=>officialRead(e.target.files?.[0]));$('#officialSearchBtn')?.addEventListener('click',officialSearch);$('#officialDelete')?.addEventListener('click',deleteOfficialIndex);bindOfficialResultButtons()};
const _runQAV6=runQA;
runQA=function(){const q=_runQAV6(),add=(name,ok,detail='')=>q.rows.push({name,ok:!!ok,detail});add('공식 PDF 영구저장',typeof officialDb==='function'&&typeof officialReplace==='function'&&typeof restoreOfficial==='function'&&'indexedDB' in window);add('공식근거 과외',typeof officialGrounding==='function'&&typeof tutorOfficialPage==='function');add('공식근거 문제생성',typeof officialQuestionsFromPage==='function'&&typeof addOfficialQuestions==='function');q.pass=q.rows.filter(x=>x.ok).length;q.total=q.rows.length;state.qa=q;S.set('qa',q);if(state.page==='home')render();return q};
const _eraseDataV6=eraseData;
eraseData=async function(){if(!confirm('모든 학습데이터를 삭제할까요?'))return;Object.keys(localStorage).filter(k=>k.startsWith(K)).forEach(k=>localStorage.removeItem(k));try{await officialStoreClear()}catch{}location.reload()};
restoreOfficial().finally(()=>setTimeout(()=>runQA(),80));
