const V8_FIRE_DOMAINS=[
{id:'F01',title:'소방조직',desc:'소방기관·소방력·소방활동·조직체계',source:'소방법령Ⅱ · 소방기본법 중심'},
{id:'F02',title:'재난관리',desc:'재난관리체계·예방·대비·대응·복구·긴급구조',source:'소방법령Ⅴ · 재난 및 안전관리 기본법'},
{id:'F03',title:'연소·화재이론',desc:'연소·화재성상·폭발·특수현상·연기',source:'소방전술Ⅰ 화재1·화재2'},
{id:'F04',title:'소화이론',desc:'소화원리·소화약제·적응화재·소화효과',source:'소방전술Ⅰ 화재1·화재2'}
];
const V8_EMS_CHAPTERS=[
['E01','응급의료 개론','제1편'],['E02','소방대원의 안녕','제1편'],['E03','감염방지 및 개인 보호 장비','제1편'],['E04','해부생리학','제1편'],['E05','무선통신 및 기록','제1편'],['E06','환자 들어올리기와 이동','제1편'],['E07','응급의료 장비 사용법','제1편'],
['E08','환자 평가','제2편'],['E09','기도유지','제2편'],['E10','호흡곤란','제2편'],['E11','응급 심장질환','제2편'],['E12','급성 복통','제2편'],['E13','출혈과 쇼크','제2편'],['E14','연부조직 손상','제2편'],['E15','근골격계 손상','제2편'],['E16','머리와 척추 손상','제2편'],['E17','의식 장애','제2편'],['E18','중독 및 알레르기 반응','제2편'],['E19','환경 응급','제2편'],['E20','산부인과','제2편'],['E21','소아','제2편'],['E22','노인','제2편'],['E23','행동 응급','제2편'],['E24','기본소생술','제2편']
].map(([id,title,part])=>({id,title,part}));
let v8StudySubject=S.get('v8StudySubject','fire');
let v8BankFilter=S.get('v8BankFilter','all');
function v8CleanLabel(t){return String(t||'').replaceAll('구급 합격AI','AI과외').replaceAll('구급합격AI','AI과외').replaceAll('무료 로컬 AI','AI').replaceAll('무료 AI','AI').replaceAll('유료 전환 없이 기본모드 사용','근거검색 모드 사용')}
state.chat=state.chat.map(m=>({...m,text:v8CleanLabel(m.text)}));state.ai.status=v8CleanLabel(state.ai.status||'AI 미로딩');S.set('chat',state.chat);
function shell(main,side=''){return `<div class="app"><header class="top"><div class="topin"><span class="logo">🔥</span><span class="brand">AI과외</span><span class="spacer"></span><span class="chip">${dday()}</span></div></header><div class="layout"><main class="main"><section class="screen">${main}</section></main>${side?`<aside class="side">${side}</aside>`:''}</div>${nav()}</div>`}
function v8SubjectSwitch(){return `<div class="v8-subject-switch"><button data-v8-subject="fire" class="${v8StudySubject==='fire'?'active':''}">소방학개론</button><button data-v8-subject="ems" class="${v8StudySubject==='ems'?'active':''}">응급처치학개론</button></div>`}
function study(){const s=stat(),mins=state.profile.daily||40;if(v8StudySubject==='fire'){return shell(`<div class="screen-head"><div><h1>소방학개론</h1><p>공식 출제범위 4대 영역만 학습</p></div><span class="chip good">25문항</span></div>${v8SubjectSwitch()}<div class="v8-scope-head"><b>시험범위</b><span class="scope-pill">범위 밖 자동 제외</span></div><div class="screen-scroll"><div class="v8-scope-grid">${V8_FIRE_DOMAINS.map((d,i)=>`<div class="v8-scope-card"><span class="scope-no">0${i+1}</span><h3>${d.title}</h3><p>${d.desc}</p><div class="source-mini">${d.source}</div></div>`).join('')}</div><div class="card compact-card" style="margin-top:8px"><div class="row"><b>오늘 권장 학습</b><span class="spacer"></span><span class="tiny muted">${mins}분</span></div><div class="plan-line">${plan(mins).join(' → ')}</div><div class="toolbar" style="margin-top:8px"><button class="btn primary small" data-nav="bank">소방학 문제</button><button class="btn small" data-v8-prompt="연소·화재이론을 시험범위 안에서 핵심부터 과외해줘">AI과외</button><button class="btn small ghost" data-nav="resources">공식근거</button></div></div></div>`)}return shell(`<div class="screen-head"><div><h1>응급처치학개론</h1><p>2026 소방전술3 공식 구조 24장</p></div><span class="chip good">40문항</span></div>${v8SubjectSwitch()}<div class="v8-scope-head"><b>공식 교재 구조</b><span class="scope-pill">24장 전부 범위지도화</span></div><div class="screen-scroll"><div class="v8-chapter-list">${V8_EMS_CHAPTERS.map(c=>`<div class="v8-chapter-row"><span>${c.id}</span><b>${c.title}</b><small>${c.part}</small></div>`).join('')}</div></div>`)}
function tutor(){return shell(`<div class="screen-head"><div><h1>AI과외</h1><p>공식 근거 → 내 노트 → AI 순서</p></div><button class="btn small" id="loadAI">${state.ai.engine?'AI 준비됨':'AI 불러오기'}</button></div><div class="v8-quick"><button data-v8-prompt="연소·화재이론 핵심을 시험범위 안에서 설명해줘">🔥 연소·화재</button><button data-v8-prompt="소화이론을 공식범위 중심으로 비교해서 설명해줘">🧯 소화이론</button><button data-v8-prompt="쇼크를 공식교재 근거로 시험에 나오게 설명해줘">🩸 쇼크</button><button data-v8-prompt="기본소생술을 단계별로 확인문제까지 내줘">❤️ 기본소생술</button></div><div class="ai-strip"><span class="dot ${state.ai.engine?'ok':''}"></span><b>${v8CleanLabel(state.ai.status)}</b>${officialPages.length?`<span class="spacer"></span><small>구급 공식 ${officialPages.length}쪽</small>`:''}</div><div id="chat" class="chat flex-chat">${state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(v8CleanLabel(m.text))}</div>`).join('')}</div><div class="chatbox fixed-input"><input id="chatInput" class="input" placeholder="예: 연소범위와 폭발범위를 비교해줘"><button class="btn primary" id="sendChat">보내기</button></div>`)}
function notes(){if(noteView==='saved'){const list=state.notes.length?state.notes.slice().reverse().map(n=>`<div class="note compact-note"><div class="row"><b>${esc(n.title)}</b><span class="spacer"></span>${tag(n.grade||'D')}</div><p>${esc((n.summary||n.text).slice(0,330))}${(n.summary||n.text).length>330?'…':''}</p><div class="toolbar"><button class="btn small" data-note-q="${n.id}">문제</button><button class="btn small" data-note-tutor="${n.id}">AI과외</button><button class="btn small ghost" data-note-del="${n.id}">삭제</button></div></div>`).join(''):'<div class="empty">저장된 노트가 없습니다.</div>';return shell(`<div class="screen-head"><div><h1>내 노트</h1><p>저장노트 ${state.notes.length}개</p></div></div><div class="seg"><button data-note-view="write">업로드/입력</button><button class="active" data-note-view="saved">저장노트</button></div><div class="screen-scroll">${list}</div>`)}return shell(`<div class="screen-head"><div><h1>PDF · 사진 · 필기</h1><p>기기 안에서 추출 후 직접 확인</p></div></div><div class="seg"><button class="active" data-note-view="write">업로드/입력</button><button data-note-view="saved">저장노트 ${state.notes.length}</button></div><div class="v8-upload-zone"><div class="v8-upload-head"><span class="v8-upload-icon">📎</span><div><b>PDF · 사진 · TXT 가져오기</b><p>PDF 텍스트 추출 / 사진 OCR / TXT 즉시 읽기</p></div><span class="spacer"></span><label class="btn primary small">파일 선택<input id="fileInput" type="file" accept="image/*,.pdf,.txt,text/plain,application/pdf" hidden></label></div><div class="v8-upload-status"><span class="v8-engine-chip">PDF.js</span><span class="v8-engine-chip">OCR</span><span class="v8-engine-chip">서버 업로드 없음</span><button class="btn small ghost" id="uploadDiag">엔진 점검</button></div><div id="uploadProgress" class="v8-file-progress" hidden><i></i></div><div id="fileStatus" class="tiny muted" style="margin-top:7px">파일을 선택하거나 아래에 직접 입력하세요.</div></div><textarea id="noteText" class="textarea compact-textarea" placeholder="필기·강의 메모·요약할 텍스트를 입력하세요"></textarea><div id="noteResult" class="note-result"></div><div class="screen-actions four"><button class="btn primary" id="basicSum">기본정리</button><button class="btn" id="aiSum">AI 정리</button><button class="btn" id="saveNote">저장</button><button class="btn ghost" id="clearNote">비우기</button></div>`)}
function v8ClassifyText(t){const s=String(t).toLowerCase();const fire=['연소','화재','소화','플래시오버','백드래프트','폭발','재난관리','소방조직','소방력','소방기본법'];const ems=['환자','응급','쇼크','기도','호흡','심장','소아','산부인과','골절','출혈','심폐소생술'];let f=fire.reduce((a,k)=>a+(s.includes(k)?1:0),0),e=ems.reduce((a,k)=>a+(s.includes(k)?1:0),0);return f>e?'소방학개론':'응급처치학개론'}
function makeQuestions(n){const subject=v8ClassifyText(n.summary||n.text),lines=String(n.summary||n.text).split(/\n+/).map(x=>x.trim()).filter(x=>x.length>18).slice(0,5);return lines.map((line,i)=>{const words=tokenize(line).sort((a,b)=>b.length-a.length),a=words[0]||'핵심어',stem=line.replace(a,'_____'),cs=[a,'원문 확인 필요','다른 개념','해당 없음'],rot=cs.map((_,j)=>cs[(j+i)%4]);return{id:uid('nq'),subject,chapter:'내 노트',q:`[내 노트] 빈칸 핵심어는?\n${stem}`,choices:rot,a:rot.indexOf(a),ex:line,source:`내 노트: ${n.title}`,grade:'D'}})}
async function v8ImportFirst(urls){let last;for(const u of urls){try{return await import(u)}catch(e){last=e}}throw last||Error('모듈 로드 실패')}
async function fileRead(f){if(!f)return;const st=$('#fileStatus'),bar=$('#uploadProgress'),fill=bar?.querySelector('i');const set=(msg,p=null)=>{if(st)st.textContent=msg;if(bar&&p!==null){bar.hidden=false;bar.style.setProperty('--progress',`${Math.max(0,Math.min(100,p))}%`)}if(fill&&p!==null)fill.style.width=`${Math.max(0,Math.min(100,p))}%`};set(`${f.name} 확인 중…`,2);try{let t='';const name=f.name.toLowerCase();if(f.type==='application/pdf'||name.endsWith('.pdf')){const p=await v8ImportFirst(['https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.min.mjs','https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/legacy/build/pdf.min.mjs','https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.min.mjs']);p.GlobalWorkerOptions.workerSrc=p.version==='6.3.289'?'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.min.mjs':'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.worker.min.mjs';const pdf=await p.getDocument({data:await f.arrayBuffer()}).promise,o=[];for(let x=1;x<=pdf.numPages;x++){const pg=await pdf.getPage(x),tc=await pg.getTextContent();o.push(`[${x}쪽] ${tc.items.map(z=>z.str).join(' ')}`);if(x%5===0||x===pdf.numPages){set(`PDF ${x}/${pdf.numPages}쪽 추출 중…`,Math.round(x/pdf.numPages*96));await new Promise(r=>setTimeout(r,0))}}t=o.join('\n\n')}else if(f.type.startsWith('image/')||/\.(png|jpg|jpeg|webp|bmp)$/i.test(name)){set('사진 OCR 엔진 준비 중…',12);const T=await v8ImportFirst(['https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.esm.min.js','https://esm.sh/tesseract.js@7.0.0']);const w=await T.createWorker('kor+eng');set('사진 글자 인식 중…',45);const r=await w.recognize(f);await w.terminate();t=r.data.text}else if(f.type.startsWith('text/')||name.endsWith('.txt'))t=await f.text();else throw Error('지원하지 않는 파일 형식입니다.');if(!t.trim())throw Error('추출된 텍스트가 없습니다. 스캔 PDF는 사진 OCR 방식이 필요할 수 있습니다.');$('#noteText').value=t;set(`추출 완료 · ${v8ClassifyText(t)} 가능성 · 원본 확인 필요`,100);setTimeout(()=>{if(bar)bar.hidden=true},1200)}catch(e){set(`추출 실패 · ${String(e.message||e).slice(0,90)}`,0);toast('파일 추출 실패')}}
async function loadAI(){if(state.ai.engine||state.ai.loading)return;state.ai.loading=true;state.ai.status='AI 불러오는 중';render();try{if(!navigator.gpu)throw Error('이 기기는 WebGPU를 지원하지 않음');const m=await import('https://esm.run/@mlc-ai/web-llm@0.2.85');const list=m.prebuiltAppConfig?.model_list||[],model=list.find(x=>/0\.5B.*Instruct/i.test(x.model_id))||list.sort((a,b)=>(a.vram_required_MB||99999)-(b.vram_required_MB||99999))[0];if(!model)throw Error('사용 가능한 로컬 모델 없음');state.ai.engine=await m.CreateMLCEngine(model.model_id,{initProgressCallback:p=>{state.ai.status=v8CleanLabel(p.text||'AI 로딩 중');state.ai.progress=p.progress||0}});state.ai.status='AI 준비 완료';state.ai.error='';toast('AI 준비 완료')}catch(e){state.ai.status='근거검색 모드';state.ai.error=String(e.message||e);toast('AI를 사용할 수 없어 근거검색 모드로 전환')}finally{state.ai.loading=false;render()}}
async function v8UploadDiag(){const st=$('#fileStatus');if(st)st.textContent='업로드 엔진 점검 중…';try{await v8ImportFirst(['https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.min.mjs','https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/legacy/build/pdf.min.mjs']);await v8ImportFirst(['https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.esm.min.js','https://esm.sh/tesseract.js@7.0.0']);if(st)st.textContent='엔진 정상 · PDF / 사진 OCR / TXT 준비됨';toast('업로드 엔진 정상')}catch(e){if(st)st.textContent='엔진 일부 로드 실패 · 직접입력은 계속 사용 가능';toast('업로드 엔진 점검 실패')}}
