'use strict';
(()=>{
const A=window.AITUTOR=window.AITUTOR||{hooks:[]};
A.name='AI과외';
A.fire=[
{id:'F01',title:'소방조직',subject:'소방학개론',summary:'소방의 조직·기관·소방력·소방활동 체계',keywords:['소방조직','소방기관','소방력','소방용수','소방활동','119종합상황실']},
{id:'F02',title:'재난관리',subject:'소방학개론',summary:'재난관리 총칙·기구·계획·예방·대비·대응·복구',keywords:['재난관리','안전관리기구','안전관리계획','재난의 예방','재난의 대비','재난의 대응','긴급구조','재난의 복구']},
{id:'F03',title:'연소·화재이론',subject:'소방학개론',summary:'화재·열전달·연소·화재진행·특수현상·폭발',keywords:['화재의 개념','화재성상','열 발생과 전달','연소이론','연소의 4요소','화재의 진행단계','백드래프트','플래시오버','연소생성물','폭발','폭연','폭굉']},
{id:'F04',title:'소화이론',subject:'소방학개론',summary:'소화원리와 물·포·CO₂·가스계·분말 소화약제',keywords:['소화이론','소화의 원리','소화약제','물 소화약제','포 소화약제','이산화탄소 소화약제','할로겐화합물','불활성기체','분말 소화약제']}
];
A.ems=[
['E01','응급의료 개론',['응급의료서비스 체계','응급구조사의 법적 책임']],['E02','소방대원의 안녕',['정신적인 스트레스','개인 안전']],['E03','감염방지 및 개인 보호 장비',['감염예방','소독과 멸균','감염 관리','개인 보호 장비']],['E04','해부생리학',['인체 기본 해부학','인체 해부생리학']],['E05','무선통신 및 기록',['의사소통','통신 체계','무선통신','기록지']],['E06','환자 들어올리기와 이동',['환자 이동','신체 역학','환자 자세']],['E07','응급의료 장비 사용법',['기도확보유지 장비','호흡유지 장비','순환유지 장비','외상처치 장비']],['E08','환자 평가',['현장 확인','1차 평가','2차 평가','재평가']],['E09','기도유지',['기도확보','기도유지 보조기구','인공호흡','흡인','산소 치료']],['E10','호흡곤란',['정상호흡','비정상호흡','호흡곤란','연기 흡입']],['E11','응급 심장질환',['심혈관계','심질환','심장마비','제세동','자동 체외 심장충격기']],['E12','급성 복통',['복통','환자 평가','복통유발 질병']],['E13','출혈과 쇼크',['출혈','외부 출혈','내부 출혈','저혈량 쇼크']],['E14','연부조직 손상',['연부조직 손상','화상']],['E15','근골격계 손상',['근골격계','골절','부목']],['E16','머리와 척추 손상',['척추 손상','머리 손상','헬멧 제거']],['E17','의식 장애',['의식 장애','당뇨','경련','뇌졸중']],['E18','중독 및 알레르기 반응',['중독','알레르기 반응','아나필락시스']],['E19','환경 응급',['한랭손상','열 손상','익수','물림','쏘임']],['E20','산부인과',['임신','분만','정상 분만','분만 합병증','부인과 응급']],['E21','소아',['소아','발달 과정','소아 기도','소아 외상']],['E22','노인',['노인환자','노인의 해부와 생리']],['E23','행동 응급',['행동 응급','정신응급']],['E24','기본소생술',['기본소생술','기도유지 방법','가슴압박','심폐소생술','기도 내 이물질 제거']]
].map(([id,title,keywords])=>({id,title,subject:'응급처치학개론',keywords,summary:keywords.slice(0,4).join(' · ')}));
A.studySubject=S.get('v8-study-subject','fire');A.studyPage=S.get('v8-study-page',0);A.bankSubject=S.get('v8-bank-subject','all');
A.clean=v=>String(v||'').replace(/무료\s*로컬\s*AI/g,'AI').replace(/무료\s*AI/g,'AI').replace(/무료\s*소형모델/g,'로컬 소형모델');
if(state.ai?.status)state.ai.status=A.clean(state.ai.status);if(Array.isArray(state.chat))state.chat=state.chat.map(m=>({...m,text:A.clean(m.text)}));
shell=function(main,side=''){return `<div class="app"><header class="top"><div class="topin"><span class="logo">🔥</span><span class="brand">AI과외</span><span class="brand-sub">소방학 · 응급처치</span><span class="spacer"></span><span class="chip">${dday()}</span></div></header><div class="layout"><main class="main"><section class="screen">${main}</section></main>${side?`<aside class="side">${side}</aside>`:''}</div>${nav()}</div>`};
loadAI=async function(){if(state.ai.engine||state.ai.loading)return;state.ai.loading=true;state.ai.status='AI 불러오는 중';render();try{if(!navigator.gpu)throw Error('이 기기는 WebGPU를 지원하지 않음');const m=await import('https://esm.run/@mlc-ai/web-llm@0.2.85');const list=m.prebuiltAppConfig?.model_list||[];const model=list.find(x=>/0\.5B.*Instruct/i.test(x.model_id))||list.sort((a,b)=>(a.vram_required_MB||99999)-(b.vram_required_MB||99999))[0];if(!model)throw Error('로컬 소형모델 없음');state.ai.engine=await m.CreateMLCEngine(model.model_id,{initProgressCallback:p=>{state.ai.status=A.clean(p.text||'AI 로딩 중');state.ai.progress=p.progress||0}});state.ai.status='AI 준비 완료';state.ai.error='';toast('AI 준비 완료')}catch(e){state.ai.status='근거검색 모드';state.ai.error=String(e.message||e);toast('AI 모델을 쓸 수 없어 근거검색 모드로 계속합니다')}finally{state.ai.loading=false;render()}};
tutor=function(){const presets=[['소방학','연소·화재이론 핵심을 공식 근거로 과외해줘'],['재난관리','재난관리의 예방·대비·대응·복구를 구분해서 설명해줘'],['쇼크','출혈과 쇼크를 시험포인트 중심으로 설명해줘'],['BLS','기본소생술을 공식 근거로 정리해줘']];return shell(`<div class="screen-head"><div><h1>AI 1:1 과외</h1><p>소방학·응급처치 공식근거 → 내 노트 → AI</p></div><button class="btn small" id="loadAI">${state.ai.engine?'AI 준비됨':'AI'}</button></div><div class="ai-strip"><span class="dot ${state.ai.engine?'ok':''}"></span><b>${esc(A.clean(state.ai.status))}</b><span class="spacer"></span><small>범위잠금</small></div><div class="tutor-presets">${presets.map(([l,q])=>`<button class="preset-chip" data-v8-preset="${esc(q)}">${l}</button>`).join('')}</div><div id="chat" class="chat flex-chat">${state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(A.clean(m.text))}</div>`).join('')}</div><div class="chatbox fixed-input"><input id="chatInput" class="input" placeholder="소방학 또는 응급처치 질문"><button class="btn primary" id="sendChat">보내기</button></div>`)};
study=function(){const isFire=A.studySubject==='fire',topics=isFire?A.fire:A.ems,pageSize=isFire?4:6,maxPage=Math.max(0,Math.ceil(topics.length/pageSize)-1);A.studyPage=Math.min(A.studyPage,maxPage);const shown=topics.slice(A.studyPage*pageSize,A.studyPage*pageSize+pageSize);return shell(`<div class="screen-head"><div><h1>과목별 학습</h1><p>시험범위만 · 소방학 25 + 응급처치 40</p></div></div><div class="subject-switch"><button class="${isFire?'active':''}" data-v8-study-subject="fire"><b>소방학개론</b><small>4대 영역</small></button><button class="${!isFire?'active':''}" data-v8-study-subject="ems"><b>응급처치학개론</b><small>공식교재 24장</small></button></div><div class="topic-grid screen-scroll">${shown.map(t=>`<article class="topic-card"><div><span class="topic-id">${t.id}</span><h3>${esc(t.title)}</h3><p>${esc(t.summary||'')}</p></div><div class="topic-actions"><button class="btn small" data-v8-topic-tutor="${t.id}">AI 과외</button><button class="btn small ghost" data-v8-topic-bank="${isFire?'소방학개론':'응급처치학개론'}">문제</button></div></article>`).join('')}</div>${maxPage?`<div class="screen-actions"><button class="btn" data-v8-study-page="${Math.max(0,A.studyPage-1)}" ${A.studyPage===0?'disabled':''}>← 이전</button><span class="pager">${A.studyPage+1}/${maxPage+1}</span><button class="btn" data-v8-study-page="${Math.min(maxPage,A.studyPage+1)}" ${A.studyPage===maxPage?'disabled':''}>다음 →</button></div>`:''}`)};
home=function(){const s=stat(),fireCount=allQ().filter(q=>q.subject==='소방학개론').length,emsCount=allQ().filter(q=>q.subject==='응급처치학개론').length;return shell(`<div class="home-v8"><section class="today-card"><div class="row"><span class="eyebrow">${phase()}</span><span class="spacer"></span><span class="chip good">${state.profile.daily||40}분</span></div><h1>${dday()==='미설정'?'오늘 학습':dday()+' · 오늘 학습'}</h1><p>소방학과 응급처치를 같이 추적하고 시험범위 밖은 차단합니다.</p><button class="btn primary block" data-nav="study">오늘 공부 시작</button></section><section class="subject-dashboard"><button data-v8-home-subject="fire"><span>25문항</span><b>소방학개론</b><small>조직 · 재난 · 연소/화재 · 소화</small><strong>${fireCount}문제 ›</strong></button><button data-v8-home-subject="ems"><span>40문항</span><b>응급처치학개론</b><small>공식교재 24장</small><strong>${emsCount}문제 ›</strong></button></section><div class="mini-stats"><div><span>정답률</span><b>${s.acc}%</b></div><div><span>위험오답</span><b>${s.risky}</b></div><div><span>복습예정</span><b>${s.due}</b></div><div><span>모의고사</span><b>${state.examHistory.length}</b></div></div></div>`)};
bank=function(){const all=allQ(),qs=A.bankSubject==='all'?all:all.filter(q=>q.subject===A.bankSubject);if(!qs.length)return shell(`<div class="screen-head"><div><h1>문제</h1><p>선택 과목에 문제가 없습니다.</p></div></div><div class="subject-filter"><button data-v8-bank-subject="all">전체</button><button data-v8-bank-subject="소방학개론">소방학</button><button data-v8-bank-subject="응급처치학개론">응급처치</button></div><div class="empty fill">공식근거 문제를 누적하면 여기에 표시됩니다.</div>`);bankIndex=Math.max(0,Math.min(bankIndex,qs.length-1));const q=qs[bankIndex];return shell(`<div class="screen-head"><div><h1>문제</h1><p>${bankIndex+1} / ${qs.length} · ${esc(q.subject)}</p></div><span class="chip">${q.grade==='A'?'공식':q.grade==='B'?'검증':'학습'}</span></div><div class="subject-filter"><button class="${A.bankSubject==='all'?'active':''}" data-v8-bank-subject="all">전체</button><button class="${A.bankSubject==='소방학개론'?'active':''}" data-v8-bank-subject="소방학개론">소방학</button><button class="${A.bankSubject==='응급처치학개론'?'active':''}" data-v8-bank-subject="응급처치학개론">응급처치</button></div><div class="question-scroll screen-scroll">${qcard(q)}</div><div class="screen-actions"><button class="btn" id="bankPrev" ${bankIndex===0?'disabled':''}>← 이전</button><span class="pager">${bankIndex+1}/${qs.length}</span><button class="btn primary" id="bankNext" ${bankIndex===qs.length-1?'disabled':''}>다음 →</button></div>`)};
A.bindCore=()=>{$$('[data-v8-study-subject]').forEach(b=>b.onclick=()=>{A.studySubject=b.dataset.v8StudySubject;A.studyPage=0;S.set('v8-study-subject',A.studySubject);S.set('v8-study-page',0);render()});$$('[data-v8-study-page]').forEach(b=>b.onclick=()=>{A.studyPage=Number(b.dataset.v8StudyPage)||0;S.set('v8-study-page',A.studyPage);render()});$$('[data-v8-topic-tutor]').forEach(b=>b.onclick=()=>{const t=[...A.fire,...A.ems].find(x=>x.id===b.dataset.v8TopicTutor);if(!t)return;state.chat.push({role:'user',text:`${t.subject} > ${t.title}를 시험범위 공식근거로 과외해줘`});save();go('tutor')});$$('[data-v8-topic-bank]').forEach(b=>b.onclick=()=>{A.bankSubject=b.dataset.v8TopicBank;S.set('v8-bank-subject',A.bankSubject);bankIndex=0;go('bank')});$$('[data-v8-home-subject]').forEach(b=>b.onclick=()=>{A.studySubject=b.dataset.v8HomeSubject;A.studyPage=0;S.set('v8-study-subject',A.studySubject);go('study')});$$('[data-v8-bank-subject]').forEach(b=>b.onclick=()=>{A.bankSubject=b.dataset.v8BankSubject;S.set('v8-bank-subject',A.bankSubject);bankIndex=0;render()});$$('[data-v8-preset]').forEach(b=>b.onclick=()=>{const i=$('#chatInput');if(i){i.value=b.dataset.v8Preset;i.focus()}});$$('[data-retry]').forEach(b=>b.onclick=()=>{const q=allQ().find(q=>q.id===b.dataset.retry);if(!q)return;A.bankSubject=q.subject;S.set('v8-bank-subject',A.bankSubject);const f=allQ().filter(x=>x.subject===A.bankSubject);bankIndex=Math.max(0,f.findIndex(x=>x.id===q.id));go('bank')})};
})();
