'use strict';
(()=>{
const A=window.AITUTOR||{};
A.v83Subject=S.get('v83-subject',A.studySubject||'fire');
A.v83Scope=S.get('v83-scope',A.v83Subject==='fire'?'F01':'E01');
A.v83Concept=S.get('v83-concept','');
A.v83BankScope=S.get('v83-bank-scope','');
A.v83PendingSearch='';
function topics(){return A.v83Subject==='fire'?(A.studyDetailFire||A.fire):(A.studyDetailEms||A.ems)}
function subjectName(){return A.v83Subject==='fire'?'소방학개론':'응급처치학개론'}
function subjectCount(){return A.v83Subject==='fire'?'25문항':'40문항'}
function scopeOf(){const list=topics();let x=list.find(t=>t.id===A.v83Scope);if(!x){x=list[0];A.v83Scope=x?.id||''}return x}
function conceptsOf(t){return Array.isArray(t?.concepts)&&t.concepts.length?t.concepts:(t?.keywords||[])}
function questionMatch(q,t){return q.subject===subjectName()&&(q.scopeId===t.id||q.chapterId===t.id||q.chapter===t.title)}
function scopeStats(t){const qs=allQ().filter(q=>questionMatch(q,t)),ids=new Set(qs.map(q=>q.id)),tried=Object.keys(state.answers).filter(id=>ids.has(id)).length,wrong=state.wrongs.filter(w=>!w.resolved&&ids.has(w.qid)).length,pages=(A.pages||[]).filter(p=>p.scopeAllowed&&p.scopeId===t.id).length;return{qs:qs.length,tried,wrong,pages}}
function subjectStats(name){const qs=allQ().filter(q=>q.subject===name),ids=new Set(qs.map(q=>q.id)),tried=Object.keys(state.answers).filter(id=>ids.has(id)).length,correct=Object.entries(state.answers).filter(([id,a])=>{const q=qs.find(x=>x.id===id);return q&&a===q.a}).length,acc=tried?Math.round(correct/tried*100):0,wrong=state.wrongs.filter(w=>!w.resolved&&ids.has(w.qid)).length;return{qs:qs.length,tried,acc,wrong}}
function conceptHits(t,c){try{return typeof A.hits==='function'?A.hits(c,t.subject||subjectName(),30):[]}catch{return[]}}
function selectScope(id){A.v83Scope=id;A.v83Concept='';S.set('v83-scope',id);S.set('v83-concept','');render()}
function selectSubject(id){A.v83Subject=id;A.v83Scope=id==='fire'?'F01':'E01';A.v83Concept='';S.set('v83-subject',id);S.set('v83-scope',A.v83Scope);S.set('v83-concept','');render()}
function conceptPrompt(t,c){return `${subjectName()} > ${t.title} > ${c}를 시험범위 안에서 공식 근거 중심으로 과외해줘. 핵심개념, 자주 헷갈리는 점, 암기포인트, 확인문제 순서로 설명해줘.`}
function homeV83(){const s=stat(),f=subjectStats('소방학개론'),e=subjectStats('응급처치학개론'),due=s.due||0;return shell(`<div class="v83-home"><section class="v83-hero"><div><span class="eyebrow">${phase()}</span><h1>${dday()==='미설정'?'오늘 학습':dday()+' · 오늘 학습'}</h1><p>오늘 필요한 것만 이어서 공부합니다.</p></div><button class="btn primary" data-nav="study">학습 시작</button></section><section class="v83-subjects"><button data-v83-home-subject="fire"><div><span>소방학개론 · 25</span><b>${f.acc}%</b></div><small>${f.tried}/${f.qs} 풀이 · 오답 ${f.wrong}</small></button><button data-v83-home-subject="ems"><div><span>응급처치학개론 · 40</span><b>${e.acc}%</b></div><small>${e.tried}/${e.qs} 풀이 · 오답 ${e.wrong}</small></button></section><section class="v83-today"><div class="panel-title"><b>오늘 할 일</b><span>${state.profile.daily||40}분</span></div><button data-nav="wrong"><span>01</span><div><b>오답 복습</b><small>${due}문제 예정</small></div><strong>›</strong></button><button data-nav="bank"><span>02</span><div><b>문제 풀이</b><small>검증문제부터 진행</small></div><strong>›</strong></button><button data-nav="notes"><span>03</span><div><b>필기·PDF</b><small>업로드 자료 정리</small></div><strong>›</strong></button></section></div>`)}
function studyV83(){const t=scopeOf(),list=topics(),cs=conceptsOf(t);if(!A.v83Concept||!cs.includes(A.v83Concept))A.v83Concept=cs[0]||'';const c=A.v83Concept,st=scopeStats(t),hits=c?conceptHits(t,c):[];return shell(`<div class="screen-head v83-head"><div><h1>학습</h1><p>과목 → 단원 → 세부개념</p></div><span class="chip good">${subjectCount()}</span></div><div class="v83-subject-switch"><button class="${A.v83Subject==='fire'?'active':''}" data-v83-subject="fire">소방학개론</button><button class="${A.v83Subject==='ems'?'active':''}" data-v83-subject="ems">응급처치학개론</button></div><div class="v83-study"><aside class="v83-scope-rail">${list.map(x=>{const z=scopeStats(x);return `<button class="${x.id===t.id?'active':''}" data-v83-scope="${x.id}"><span>${x.id}</span><b>${esc(x.title)}</b><small>${z.qs}문제 · 근거 ${z.pages}쪽</small></button>`}).join('')}</aside><section class="v83-detail"><div class="v83-detail-head"><div><span>${t.id} · ${subjectName()}</span><h2>${esc(t.title)}</h2></div><div class="v83-metrics"><span>문제 <b>${st.qs}</b></span><span>풀이 <b>${st.tried}</b></span><span>오답 <b>${st.wrong}</b></span><span>근거 <b>${st.pages}</b></span></div></div><div class="v83-concepts">${cs.map(x=>`<button class="${x===c?'active':''}" data-v83-concept="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="v83-focus"><span class="tiny muted">선택한 세부개념</span><h3>${esc(c||'세부개념을 선택하세요')}</h3><p>${hits.length?`공식 시험범위 근거 ${hits.length}개 페이지가 연결되어 있습니다.`:'현재 로컬 색인에서 직접 연결된 공식 페이지가 없습니다. 공식 PDF를 색인하면 근거가 연결됩니다.'}</p><div class="v83-focus-actions"><button class="btn primary" data-v83-concept-tutor>AI과외</button><button class="btn" data-v83-concept-bank>관련문제</button><button class="btn ghost" data-v83-concept-source>공식근거</button></div></div></section></div>`)}
function bankV83(){let qs=allQ();if(A.bankSubject!=='all')qs=qs.filter(q=>q.subject===A.bankSubject);if(A.v83BankScope)qs=qs.filter(q=>q.scopeId===A.v83BankScope||q.chapterId===A.v83BankScope||(A.fire||[]).find(x=>x.id===A.v83BankScope)?.title===q.chapter||(A.ems||[]).find(x=>x.id===A.v83BankScope)?.title===q.chapter);if(!qs.length)return shell(`<div class="screen-head"><div><h1>문제</h1><p>${A.v83BankScope?'선택 단원의 검증문제가 아직 없습니다.':'선택 과목에 문제가 없습니다.'}</p></div></div><div class="subject-filter"><button class="${A.bankSubject==='all'?'active':''}" data-v8-bank-subject="all">전체</button><button class="${A.bankSubject==='소방학개론'?'active':''}" data-v8-bank-subject="소방학개론">소방학</button><button class="${A.bankSubject==='응급처치학개론'?'active':''}" data-v8-bank-subject="응급처치학개론">응급처치</button></div>${A.v83BankScope?`<button class="btn small ghost v83-clear-filter" data-v83-clear-bank>단원 필터 해제</button>`:''}<div class="empty fill">공식근거 문제를 검증해 누적합니다.</div>`);bankIndex=Math.max(0,Math.min(bankIndex,qs.length-1));const q=qs[bankIndex],scopeLabel=A.v83BankScope?((A.fire||[]).find(x=>x.id===A.v83BankScope)||(A.ems||[]).find(x=>x.id===A.v83BankScope))?.title:'';return shell(`<div class="screen-head"><div><h1>문제</h1><p>${bankIndex+1}/${qs.length}${scopeLabel?' · '+esc(scopeLabel):' · '+esc(q.subject)}</p></div>${A.v83BankScope?'<button class="btn small ghost" data-v83-clear-bank>필터 해제</button>':`<span class="chip">${q.grade==='A'?'공식':q.grade==='B'?'검증':'학습'}</span>`}</div><div class="subject-filter"><button class="${A.bankSubject==='all'?'active':''}" data-v8-bank-subject="all">전체</button><button class="${A.bankSubject==='소방학개론'?'active':''}" data-v8-bank-subject="소방학개론">소방학</button><button class="${A.bankSubject==='응급처치학개론'?'active':''}" data-v8-bank-subject="응급처치학개론">응급처치</button></div><div class="question-scroll screen-scroll">${qcard(q)}</div><div class="screen-actions"><button class="btn" id="bankPrev" ${bankIndex===0?'disabled':''}>← 이전</button><span class="pager">${bankIndex+1}/${qs.length}</span><button class="btn primary" id="bankNext" ${bankIndex===qs.length-1?'disabled':''}>다음 →</button></div>`)}
function resourcesV83(){if(!['sources','search'].includes(A.resourceTab))A.resourceTab='sources';const defs=A.sourceDefs||[],docs=A.docs||[],pages=A.pages||[];if(A.resourceTab==='sources')return shell(`<div class="screen-head"><div><h1>공식자료</h1><p>원문 등록과 범위 색인만 관리</p></div></div><div class="v83-resource-tabs"><button class="active" data-v8-resource-tab="sources">공식 PDF</button><button data-v8-resource-tab="search">근거검색</button></div><label class="btn primary block">공식 PDF 추가<input id="v8OfficialFiles" type="file" accept="application/pdf,.pdf" multiple hidden></label><div id="v8OfficialStatus" class="tiny muted">구급 · 화재1/2 · 소방법령2/5 우선</div><div class="screen-scroll v83-source-list">${defs.map(d=>{const doc=docs.find(x=>x.id===d.id),ps=pages.filter(p=>p.docId===d.id),ins=ps.filter(p=>p.scopeAllowed).length;return `<div class="v83-source-row ${d.allowed?'':'reference'}"><div><span class="tag ${d.allowed?'a':'d'}">${d.allowed?'시험원천':'참고'}</span><b>${esc(d.title)}</b><small>${doc?`${doc.pageCount||ps.length}쪽 · 범위 ${ins}쪽`:'미등록'}</small></div>${doc?`<button class="btn small ghost" data-v8-source-delete="${d.id}">삭제</button>`:''}</div>`}).join('')}</div>`);return shell(`<div class="screen-head"><div><h1>공식근거 검색</h1><p>시험범위로 허용된 원문만 검색</p></div></div><div class="v83-resource-tabs"><button data-v8-resource-tab="sources">공식 PDF</button><button class="active" data-v8-resource-tab="search">근거검색</button></div><div class="search-row"><input id="v8SourceSearch" class="input" value="${esc(A.v83PendingSearch||'')}" placeholder="플래시오버, 쇼크, 재난대응"><button class="btn primary" id="v8SourceSearchBtn">검색</button></div><div id="v8SourceResults" class="screen-scroll"><div class="empty">검색어를 입력하세요.</div></div>`)}
home=homeV83;study=studyV83;bank=bankV83;resources=resourcesV83;
const baseBind=bind;
bind=function(){baseBind();$$('[data-v83-subject]').forEach(b=>b.onclick=()=>selectSubject(b.dataset.v83Subject));$$('[data-v83-home-subject]').forEach(b=>b.onclick=()=>{selectSubject(b.dataset.v83HomeSubject);go('study')});$$('[data-v83-scope]').forEach(b=>b.onclick=()=>selectScope(b.dataset.v83Scope));$$('[data-v83-concept]').forEach(b=>b.onclick=()=>{A.v83Concept=b.dataset.v83Concept;S.set('v83-concept',A.v83Concept);render()});$('[data-v83-concept-tutor]')?.addEventListener('click',()=>{const t=scopeOf(),c=A.v83Concept;if(!c)return;state.chat.push({role:'user',text:conceptPrompt(t,c)});save();go('tutor')});$('[data-v83-concept-bank]')?.addEventListener('click',()=>{const t=scopeOf();A.bankSubject=subjectName();A.v83BankScope=t.id;bankIndex=0;S.set('v8-bank-subject',A.bankSubject);S.set('v83-bank-scope',A.v83BankScope);go('bank')});$('[data-v83-concept-source]')?.addEventListener('click',()=>{A.v83PendingSearch=A.v83Concept;A.resourceTab='search';S.set('v8-resource-tab','search');go('resources');setTimeout(()=>$('#v8SourceSearchBtn')?.click(),0)});$$('[data-v83-clear-bank]').forEach(b=>b.onclick=()=>{A.v83BankScope='';S.set('v83-bank-scope','');bankIndex=0;render()});if(state.page==='resources'&&A.resourceTab==='search'&&A.v83PendingSearch){setTimeout(()=>{$('#v8SourceSearchBtn')?.click();A.v83PendingSearch=''},0)}};
})();
