
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const K='rescue6:';
const S={get(k,d){try{const v=localStorage.getItem(K+k);return v===null?d:JSON.parse(v)}catch{return d}},set(k,v){localStorage.setItem(K+k,JSON.stringify(v))},del(k){localStorage.removeItem(K+k)}};
const NAV=[['home','⌂','홈'],['study','▣','학습'],['tutor','AI','과외'],['notes','▤','노트'],['bank','?','문제'],['exam','⏱','시험'],['wrong','!','오답'],['stats','▥','통계'],['resources','◎','자료'],['settings','⚙','설정']];
const SOURCES=[
 {title:'2026년 소방공무원 채용시험 시행계획 변경공고',org:'소방청',url:'https://www.nfa.go.kr/nfa/news/notice/?cntId=734&mode=view&pageIdx=2',note:'구급 경채 시험 과목·문항수·시험시간 확인'},
 {title:'2026년 공통교재 [소방전술3]',org:'중앙소방학교',url:'https://www.nfa.go.kr/nfsa/releaseinformation/archive/materials/?boardId=bbs_0000000000000035&category=&cntId=106811&mode=view&pageIdx=&searchCondition=&searchKeyword=',note:'구급 공식 교재 다운로드 페이지'},
 {title:'소방공무원 임용령',org:'국가법령정보센터',url:'https://www.law.go.kr/법령/소방공무원임용령',note:'필기시험 과목·출제범위 확인'}
];
const Q0=[
 ['f1','소방학개론','시험범위','소방학개론의 법정 상위 범위에 포함되는 것은?',['소방조직','산부인과','소아','기본소생술'],0,'소방학개론의 공식 범위에는 소방조직이 포함됩니다.','소방공무원 임용령'],
 ['f2','소방학개론','시험범위','소방학개론의 법정 상위 범위에 포함되는 것은?',['응급의료개론','재난관리','중독','행동응급'],1,'소방학개론의 공식 범위에는 재난관리가 포함됩니다.','소방공무원 임용령'],
 ['f3','소방학개론','시험범위','소방학개론의 법정 상위 범위에 포함되는 것은?',['기도유지','연소·화재이론','환자평가','소아'],1,'소방학개론의 공식 범위에는 연소·화재이론이 포함됩니다.','소방공무원 임용령'],
 ['f4','소방학개론','시험범위','소방학개론의 법정 상위 범위에 포함되는 것은?',['소화이론','노인','환경응급','산부인과'],0,'소방학개론의 공식 범위에는 소화이론이 포함됩니다.','소방공무원 임용령'],
 ['e1','응급처치학개론','시험범위','응급처치학개론의 법정 상위 범위 조합은?',['전문응급처치학총론 + 전문응급처치학개론','소방조직 + 재난관리','연소이론 + 소화이론','소방관계법규 + 행정법'],0,'응급처치학개론은 전문응급처치학총론과 전문응급처치학개론을 범위로 합니다.','소방공무원 임용령'],
 ['e2','응급처치학개론','시험안내','2026 구급 경채의 응급처치학개론 문항수는?',['20','25','40','65'],2,'2026 구급 경채는 응급처치학개론 40문항입니다.','2026 소방공무원 채용시험 시행계획 변경공고'],
 ['f5','소방학개론','시험안내','2026 구급 경채의 소방학개론 문항수는?',['20','25','40','65'],1,'2026 구급 경채는 소방학개론 25문항입니다.','2026 소방공무원 채용시험 시행계획 변경공고'],
 ['e3','응급처치학개론','시험안내','2026 구급 경채 필기시험 총 시간은?',['50분','60분','65분','75분'],2,'공고상 구급 경채 필기시험은 65분입니다.','2026 소방공무원 채용시험 시행계획 변경공고'],
 ['e4','응급처치학개론','학습법','손글씨 OCR 결과를 학습에 사용하기 전 필요한 것은?',['원본 대조','즉시 기출 등록','자동 A등급','무조건 삭제'],0,'OCR은 오인식 가능성이 있어 원본과 대조해야 합니다.','앱 학습 안전 규칙'],
 ['e5','응급처치학개론','학습법','확실하다고 생각했는데 틀린 문제는 어떻게 관리하는 것이 적절한가?',['삭제','위험오답으로 우선 복습','무시','기출로 승격'],1,'높은 확신의 오답은 잘못 굳어진 개념일 수 있어 우선 복습합니다.','앱 학습 안전 규칙']
].map(x=>({id:x[0],subject:x[1],chapter:x[2],q:x[3],choices:x[4],a:x[5],ex:x[6],source:x[7],grade:x[7].includes('임용령')||x[7].includes('공고')?'A':'D'}));
const state={page:S.get('page','home'),profile:S.get('profile',{examYear:'2027',examDate:'',daily:40,level:'처음 시작'}),notes:S.get('notes',[]),generated:S.get('generated',[]),answers:S.get('answers',{}),conf:S.get('conf',{}),wrongs:S.get('wrongs',[]),examHistory:S.get('examHistory',[]),chat:S.get('chat',[{role:'assistant',text:'안녕하세요. 무료 로컬 AI가 없어도 내 노트 근거검색으로 계속 사용할 수 있습니다.'}]),exam:null,ai:{engine:null,loading:false,status:'무료 AI 미로딩',progress:0,error:''},qa:null};
let examTimer=null;
function save(){['page','profile','notes','generated','answers','conf','wrongs','examHistory','chat'].forEach(k=>S.set(k,state[k]))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function uid(p='id'){return `${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function dday(){if(!state.profile.examDate)return '미설정';const d=Math.ceil((new Date(state.profile.examDate+'T00:00:00')-new Date())/86400000);return Number.isFinite(d)?(d===0?'D-DAY':d>0?`D-${d}`:`D+${-d}`):'미설정'}
function allQ(){return [...Q0,...state.generated]}
function stat(){const qs=allQ();let c=0,t=0;for(const [id,a] of Object.entries(state.answers)){const q=qs.find(q=>q.id===id);if(q){t++;if(a===q.a)c++}}return{tried:t,correct:c,acc:t?Math.round(c/t*100):0,wrong:state.wrongs.filter(w=>!w.resolved).length,risky:state.wrongs.filter(w=>!w.resolved&&w.conf==='sure').length,due:state.wrongs.filter(w=>!w.resolved&&w.due<=Date.now()).length}}
function tag(g){return `<span class="tag ${String(g).toLowerCase()}">${g==='A'?'A 공식':g==='B'?'B 검증':g==='C'?'C AI예상':'D 개인/연습'}</span>`}
function nav(){return `<nav class="nav">${NAV.map(([p,i,l])=>`<button data-nav="${p}" class="${state.page===p?'active':''}"><span class="nav-icon">${i}</span><span class="nav-label">${l}</span></button>`).join('')}</nav>`}
function shell(main,side=''){return `<div class="app"><header class="top"><div class="topin"><span class="logo">🔥</span><span class="brand">구급 합격AI</span><span class="chip good">무료 AI ONLY</span><span class="spacer"></span><span class="chip">${dday()}</span></div></header><div class="layout"><main class="main">${main}</main>${side?`<aside class="side">${side}</aside>`:''}</div>${nav()}</div>`}
function home(){const s=stat();const side=`<div class="card"><b>오늘 추천</b><div class="task"><b>오답 복습</b><div class="tiny muted">${s.due}문제</div></div><div class="task"><b>내 노트</b><div class="tiny muted">${state.notes.length}개</div></div><button class="btn primary block small" data-nav="study">오늘 학습 시작</button></div><div class="card"><b>기능 QA</b><p class="tiny muted">핵심 기능 자동검사 결과</p><div style="font-size:28px;font-weight:950">${state.qa?state.qa.pass+'/'+state.qa.total:'검사 전'}</div><button class="btn block small" data-run-qa>다시 검사</button></div>`;return shell(`<section class="hero"><div class="eyebrow">STABLE CORE V6</div><h1>버튼부터 끝까지<br>실제로 작동하는 합격코치.</h1><p>노트·PDF/TXT·무료 기본정리·AI 과외 fallback·문제·오답·65문항 모의고사·통계·백업까지 한 코어에서 동작합니다.</p><div class="actions"><button class="btn primary" data-nav="study">오늘 학습</button><button class="btn ghost" data-nav="notes">필기/PDF</button></div></section><div class="grid stats"><div class="card stat"><div class="label">정답률</div><div class="value">${s.acc}%</div><div class="tiny muted">${s.tried}문제</div></div><div class="card stat"><div class="label">위험오답</div><div class="value">${s.risky}</div></div><div class="card stat"><div class="label">내 노트</div><div class="value">${state.notes.length}</div></div><div class="card stat"><div class="label">모의고사</div><div class="value">${state.examHistory.length}</div></div></div><div class="section"><h2>합격 루프</h2><span>모든 카드가 실제 화면으로 연결됩니다.</span></div><div class="grid study-grid">${[['📚','학습','오늘 계획·암기카드','study'],['🎓','AI 과외','무료AI 또는 노트 검색','tutor'],['📄','내 노트','사진·PDF·TXT·직접입력','notes'],['📝','문제은행','답안·확신도·해설','bank'],['⏱','모의고사','65문항·65분·25+40','exam'],['❌','오답','재풀이·복습예약','wrong'],['📊','통계','실제 기록만 집계','stats'],['🔎','공식자료','원문 링크·범위','resources']].map(x=>`<button class="card study-card" data-nav="${x[3]}"><div class="icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></button>`).join('')}</div>`,side)}
function phase(){const d=state.profile.examDate?Math.ceil((new Date(state.profile.examDate+'T00:00:00')-new Date())/86400000):999;if(d<=1)return'D-1 마무리';if(d<=7)return'D-7 실전';if(d<=14)return'D-14 압축';if(d<=30)return'D-30 강화';return'기본기'}
function study(){const s=stat();const mins=state.profile.daily||40;return shell(`<div class="pagehead"><div><h1>오늘의 학습</h1><p>${mins}분 · ${phase()}</p></div></div><div class="grid study-grid"><div class="card"><b>1. 복습 예정 오답</b><p class="muted">${s.due}문제</p><button class="btn primary" data-nav="wrong">오답 복습</button></div><div class="card"><b>2. 문제은행</b><p class="muted">총 ${allQ().length}문제</p><button class="btn" data-nav="bank">문제 풀기</button></div><div class="card"><b>3. 내 노트</b><p class="muted">저장된 노트 ${state.notes.length}개</p><button class="btn" data-nav="notes">노트 학습</button></div><div class="card"><b>4. 실전</b><p class="muted">소방학 25 + 응급처치 40</p><button class="btn" data-nav="exam">모의고사</button></div></div><div class="section"><h2>시간별 모드</h2></div><div class="toolbar">${[5,20,60,mins].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<button class="btn small" data-plan="${v}">${v}분 계획</button>`).join('')}</div><div id="planBox" class="card" style="margin-top:10px"><p class="muted">시간을 선택하면 실제 오답과 노트 수를 바탕으로 계획을 만듭니다.</p></div>`)}
function plan(min){const s=stat();const blocks=[];if(s.due)blocks.push(`오답 복습 ${Math.min(min,Math.max(5,Math.round(min*.35)))}분`);if(state.notes.length)blocks.push(`내 노트 회상 ${Math.max(5,Math.round(min*.25))}분`);blocks.push(`문제풀이 ${Math.max(5,Math.round(min*.3))}분`);if(min>=20)blocks.push(`정리/암기 ${Math.max(3,min-blocks.reduce((a,x)=>a+(Number(x.match(/\d+/)?.[0])||0),0))}분`);return blocks.slice(0,4)}
