function notes(){
  const list=state.notes.length?state.notes.slice().reverse().map(n=>`<div class="note"><div class="row"><b>${esc(n.title)}</b><span class="spacer"></span>${tag(n.grade||'D')}</div><div class="tiny muted">${new Date(n.at).toLocaleString('ko-KR')}</div><div style="white-space:pre-wrap;line-height:1.6;margin-top:8px">${esc((n.summary||n.text).slice(0,900))}</div><div class="toolbar"><button class="btn small" data-note-q="${n.id}">문제 만들기</button><button class="btn small" data-note-tutor="${n.id}">과외로 보내기</button><button class="btn small ghost" data-note-del="${n.id}">삭제</button></div></div>`).join(''):`<div class="card empty">아직 노트가 없습니다.</div>`;
  return shell(`<div class="pagehead"><div><h1>내 필기 · PDF</h1><p>기본 기능은 외부 AI 없이 동작합니다.</p></div></div><div class="upload"><div class="big">📷 📄</div><h3>파일 가져오기</h3><p>TXT는 즉시 처리 · PDF/이미지는 무료 브라우저 라이브러리 사용, 실패 시 직접 붙여넣기 가능</p><label class="btn primary">파일 선택<input id="fileInput" type="file" accept="image/*,.pdf,.txt,text/plain,application/pdf"></label><div id="fileStatus" class="tiny muted" style="margin-top:9px"></div></div><div class="section"><h2>직접 입력</h2></div><div class="card"><textarea id="noteText" class="textarea" placeholder="필기·인강 자막·메모를 붙여넣으세요"></textarea><div class="toolbar"><button class="btn primary" id="basicSum">무료 기본정리</button><button class="btn" id="aiSum">무료 AI 정리</button><button class="btn" id="saveNote">원문 저장</button><button class="btn ghost" id="clearNote">비우기</button></div><div id="noteResult"></div></div><div class="section"><h2>저장 노트</h2><span>${state.notes.length}개</span></div>${list}`);
}
function tokenize(t){return String(t).toLowerCase().replace(/[^0-9a-zA-Z가-힣\s]/g,' ').split(/\s+/).filter(x=>x.length>=2)}
function basicSummary(t){const lines=String(t).split(/\n+/).map(x=>x.trim()).filter(x=>x.length>10);const freq={};tokenize(t).forEach(w=>freq[w]=(freq[w]||0)+1);const top=lines.map(l=>({l,s:tokenize(l).reduce((a,w)=>a+(freq[w]||0),0)})).sort((a,b)=>b.s-a.s).slice(0,7).map(x=>x.l);const terms=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0]);return `[핵심]\n${top.map((x,i)=>`${i+1}. ${x}`).join('\n')||'- 문장이 부족합니다.'}\n\n[핵심어]\n${terms.join(' · ')}\n\n[복습]\n- 원문과 대조\n- 숫자·기준은 공식자료 재확인\n- 아래 문제 만들기로 회상 연습`}
function tutor(){return shell(`<div class="pagehead"><div><h1>AI 1:1 과외</h1><p>무료 로컬 AI가 안 되면 내 노트 검색으로 계속 작동합니다.</p></div></div><div class="card"><div class="row"><b>${esc(state.ai.status)}</b><span class="spacer"></span><button class="btn small" id="loadAI">무료 AI 불러오기</button></div>${state.ai.error?`<p class="tiny bad">${esc(state.ai.error)}</p>`:''}</div><div id="chat" class="chat" style="margin-top:10px">${state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(m.text)}</div>`).join('')}</div><div class="chatbox"><input id="chatInput" class="input" placeholder="예: 쇼크 필기 내용을 쉽게 설명해줘"><button class="btn primary" id="sendChat">보내기</button></div>`)}
function retrieve(q){const words=new Set(tokenize(q));return state.notes.map(n=>{const t=(n.title+' '+(n.summary||'')+' '+n.text).toLowerCase();let s=0;words.forEach(w=>{if(t.includes(w))s++});return{n,s}}).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,3).map(x=>x.n)}
function fallbackTutor(q){const hits=retrieve(q);return hits.length?`내 노트 근거검색 결과\n\n${hits.map((n,i)=>`${i+1}. ${n.title}\n${(n.summary||n.text).slice(0,650)}`).join('\n\n')}\n\n※ 원문/공식자료를 최종 확인하세요.`:`무료 로컬 AI를 현재 사용할 수 없습니다.\n내 노트에서도 관련 내용을 찾지 못했습니다.\n노트/PDF에 자료를 넣은 뒤 다시 질문해 주세요.`}
function qcard(q){const ans=state.answers[q.id];const done=ans!==undefined;return `<div class="qcard" data-qcard="${q.id}"><div class="row">${tag(q.grade)}<span class="tag">${esc(q.subject)}</span><span class="tag">${esc(q.chapter)}</span></div><h3>${esc(q.q)}</h3>${q.choices.map((c,i)=>`<button class="choice ${ans===i?'sel':''} ${done&&i===q.a?'correct':''} ${done&&ans===i&&i!==q.a?'wrong':''}" data-answer="${q.id}:${i}">${i+1}. ${esc(c)}</button>`).join('')}<div class="row"><span class="tiny muted">확신도</span><div class="confidence">${[['sure','확실'],['maybe','애매'],['none','모름']].map(([k,l])=>`<button class="${state.conf[q.id]===k?'on':''}" data-conf="${q.id}:${k}">${l}</button>`).join('')}</div></div>${done?`<div class="card" style="padding:12px;margin-top:9px"><b class="${ans===q.a?'good':'bad'}">${ans===q.a?'정답':'오답'} · 정답 ${q.a+1}번</b><p class="muted">${esc(q.ex)}</p><p class="tiny muted">출처: ${esc(q.source)}</p></div>`:''}</div>`}
function bank(){return shell(`<div class="pagehead"><div><h1>문제은행</h1><p>A 공식 / D 개인·연습을 분리해 표시합니다.</p></div></div>${allQ().map(qcard).join('')}`)}
function exam(){if(state.exam)return examRun();const last=state.examHistory.slice(-5).reverse();return shell(`<div class="pagehead"><div><h1>실전 모의고사</h1><p>65문항 · 65분 · 소방학 25 + 응급처치 40</p></div></div><section class="hero"><div class="eyebrow">EXAM MODE</div><h1>25 + 40 / 65분</h1><p>문제은행이 65개보다 적으면 문제를 반복 인스턴스로 구성하되 채점과 과목배분은 정확히 유지합니다.</p><div class="actions"><button class="btn primary" id="startExam">시작</button></div></section>${last.length?`<div class="section"><h2>최근 결과</h2></div>${last.map(r=>`<div class="card" style="margin-top:8px"><div class="row"><b>${r.score}점</b><span class="spacer"></span><span class="tag b">소방 ${r.fireCorrect}/25 · 응급 ${r.emsCorrect}/40</span></div></div>`).join('')}`:''}`)}
function makeExam(){const pool=allQ(),fire=pool.filter(q=>q.subject==='소방학개론'),ems=pool.filter(q=>q.subject==='응급처치학개론');const fill=(arr,n)=>Array.from({length:n},(_,i)=>({...arr[i%arr.length],instance:`${arr[i%arr.length].id}-${i}-${Date.now()}-${Math.random()}`}));if(!fire.length||!ems.length)throw Error('과목 문제 부족');return[...fill(fire,25),...fill(ems,40)]}
function startExam(){try{state.exam={qs:makeExam(),i:0,start:Date.now(),answers:{},conf:{},marked:{}};examTimer=setInterval(()=>{if(state.exam&&state.page==='exam')render()},1000);render()}catch(e){toast(e.message)}}
function examRun(){const e=state.exam,q=e.qs[e.i],left=Math.max(0,3900-Math.floor((Date.now()-e.start)/1000));if(left===0)setTimeout(()=>finishExam(true),0);const mm=String(Math.floor(left/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0'),sel=e.answers[q.instance];return shell(`<div class="exam-head"><b>${e.i+1}/65</b><span class="tiny muted">답변 ${Object.keys(e.answers).length}</span><span class="spacer"></span><span class="timer">${mm}:${ss}</span><button class="btn small" id="finishExam">종료</button></div><div class="qcard"><div class="row"><span class="tag">${esc(q.subject)}</span><span class="tag">${esc(q.chapter)}</span></div><h2>${esc(q.q)}</h2>${q.choices.map((c,i)=>`<button class="choice ${sel===i?'sel':''}" data-exam-a="${i}">${i+1}. ${esc(c)}</button>`).join('')}<div class="row"><span class="tiny muted">확신도</span><div class="confidence">${[['sure','확실'],['maybe','애매'],['none','모름']].map(([k,l])=>`<button class="${e.conf[q.instance]===k?'on':''}" data-exam-c="${k}">${l}</button>`).join('')}</div></div></div><div class="row" style="margin-top:10px"><button class="btn" id="prevExam" ${e.i===0?'disabled':''}>이전</button><button class="btn" id="markExam">${e.marked[q.instance]?'★ 검토':'☆ 검토'}</button><span class="spacer"></span><button class="btn primary" id="nextExam">${e.i===64?'채점':'다음'}</button></div>`)}
function finishExam(auto=false){if(!state.exam)return;const e=state.exam,unanswered=65-Object.keys(e.answers).length;if(!auto&&unanswered&&!confirm(`미응답 ${unanswered}문제입니다. 채점할까요?`))return;let fireCorrect=0,emsCorrect=0;for(const q of e.qs){const a=e.answers[q.instance];if(a===q.a){if(q.subject==='소방학개론')fireCorrect++;else emsCorrect++}else if(a!==undefined){let w=state.wrongs.find(w=>w.qid===q.id&&!w.resolved);if(!w)state.wrongs.push({id:uid('w'),qid:q.id,q,conf:e.conf[q.instance]||'none',due:Date.now(),interval:1,resolved:false})}}const correct=fireCorrect+emsCorrect,r={id:uid('exam'),at:Date.now(),correct,score:Math.round(correct/65*100),fireCorrect,emsCorrect,unanswered};state.examHistory.push(r);state.exam=null;clearInterval(examTimer);save();toast(`${correct}/65 · ${r.score}점`);state.page='stats';render()}
function wrong(){
  const ws=state.wrongs.filter(w=>!w.resolved).sort((a,b)=>a.due-b.due);
  const list=ws.length?ws.map(w=>{const q=allQ().find(q=>q.id===w.qid)||w.q;return `<div class="wrong-item"><div class="row">${w.conf==='sure'?'<span class="tag d">위험오답</span>':''}<span class="tag ${w.due<=Date.now()?'c':'b'}">${w.due<=Date.now()?'복습 예정':new Date(w.due).toLocaleDateString('ko-KR')}</span></div><h3>${esc(q.q)}</h3><p class="muted">${esc(q.ex)}</p><div class="toolbar"><button class="btn small primary" data-retry="${q.id}">다시 풀기</button><button class="btn small" data-relearn="${q.id}">과외로 복습</button><button class="btn small ghost" data-reviewed="${q.id}">복습 완료</button></div></div>`}).join(''):`<div class="card empty">오답이 없습니다.</div>`;
  return shell(`<div class="pagehead"><div><h1>오답 치료</h1><p>재풀이·과외·복습예약</p></div></div>${list}`);
}
function stats(){const s=stat(),last=state.examHistory.slice(-10);return shell(`<div class="pagehead"><div><h1>학습 통계</h1><p>실제 기록만 사용합니다.</p></div></div><div class="grid stats"><div class="card stat"><div class="label">푼 문제</div><div class="value">${s.tried}</div></div><div class="card stat"><div class="label">정답률</div><div class="value">${s.acc}%</div></div><div class="card stat"><div class="label">오답</div><div class="value">${s.wrong}</div></div><div class="card stat"><div class="label">복습예정</div><div class="value">${s.due}</div></div></div><div class="section"><h2>모의고사</h2></div>${last.length?last.map(r=>`<div class="card" style="margin-top:8px"><div class="row"><b>${r.score}점</b><span class="spacer"></span><span class="tiny muted">소방 ${r.fireCorrect}/25 · 응급 ${r.emsCorrect}/40</span></div><div class="progress"><i style="width:${r.score}%"></i></div></div>`).join(''):`<div class="card empty">모의고사 기록이 없습니다.</div>`}`)}
