function save(){['page','profile','notes','generated','answers','conf','wrongs','examHistory','chat'].forEach(k=>S.set(k,state[k]))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function uid(p='id'){return `${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function dday(){if(!state.profile.examDate)return '미설정';const d=Math.ceil((new Date(state.profile.examDate+'T00:00:00')-new Date())/86400000);return Number.isFinite(d)?(d===0?'D-DAY':d>0?`D-${d}`:`D+${-d}`):'미설정'}
function allQ(){return [...Q0,...state.generated]}
function stat(){const qs=allQ();let c=0,t=0;for(const [id,a] of Object.entries(state.answers)){const q=qs.find(q=>q.id===id);if(q){t++;if(a===q.a)c++}}return{tried:t,correct:c,acc:t?Math.round(c/t*100):0,wrong:state.wrongs.filter(w=>!w.resolved).length,risky:state.wrongs.filter(w=>!w.resolved&&w.conf==='sure').length,due:state.wrongs.filter(w=>!w.resolved&&w.due<=Date.now()).length}}
function tag(g){return `<span class="tag ${String(g).toLowerCase()}">${g==='A'?'A 공식':g==='B'?'B 검증':g==='C'?'C AI예상':'D 개인/연습'}</span>`}
function nav(){return `<nav class="nav">${NAV.map(([p,i,l])=>`<button data-nav="${p}" class="${state.page===p?'active':''}"><span class="nav-icon">${i}</span><span class="nav-label">${l}</span></button>`).join('')}</nav>`}
function shell(main,side=''){return `<div class="app"><header class="top"><div class="topin"><span class="logo">🔥</span><span class="brand">구급 합격AI</span><span class="chip good">무료 AI ONLY</span><span class="spacer"></span><span class="chip">${dday()}</span></div></header><div class="layout"><main class="main">${main}</main>${side?`<aside class="side">${side}</aside>`:''}</div>${nav()}</div>`}
function home(){const s=stat();const side=`<div class="card"><b>오늘 추천</b><div class="task"><b>오답 복습</b><div class="tiny muted">${s.due}문제</div></div><div class="task"><b>내 노트</b><div class="tiny muted">${state.notes.length}개</div></div><button class="btn primary block small" data-nav="study">오늘 학습 시작</button></div><div class="card"><b>기능 QA</b><p class="tiny muted">핵심 기능 자동검사 결과</p><div style="font-size:28px;font-weight:950">${state.qa?state.qa.pass+'/'+state.qa.total:'검사 전'}</div><button class="btn block small" data-run-qa>다시 검사</button></div>`;return shell(`<section class="hero"><div class="eyebrow">STABLE CORE V6.1</div><h1>버튼부터 근거까지<br>실제로 이어지는 합격코치.</h1><p>Stable v6의 작동성을 유지하면서 공식 PDF 근거를 새로고침 후에도 보존하고, 과외·문제 생성까지 같은 페이지 근거로 연결합니다.</p><div class="actions"><button class="btn primary" data-nav="study">오늘 학습</button><button class="btn ghost" data-nav="notes">필기/PDF</button></div></section><div class="grid stats"><div class="card stat"><div class="label">정답률</div><div class="value">${s.acc}%</div><div class="tiny muted">${s.tried}문제</div></div><div class="card stat"><div class="label">위험오답</div><div class="value">${s.risky}</div></div><div class="card stat"><div class="label">내 노트</div><div class="value">${state.notes.length}</div></div><div class="card stat"><div class="label">모의고사</div><div class="value">${state.examHistory.length}</div></div></div><div class="section"><h2>합격 루프</h2><span>모든 카드가 실제 화면으로 연결됩니다.</span></div><div class="grid study-grid">${[['📚','학습','오늘 계획·암기카드','study'],['🎓','AI 과외','무료AI 또는 노트 검색','tutor'],['📄','내 노트','사진·PDF·TXT·직접입력','notes'],['📝','문제은행','답안·확신도·해설','bank'],['⏱','모의고사','65문항·65분·25+40','exam'],['❌','오답','재풀이·복습예약','wrong'],['📊','통계','실제 기록만 집계','stats'],['🔎','공식자료','원문 링크·범위','resources']].map(x=>`<button class="card study-card" data-nav="${x[3]}"><div class="icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></button>`).join('')}</div>`,side)}
function phase(){const d=state.profile.examDate?Math.ceil((new Date(state.profile.examDate+'T00:00:00')-new Date())/86400000):999;if(d<=1)return'D-1 마무리';if(d<=7)return'D-7 실전';if(d<=14)return'D-14 압축';if(d<=30)return'D-30 강화';return'기본기'}
function study(){const s=stat();const mins=state.profile.daily||40;return shell(`<div class="pagehead"><div><h1>오늘의 학습</h1><p>${mins}분 · ${phase()}</p></div></div><div class="grid study-grid"><div class="card"><b>1. 복습 예정 오답</b><p class="muted">${s.due}문제</p><button class="btn primary" data-nav="wrong">오답 복습</button></div><div class="card"><b>2. 문제은행</b><p class="muted">총 ${allQ().length}문제</p><button class="btn" data-nav="bank">문제 풀기</button></div><div class="card"><b>3. 내 노트</b><p class="muted">저장된 노트 ${state.notes.length}개</p><button class="btn" data-nav="notes">노트 학습</button></div><div class="card"><b>4. 실전</b><p class="muted">소방학 25 + 응급처치 40</p><button class="btn" data-nav="exam">모의고사</button></div></div><div class="section"><h2>시간별 모드</h2></div><div class="toolbar">${[5,20,60,mins].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<button class="btn small" data-plan="${v}">${v}분 계획</button>`).join('')}</div><div id="planBox" class="card" style="margin-top:10px"><p class="muted">시간을 선택하면 실제 오답과 노트 수를 바탕으로 계획을 만듭니다.</p></div>`)}
function plan(min){const s=stat();const blocks=[];if(s.due)blocks.push(`오답 복습 ${Math.min(min,Math.max(5,Math.round(min*.35)))}분`);if(state.notes.length)blocks.push(`내 노트 회상 ${Math.max(5,Math.round(min*.25))}분`);blocks.push(`문제풀이 ${Math.max(5,Math.round(min*.3))}분`);if(min>=20)blocks.push(`정리/암기 ${Math.max(3,min-blocks.reduce((a,x)=>a+(Number(x.match(/\d+/)?.[0])||0),0))}분`);return blocks.slice(0,4)}
function notes(){
  const list=state.notes.length?state.notes.slice().reverse().map(n=>`<div class="note"><div class="row"><b>${esc(n.title)}</b><span class="spacer"></span>${tag(n.grade||'D')}</div><div class="tiny muted">${new Date(n.at).toLocaleString('ko-KR')}</div><div style="white-space:pre-wrap;line-height:1.6;margin-top:8px">${esc((n.summary||n.text).slice(0,900))}</div><div class="toolbar"><button class="btn small" data-note-q="${n.id}">문제 만들기</button><button class="btn small" data-note-tutor="${n.id}">과외로 보내기</button><button class="btn small ghost" data-note-del="${n.id}">삭제</button></div></div>`).join(''):`<div class="card empty">아직 노트가 없습니다.</div>`;
  return shell(`<div class="pagehead"><div><h1>내 필기 · PDF</h1><p>기본 기능은 외부 AI 없이 동작합니다.</p></div></div><div class="upload"><div class="big">📷 📄</div><h3>파일 가져오기</h3><p>TXT는 즉시 처리 · PDF/이미지는 무료 브라우저 라이브러리 사용, 실패 시 직접 붙여넣기 가능</p><label class="btn primary">파일 선택<input id="fileInput" type="file" accept="image/*,.pdf,.txt,text/plain,application/pdf"></label><div id="fileStatus" class="tiny muted" style="margin-top:9px"></div></div><div class="section"><h2>직접 입력</h2></div><div class="card"><textarea id="noteText" class="textarea" placeholder="필기·인강 자막·메모를 붙여넣으세요"></textarea><div class="toolbar"><button class="btn primary" id="basicSum">무료 기본정리</button><button class="btn" id="aiSum">무료 AI 정리</button><button class="btn" id="saveNote">원문 저장</button><button class="btn ghost" id="clearNote">비우기</button></div><div id="noteResult"></div></div><div class="section"><h2>저장 노트</h2><span>${state.notes.length}개</span></div>${list}`);
}
function tokenize(t){return String(t).toLowerCase().replace(/[^0-9a-zA-Z가-힣\s]/g,' ').split(/\s+/).filter(x=>x.length>=2)}
function basicSummary(t){const lines=String(t).split(/\n+/).map(x=>x.trim()).filter(x=>x.length>10);const freq={};tokenize(t).forEach(w=>freq[w]=(freq[w]||0)+1);const top=lines.map(l=>({l,s:tokenize(l).reduce((a,w)=>a+(freq[w]||0),0)})).sort((a,b)=>b.s-a.s).slice(0,7).map(x=>x.l);const terms=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0]);return `[핵심]\n${top.map((x,i)=>`${i+1}. ${x}`).join('\n')||'- 문장이 부족합니다.'}\n\n[핵심어]\n${terms.join(' · ')}\n\n[복습]\n- 원문과 대조\n- 숫자·기준은 공식자료 재확인\n- 아래 문제 만들기로 회상 연습`}
function tutor(){return shell(`<div class="pagehead"><div><h1>AI 1:1 과외</h1><p>무료 로컬 AI가 안 되면 내 노트 검색으로 계속 작동합니다.</p></div></div><div class="card"><div class="row"><b>${esc(state.ai.status)}</b><span class="spacer"></span><button class="btn small" id="loadAI">무료 AI 불러오기</button></div>${state.ai.error?`<p class="tiny bad">${esc(state.ai.error)}</p>`:''}</div><div id="chat" class="chat" style="margin-top:10px">${state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(m.text)}</div>`).join('')}</div><div class="chatbox"><input id="chatInput" class="input" placeholder="예: 쇼크 필기 내용을 쉽게 설명해줘"><button class="btn primary" id="sendChat">보내기</button></div>`)}
function retrieve(q){const words=new Set(tokenize(q));return state.notes.map(n=>{const t=(n.title+' '+(n.summary||'')+' '+n.text).toLowerCase();let s=0;words.forEach(w=>{if(t.includes(w))s++});return{n,s}}).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,3).map(x=>x.n)}
function fallbackTutor(q){const official=officialFallback(q);if(official)return official;const hits=retrieve(q);return hits.length?`내 노트 근거검색 결과\n\n${hits.map((n,i)=>`${i+1}. ${n.title}\n${(n.summary||n.text).slice(0,650)}`).join('\n\n')}\n\n※ 원문/공식자료를 최종 확인하세요.`:`무료 로컬 AI를 현재 사용할 수 없습니다.\n공식 PDF와 내 노트에서도 관련 내용을 찾지 못했습니다.\n자료 탭에서 공식 PDF를 색인하거나 노트/PDF에 자료를 넣은 뒤 다시 질문해 주세요.`}
function qcard(q){const ans=state.answers[q.id];const done=ans!==undefined;return `<div class="qcard" data-qcard="${q.id}"><div class="row">${tag(q.grade)}<span class="tag">${esc(q.subject)}</span><span class="tag">${esc(q.chapter)}</span></div><h3>${esc(q.q)}</h3>${q.choices.map((c,i)=>`<button class="choice ${ans===i?'sel':''} ${done&&i===q.a?'correct':''} ${done&&ans===i&&i!==q.a?'wrong':''}" data-answer="${q.id}:${i}">${i+1}. ${esc(c)}</button>`).join('')}<div class="row"><span class="tiny muted">확신도</span><div class="confidence">${[['sure','확실'],['maybe','애매'],['none','모름']].map(([k,l])=>`<button class="${state.conf[q.id]===k?'on':''}" data-conf="${q.id}:${k}">${l}</button>`).join('')}</div></div>${done?`<div class="card" style="padding:12px;margin-top:9px"><b class="${ans===q.a?'good':'bad'}">${ans===q.a?'정답':'오답'} · 정답 ${q.a+1}번</b><p class="muted">${esc(q.ex)}</p><p class="tiny muted">출처: ${esc(q.source)}</p></div>`:''}</div>`}
function bank(){return shell(`<div class="pagehead"><div><h1>문제은행</h1><p>A 공식 / D 개인·연습을 분리해 표시합니다.</p></div></div>${allQ().map(qcard).join('')}`)}
function exam(){if(state.exam)return examRun();const last=state.examHistory.slice(-5).reverse();return shell(`<div class="pagehead"><div><h1>실전 모의고사</h1><p>65문항 · 65분 · 소방학 25 + 응급처치 40</p></div></div><section class="hero"><div class="eyebrow">EXAM MODE</div><h1>25 + 40 / 65분</h1><p>문제은행이 65개보다 적으면 문제를 반복 인스턴스로 구성하되 채점과 과목배분은 정확히 유지합니다.</p><div class="actions"><button class="btn primary" id="startExam">시작</button></div></section>${last.length?`<div class="section"><h2>최근 결과</h2></div>${last.map(r=>`<div class="card" style="margin-top:8px"><div class="row"><b>${r.score}점</b><span class="spacer"></span><span class="tag b">소방 ${r.fireCorrect}/25 · 응급 ${r.emsCorrect}/40</span></div></div>`).join('')}`:''}`)}
function makeExam(){const pool=allQ(),fire=pool.filter(q=>q.subject==='소방학개론'),ems=pool.filter(q=>q.subject==='응급처치학개론');const fill=(arr,n)=>Array.from({length:n},(_,i)=>({...arr[i%arr.length],instance:`${arr[i%arr.length].id}-${i}-${Date.now()}-${Math.random()}`}));if(!fire.length||!ems.length)throw Error('과목 문제 부족');return[...fill(fire,25),...fill(ems,40)]}
function startExam(){try{state.exam={qs:makeExam(),i:0,start:Date.now(),answers:{},conf:{},marked:{}};examTimer=setInterval(()=>{if(state.exam&&state.page==='exam')render()},1000);render()}catch(e){toast(e.message)}}
function examRun(){const e=state.exam,q=e.qs[e.i],left=Math.max(0,3900-Math.floor((Date.now()-e.start)/1000));if(left===0)setTimeout(()=>finishExam(true),0);const mm=String(Math.floor(left/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0'),sel=e.answers[q.instance];return shell(`<div class="exam-head"><b>${e.i+1}/65</b><span class="tiny muted">답변 ${Object.keys(e.answers).length}</span><span class="spacer"></span><span class="timer">${mm}:${ss}</span><button class="btn small" id="finishExam">종료</button></div><div class="qcard"><div class="row"><span class="tag">${esc(q.subject)}</span><span class="tag">${esc(q.chapter)}</span></div><h2>${esc(q.q)}</h2>${q.choices.map((c,i)=>`<button class="choice ${sel===i?'sel':''}" data-exam-a="${i}">${i+1}. ${esc(c)}</button>`).join('')}<div class="row"><span class="tiny muted">확신도</span><div class="confidence">${[['sure','확실'],['maybe','애매'],['none','모름']].map(([k,l])=>`<button class="${e.conf[q.instance]===k?'on':''}" data-exam-c="${k}">${l}</button>`).join('')}</div></div></div><div class="row" style="margin-top:10px"><button class="btn" id="prevExam" ${e.i===0?'disabled':''}>이전</button><button class="btn" id="markExam">${e.marked[q.instance]?'★ 검토':'☆ 검토'}</button><span class="spacer"></span><button class="btn primary" id="nextExam">${e.i===64?'채점':'다음'}</button></div>`)}
function finishExam(auto=false){if(!state.exam)return;const e=state.exam,unanswered=65-Object.keys(e.answers).length;if(!auto&&unanswered&&!confirm(`미응답 ${unanswered}문제입니다. 채점할까요?`))return;let fireCorrect=0,emsCorrect=0;for(const q of e.qs){const a=e.answers[q.instance];if(a===q.a){if(q.subject==='소방학개론')fireCorrect++;else emsCorrect++}else if(a!==undefined){let w=state.wrongs.find(w=>w.qid===q.id&&!w.resolved);if(!w)state.wrongs.push({id:uid('w'),qid:q.id,q,conf:e.conf[q.instance]||'none',due:Date.now(),interval:1,resolved:false})}}const correct=fireCorrect+emsCorrect,r={id:uid('exam'),at:Date.now(),correct,score:Math.round(correct/65*100),fireCorrect,emsCorrect,unanswered};state.examHistory.push(r);state.exam=null;clearInterval(examTimer);save();toast(`${correct}/65 · ${r.score}점`);state.page='stats';render()}
function wrong(){
  const ws=state.wrongs.filter(w=>!w.resolved).sort((a,b)=>a.due-b.due);
  const list=ws.length?ws.map(w=>{const q=allQ().find(q=>q.id===w.qid)||w.q;return `<div class="wrong-item"><div class="row">${w.conf==='sure'?'<span class="tag d">위험오답</span>':''}<span class="tag ${w.due<=Date.now()?'c':'b'}">${w.due<=Date.now()?'복습 예정':new Date(w.due).toLocaleDateString('ko-KR')}</span></div><h3>${esc(q.q)}</h3><p class="muted">${esc(q.ex)}</p><div class="toolbar"><button class="btn small primary" data-retry="${q.id}">다시 풀기</button><button class="btn small" data-relearn="${q.id}">과외로 복습</button><button class="btn small ghost" data-reviewed="${q.id}">복습 완료</button></div></div>`}).join(''):`<div class="card empty">오답이 없습니다.</div>`;
  return shell(`<div class="pagehead"><div><h1>오답 치료</h1><p>재풀이·과외·복습예약</p></div></div>${list}`);
}
function stats(){const s=stat(),last=state.examHistory.slice(-10);return shell(`<div class="pagehead"><div><h1>학습 통계</h1><p>실제 기록만 사용합니다.</p></div></div><div class="grid stats"><div class="card stat"><div class="label">푼 문제</div><div class="value">${s.tried}</div></div><div class="card stat"><div class="label">정답률</div><div class="value">${s.acc}%</div></div><div class="card stat"><div class="label">오답</div><div class="value">${s.wrong}</div></div><div class="card stat"><div class="label">복습예정</div><div class="value">${s.due}</div></div></div><div class="section"><h2>모의고사</h2></div>${last.length?last.map(r=>`<div class="card" style="margin-top:8px"><div class="row"><b>${r.score}점</b><span class="spacer"></span><span class="tiny muted">소방 ${r.fireCorrect}/25 · 응급 ${r.emsCorrect}/40</span></div><div class="progress"><i style="width:${r.score}%"></i></div></div>`).join(''):`<div class="card empty">모의고사 기록이 없습니다.</div>`}`)}
function resources(){const status=officialPages.length?`${officialMeta.fileName||'공식 PDF'} · ${officialPages.length}쪽 · ${officialMeta.verified?'B 검증사본':'D 출처확인 필요'} · 새로고침 후 유지`:'미색인';return shell(`<div class="pagehead"><div><h1>공식자료</h1><p>공식 출처 링크와 영구 로컬 PDF 근거색인</p></div></div>${SOURCES.map(s=>`<div class="card" style="margin-top:9px"><div class="row">${tag('A')}<span class="tag">${esc(s.org)}</span></div><h3>${esc(s.title)}</h3><p class="muted">${esc(s.note)}</p><a class="btn ghost source-link" href="${s.url}" target="_blank" rel="noopener">공식 사이트 열기 ↗</a></div>`).join('')}<div class="section"><h2>공식 PDF 로컬 색인</h2><span>IndexedDB에 페이지별 저장</span></div><div class="card"><p class="muted">공식 사이트에서 받은 PDF를 선택하면 브라우저 안에서 페이지별 텍스트를 추출합니다. 서버 업로드 없음. 색인은 새로고침 뒤에도 유지됩니다.</p><div class="toolbar"><label class="btn primary">PDF 선택<input id="officialPdf" type="file" accept="application/pdf,.pdf" hidden></label>${officialPages.length?'<button class="btn ghost" id="officialDelete">색인 삭제</button>':''}</div><div id="officialStatus" class="tiny muted" style="margin-top:9px">${esc(status)}</div><div class="row stack-mobile" style="margin-top:10px"><input id="officialSearch" class="input" placeholder="예: 쇼크, 기도폐쇄, 소아"><button class="btn" id="officialSearchBtn">검색</button></div><div id="officialResults"></div></div>`)}
function settings(){return shell(`<div class="pagehead"><div><h1>설정 · QA</h1><p>목표, 데이터, 기능검사를 관리합니다.</p></div></div><div class="card"><h3>시험 목표</h3><div class="formgrid"><label>목표연도<input id="year" class="input" value="${esc(state.profile.examYear||'2027')}"></label><label>시험일<input id="date" type="date" class="input" value="${esc(state.profile.examDate||'')}"></label><label>하루 공부(분)<input id="daily" type="number" class="input" value="${state.profile.daily||40}"></label><label>수준<select id="level" class="select">${['처음 시작','기초 있음','재도전'].map(v=>`<option ${state.profile.level===v?'selected':''}>${v}</option>`).join('')}</select></label></div><button class="btn primary" id="saveSettings" style="margin-top:10px">저장</button></div><div class="card" style="margin-top:12px"><h3>데이터</h3><div class="toolbar"><button class="btn" id="exportData">백업</button><label class="btn">복원<input id="importData" type="file" accept="application/json,.json" hidden></label><button class="btn ghost" id="eraseData">전체 삭제</button></div></div><div class="card" style="margin-top:12px"><div class="row"><h3>기능 완성도</h3><span class="spacer"></span><button class="btn primary" data-run-qa>100점 검사</button></div><div id="qaBox">${qaHtml()}</div></div>`)}
function qaHtml(){if(!state.qa)return'<p class="muted">검사를 실행하세요.</p>';return `<div style="font-size:40px;font-weight:950" class="${state.qa.pass===state.qa.total?'good':'warn'}">${Math.round(state.qa.pass/state.qa.total*100)} / 100</div>${state.qa.rows.map(r=>`<div class="qa-row"><span class="status">${r.ok?'✓':'✕'}</span><b>${esc(r.name)}</b><small>${esc(r.detail||'')}</small></div>`).join('')}`}
