function save(){['page','profile','notes','generated','answers','conf','wrongs','examHistory','chat'].forEach(k=>S.set(k,state[k]))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function uid(p='id'){return `${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function dday(){if(!state.profile.examDate)return '미설정';const d=Math.ceil((new Date(state.profile.examDate+'T00:00:00')-new Date())/86400000);return Number.isFinite(d)?(d===0?'D-DAY':d>0?`D-${d}`:`D+${-d}`):'미설정'}
function allQ(){return [...Q0,...state.generated]}
function stat(){const qs=allQ();let c=0,t=0;for(const [id,a] of Object.entries(state.answers)){const q=qs.find(q=>q.id===id);if(q){t++;if(a===q.a)c++}}return{tried:t,correct:c,acc:t?Math.round(c/t*100):0,wrong:state.wrongs.filter(w=>!w.resolved).length,risky:state.wrongs.filter(w=>!w.resolved&&w.conf==='sure').length,due:state.wrongs.filter(w=>!w.resolved&&w.due<=Date.now()).length}}
function tag(g){return `<span class="tag ${String(g).toLowerCase()}">${g==='A'?'A 공식':g==='B'?'B 검증':g==='C'?'C AI예상':'D 개인/연습'}</span>`}
const MOBILE_PRIMARY=[['home','⌂','홈'],['study','▣','학습'],['tutor','AI','과외'],['bank','?','문제']];
const MOBILE_MORE=[['notes','▤','노트'],['exam','⏱','시험'],['wrong','!','오답'],['stats','▥','통계'],['resources','◎','자료'],['settings','⚙','설정']];
function nav(){const secondaryActive=MOBILE_MORE.some(([p])=>p===state.page);return `<nav class="nav desktop-nav">${NAV.map(([p,i,l])=>`<button data-nav="${p}" class="${state.page===p?'active':''}"><span class="nav-icon">${i}</span><span class="nav-label">${l}</span></button>`).join('')}</nav><nav class="nav mobile-nav">${MOBILE_PRIMARY.map(([p,i,l])=>`<button data-nav="${p}" class="${state.page===p?'active':''}"><span class="nav-icon">${i}</span><span class="nav-label">${l}</span></button>`).join('')}<button data-more class="${secondaryActive||moreOpen?'active':''}"><span class="nav-icon">•••</span><span class="nav-label">전체</span></button></nav>${moreOpen?`<div class="more-backdrop" data-more-close></div><section class="more-sheet"><div class="more-handle"></div><div class="more-grid">${MOBILE_MORE.map(([p,i,l])=>`<button data-nav="${p}" class="${state.page===p?'active':''}"><span>${i}</span><b>${l}</b></button>`).join('')}</div></section>`:''}`}
function shell(main,side=''){return `<div class="app"><header class="top"><div class="topin"><span class="logo">🔥</span><span class="brand">구급 합격AI</span><span class="spacer"></span><span class="chip">${dday()}</span></div></header><div class="layout"><main class="main"><section class="screen">${main}</section></main>${side?`<aside class="side">${side}</aside>`:''}</div>${nav()}</div>`}
function phase(){const d=state.profile.examDate?Math.ceil((new Date(state.profile.examDate+'T00:00:00')-new Date())/86400000):999;if(d<=1)return'D-1 마무리';if(d<=7)return'D-7 실전';if(d<=14)return'D-14 압축';if(d<=30)return'D-30 강화';return'기본기'}
function home(){const s=stat();const tasks=[['오답 복습',`${s.due}문제`,s.due?'wrong':'study'],['문제풀이',`${allQ().length}문제`,'bank'],['내 노트',`${state.notes.length}개`,'notes']];const side=`<div class="card compact-card"><b>기능 QA</b><div class="qa-score">${state.qa?state.qa.pass+'/'+state.qa.total:'검사 전'}</div><button class="btn small block" data-run-qa>다시 검사</button></div>`;return shell(`<div class="home-compact"><section class="today-card"><div class="row"><span class="eyebrow">${phase()}</span><span class="spacer"></span><span class="chip good">${state.profile.daily||40}분</span></div><h1>${dday()==='미설정'?'오늘 학습':dday()+' · 오늘 학습'}</h1><p>오답 → 문제 → 노트 순서로 가장 필요한 것부터 끝냅니다.</p><button class="btn primary block" data-nav="study">오늘 공부 시작</button></section><div class="mini-stats"><div><span>정답률</span><b>${s.acc}%</b></div><div><span>위험오답</span><b>${s.risky}</b></div><div><span>복습예정</span><b>${s.due}</b></div><div><span>모의고사</span><b>${state.examHistory.length}</b></div></div><section class="task-panel"><div class="panel-title"><b>오늘 할 일</b><span>한 번에 하나씩</span></div>${tasks.map((x,i)=>`<button class="task-row" data-nav="${x[2]}"><span class="task-no">${i+1}</span><span><b>${x[0]}</b><small>${x[1]}</small></span><span class="spacer"></span><span>›</span></button>`).join('')}</section></div>`,side)}
function plan(min){const s=stat(),blocks=[];if(s.due)blocks.push(`오답 ${Math.min(min,Math.max(5,Math.round(min*.35)))}분`);blocks.push(`문제 ${Math.max(5,Math.round(min*.35))}분`);if(state.notes.length)blocks.push(`노트 ${Math.max(5,Math.round(min*.2))}분`);if(min>=20)blocks.push(`정리 ${Math.max(3,Math.round(min*.1))}분`);return blocks.slice(0,4)}
function study(){const s=stat(),mins=state.profile.daily||40;return shell(`<div class="screen-head"><div><h1>오늘의 학습</h1><p>${mins}분 · ${phase()}</p></div></div><div class="time-chips">${[5,20,60,mins].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<button class="chip-btn" data-plan="${v}">${v}분</button>`).join('')}</div><div id="planBox" class="plan-line">${plan(mins).join(' → ')}</div><div class="task-stack"><button class="task-card ${s.due?'urgent':''}" data-nav="wrong"><span>1</span><div><b>오답 복습</b><small>${s.due}문제 · 위험오답 ${s.risky}</small></div><strong>›</strong></button><button class="task-card" data-nav="bank"><span>2</span><div><b>문제풀이</b><small>현재 ${allQ().length}문제</small></div><strong>›</strong></button><button class="task-card" data-nav="notes"><span>3</span><div><b>내 노트 회상</b><small>${state.notes.length}개 노트</small></div><strong>›</strong></button><button class="task-card" data-nav="exam"><span>4</span><div><b>실전 점검</b><small>65문항 · 65분 · 25+40</small></div><strong>›</strong></button></div>`)}
function tokenize(t){return String(t).toLowerCase().replace(/[^0-9a-zA-Z가-힣\s]/g,' ').split(/\s+/).filter(x=>x.length>=2)}
function basicSummary(t){const lines=String(t).split(/\n+/).map(x=>x.trim()).filter(x=>x.length>10),freq={};tokenize(t).forEach(w=>freq[w]=(freq[w]||0)+1);const top=lines.map(l=>({l,s:tokenize(l).reduce((a,w)=>a+(freq[w]||0),0)})).sort((a,b)=>b.s-a.s).slice(0,6).map(x=>x.l),terms=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0]);return `[핵심]\n${top.map((x,i)=>`${i+1}. ${x}`).join('\n')||'- 문장이 부족합니다.'}\n\n[핵심어]\n${terms.join(' · ')}\n\n[복습]\n- 원문과 대조\n- 숫자·기준은 공식자료 재확인`}
function notes(){if(noteView==='saved'){const list=state.notes.length?state.notes.slice().reverse().map(n=>`<div class="note compact-note"><div class="row"><b>${esc(n.title)}</b><span class="spacer"></span>${tag(n.grade||'D')}</div><p>${esc((n.summary||n.text).slice(0,330))}${(n.summary||n.text).length>330?'…':''}</p><div class="toolbar"><button class="btn small" data-note-q="${n.id}">문제</button><button class="btn small" data-note-tutor="${n.id}">과외</button><button class="btn small ghost" data-note-del="${n.id}">삭제</button></div></div>`).join(''):'<div class="empty">저장된 노트가 없습니다.</div>';return shell(`<div class="screen-head"><div><h1>내 노트</h1><p>저장된 노트 ${state.notes.length}개</p></div></div><div class="seg"><button data-note-view="write">입력</button><button class="active" data-note-view="saved">저장노트</button></div><div class="screen-scroll">${list}</div>`)}return shell(`<div class="screen-head"><div><h1>필기 · PDF</h1><p>파일 또는 직접 입력</p></div></div><div class="seg"><button class="active" data-note-view="write">입력</button><button data-note-view="saved">저장노트 ${state.notes.length}</button></div><div class="file-row"><label class="btn small">📎 파일 가져오기<input id="fileInput" type="file" accept="image/*,.pdf,.txt,text/plain,application/pdf" hidden></label><span id="fileStatus" class="tiny muted">TXT/PDF/이미지</span></div><textarea id="noteText" class="textarea compact-textarea" placeholder="필기·인강 자막·메모를 붙여넣으세요"></textarea><div id="noteResult" class="note-result"></div><div class="screen-actions four"><button class="btn primary" id="basicSum">기본정리</button><button class="btn" id="aiSum">무료 AI</button><button class="btn" id="saveNote">저장</button><button class="btn ghost" id="clearNote">비우기</button></div>`)}
function tutor(){return shell(`<div class="screen-head"><div><h1>AI 1:1 과외</h1><p>공식 PDF → 내 노트 → 무료 AI 순서</p></div><button class="btn small" id="loadAI">${state.ai.engine?'AI 준비됨':'무료 AI'}</button></div><div class="ai-strip"><span class="dot ${state.ai.engine?'ok':''}"></span><b>${esc(state.ai.status)}</b>${officialPages.length?`<span class="spacer"></span><small>공식 ${officialPages.length}쪽</small>`:''}</div><div id="chat" class="chat flex-chat">${state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(m.text)}</div>`).join('')}</div><div class="chatbox fixed-input"><input id="chatInput" class="input" placeholder="예: 쇼크를 공식교재 근거로 설명해줘"><button class="btn primary" id="sendChat">보내기</button></div>`)}
function retrieve(q){const words=new Set(tokenize(q));return state.notes.map(n=>{const t=(n.title+' '+(n.summary||'')+' '+n.text).toLowerCase();let s=0;words.forEach(w=>{if(t.includes(w))s++});return{n,s}}).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,3).map(x=>x.n)}
function fallbackTutor(q){const official=officialFallback(q);if(official)return official;const hits=retrieve(q);return hits.length?`내 노트 근거검색 결과\n\n${hits.map((n,i)=>`${i+1}. ${n.title}\n${(n.summary||n.text).slice(0,650)}`).join('\n\n')}\n\n※ 원문/공식자료를 최종 확인하세요.`:`무료 로컬 AI를 현재 사용할 수 없습니다.\n공식 PDF와 내 노트에서도 관련 내용을 찾지 못했습니다.\n자료에서 공식 PDF를 색인하거나 노트를 추가해 주세요.`}
