'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{};const cfg=window.AITUTOR_V9_CONFIG||{};let client=null,user=null,ready=false;
const configured=()=>!!(cfg.supabaseUrl&&cfg.supabaseAnonKey);
async function init(){if(ready)return{client,user};ready=true;if(!configured())return{client:null,user:null};try{const m=await import('https://esm.sh/@supabase/supabase-js@2');client=m.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await client.auth.getUser();user=data?.user||null;if(user){V.Store.switchOwner(user.id)}client.auth.onAuthStateChange(async(_event,session)=>{const next=session?.user||null;if(next&&!user){V.Store.migrateGuestToUser(next.id);user=next;await syncAll().catch(()=>{})}else if(!next&&user){user=null;V.Store.switchOwner(V.Store.guestId)}else if(next){user=next;V.Store.switchOwner(next.id)}window.dispatchEvent(new CustomEvent('aitutor-auth-change',{detail:{user}}))});return{client,user}}catch(e){console.warn('auth init failed',e);client=null;user=null;return{client:null,user:null}}}
async function signUp(email,password){await init();if(!client)throw Error('MEMBER_BACKEND_NOT_CONFIGURED');const {data,error}=await client.auth.signUp({email,password});if(error)throw error;return data}
async function signIn(email,password){await init();if(!client)throw Error('MEMBER_BACKEND_NOT_CONFIGURED');const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;if(data.user){V.Store.migrateGuestToUser(data.user.id);user=data.user;await syncAll()}return data}
async function signOut(){await init();if(client)await client.auth.signOut();user=null;V.Store.switchOwner(V.Store.guestId)}
const rows=(obj,userId)=>Object.entries(obj||{}).map(([concept_id,v])=>({user_id:userId,concept_id,...v}));
async function syncAll(){await init();if(!client||!user)throw Error('NOT_SIGNED_IN');const s=V.Store.state,uid=user.id;const tasks=[];tasks.push(client.from('profiles').upsert({id:uid,exam_year:s.profile.examYear||null,exam_date:s.profile.examDate||null,daily_minutes:s.profile.dailyMinutes||40,level:s.profile.level||'처음 시작',updated_at:new Date().toISOString()}));const progress=Object.entries(s.progress||{}).map(([concept_id,p])=>({user_id:uid,concept_id,mastery:p.mastery||0,attempts:p.attempts||0,correct_count:p.correct||0,dangerous_wrong:p.dangerousWrong||0,last_study:p.lastStudy?new Date(p.lastStudy).toISOString():null,next_review:p.nextReview?new Date(p.nextReview).toISOString():null,updated_at:new Date().toISOString()}));if(progress.length)tasks.push(client.from('user_progress').upsert(progress,{onConflict:'user_id,concept_id'}));const wrong=(s.wrongs||[]).map(w=>({id:w.id,user_id:uid,question_id:w.questionId,concept_id:w.conceptId,confidence:w.confidence,due_at:new Date(w.due||Date.now()).toISOString(),interval_days:w.intervalDays||0,resolved:!!w.resolved,wrong_count:w.wrongCount||1,last_wrong_at:w.lastWrongAt?new Date(w.lastWrongAt).toISOString():null,resolved_at:w.resolvedAt?new Date(w.resolvedAt).toISOString():null}));if(wrong.length)tasks.push(client.from('wrong_answers').upsert(wrong));const notes=(s.notes||[]).map(n=>({id:n.id,user_id:uid,title:n.title||'내 노트',body:n.body||n.text||'',source_type:n.sourceType||'manual',private:true,updated_at:new Date(n.updatedAt||Date.now()).toISOString()}));if(notes.length)tasks.push(client.from('personal_notes').upsert(notes));const sessions=(s.studySessions||[]).map(x=>({id:x.id,user_id:uid,concept_id:x.conceptId||null,started_at:new Date(x.startedAt||Date.now()).toISOString(),ended_at:x.endedAt?new Date(x.endedAt).toISOString():null,duration_sec:x.durationSec||0}));if(sessions.length)tasks.push(client.from('study_sessions').upsert(sessions));const exams=(s.examHistory||[]).map(x=>({id:x.id,user_id:uid,mode:x.mode||'practice',score:x.score||0,fire_correct:x.fireCorrect||0,ems_correct:x.emsCorrect||0,total_answered:x.totalAnswered||0,created_at:new Date(x.at||Date.now()).toISOString()}));if(exams.length)tasks.push(client.from('exam_history').upsert(exams));const settled=await Promise.all(tasks);const bad=settled.find(x=>x.error);if(bad?.error)throw bad.error;V.Store.state.settings.cloudSync=true;V.Store.save();return true}
async function pull(){await init();if(!client||!user)throw Error('NOT_SIGNED_IN');const uid=user.id;const [p,pr,w,n,e]=await Promise.all([client.from('profiles').select('*').eq('id',uid).maybeSingle(),client.from('user_progress').select('*').eq('user_id',uid),client.from('wrong_answers').select('*').eq('user_id',uid),client.from('personal_notes').select('*').eq('user_id',uid),client.from('exam_history').select('*').eq('user_id',uid)]);for(const r of [p,pr,w,n,e])if(r.error)throw r.error;const s=V.Store.state;if(p.data){s.profile={...s.profile,examYear:p.data.exam_year||s.profile.examYear,examDate:p.data.exam_date||'',dailyMinutes:p.data.daily_minutes||40,level:p.data.level||s.profile.level}}for(const r of pr.data||[])s.progress[r.concept_id]={conceptId:r.concept_id,mastery:r.mastery,attempts:r.attempts,correct:r.correct_count,dangerousWrong:r.dangerous_wrong,lastStudy:r.last_study?Date.parse(r.last_study):0,nextReview:r.next_review?Date.parse(r.next_review):0};s.wrongs=(w.data||[]).map(r=>({id:r.id,questionId:r.question_id,conceptId:r.concept_id,confidence:r.confidence,due:Date.parse(r.due_at),intervalDays:r.interval_days,resolved:r.resolved,wrongCount:r.wrong_count,lastWrongAt:r.last_wrong_at?Date.parse(r.last_wrong_at):0,resolvedAt:r.resolved_at?Date.parse(r.resolved_at):0}));s.notes=(n.data||[]).map(r=>({id:r.id,title:r.title,body:r.body,sourceType:r.source_type,private:true,updatedAt:Date.parse(r.updated_at)}));s.examHistory=(e.data||[]).map(r=>({id:r.id,mode:r.mode,score:r.score,fireCorrect:r.fire_correct,emsCorrect:r.ems_correct,totalAnswered:r.total_answered,at:Date.parse(r.created_at)}));V.Store.save();return s}
V.Auth={init,configured,get client(){return client},get user(){return user},get isGuest(){return !user},signUp,signIn,signOut,syncAll,pull,label(){return user?.email||'게스트'},privacy:'personal-data-is-private-by-default'};
init();
})();
