import fs from 'node:fs';
import vm from 'node:vm';

function ok(cond,msg){if(!cond)throw new Error(msg);console.log('PASS',msg)}
globalThis.window={AITUTOR_V9:{}};
for(const file of ['curriculum.js','curriculum-complete-2026.js','curriculum-fire-depth-119.js','master-syllabus-119.js','content-packs.js','questions.js','verified-expansion.js','verified-completion.js','verified-final.js','questions-scope-2026.js','questions-fire-depth-119.js','questions-ems-depth-119.js','questions-ems-restored-verified-119.js','questions-hazmat-depth-119.js','questions-suppression-depth-119.js','questions-governance-depth-119.js','questions-investigation-depth-119.js','questions-facilities-depth-119.js','questions-restored-fire-verified-119.js','question-difficulty.js','question-quality-119.js','content-contract-119.js','depth-enrichment.js','depth-enrichment-2.js','content-rich-2026.js','fire-depth-119.js','fire-visuals-119.js','governance-depth-119.js','governance-visuals-119.js','investigation-depth-119.js','investigation-visuals-119.js','facilities-depth-119.js','facilities-visuals-119.js','hazmat-reference-2026.js','hazmat-depth-119.js','hazmat-visuals-119.js','suppression-depth-119.js','suppression-visuals-119.js','ems-rich-2026.js','ems-depth-119.js','ems-visuals-119.js','exam-gap-enrichment-119.js','questions-calculation-119.js','questions-law-119.js','questions-special-combustible-119.js','questions-ems-gap-practice-119.js','questions-final-gap-119.js','questions-pals-advanced-119.js','questions-fire-terminology-119.js','question-bank-119.js','textbook-grounded-119.js','visual-completion-119.js','calculation-contract-119.js','coverage-map-119.js']){
  const code=fs.readFileSync(new URL(`./${file}`,import.meta.url),'utf8');
  vm.runInThisContext(code,{filename:file});
}
const V=window.AITUTOR_V9;
ok(V.curriculum.totalConcepts===176,'176 current curriculum nodes load successfully');
ok(V.MasterSyllabus119?.groups?.fire?.length===6&&V.MasterSyllabus119?.groups?.ems?.length===10,'119 master syllabus groups fire/EMS into exam-oriented parts');
ok(typeof V.ContentContract119?.audit==='function','119 fail-closed content completion contract is loaded');
ok(typeof V.QuestionQuality119?.isExamStyle==='function','119 exam-style question quality gate is loaded');
const questionAudit=V.QuestionQuality119.audit();
ok(questionAudit.examStyle>0,'exam-style question bank is non-empty');
ok(questionAudit.duplicateTexts.length===0,'exam-style question text duplicates = 0');
ok((V.questions||[]).filter(V.QuestionQuality119.isExamStyle).every(q=>q.choiceExplanations?.length===4),'every exam-style question explains all four options');
ok((V.questions||[]).filter(V.QuestionQuality119.isExamStyle).every(q=>q.difficulty&&q.type&&q.source),'every exam-style question has difficulty, type and source');
const reviewed119=(V.questions||[]).filter(q=>/^119-/.test(q.id||'')&&!q.generatedPractice);
const generated119=(V.questions||[]).filter(q=>q.generatedPractice===true);
ok(reviewed119.length>=29,'119 manually-authored/reviewed exam-question bank remains intact');
ok(reviewed119.every(V.QuestionQuality119.isExamStyle),'every manually-authored 119 question passes the full exam-style quality contract');
ok(V.QuestionFactory119?.generated===generated119.length&&generated119.length>0,'grounded factory reports exactly the generated practice questions it added');
ok(generated119.every(q=>q.grade==='P'&&q.generatedBy==='119-grounded-question-factory-v1'&&V.QuestionQuality119.isExamStyle(q)),'factory questions stay P-grade practice and pass the exam-style contract');
ok(V.CalculationQuestions119?.added===17,'calculation practice bank adds seventeen calculation drills with explicit evidence tiers');
const calculationPractice=(V.questions||[]).filter(q=>/^119-calc-/.test(q.id||''));
ok(calculationPractice.length===17&&calculationPractice.every(q=>q.grade==='P'&&q.type==='계산형'&&V.QuestionQuality119.isExamStyle(q)),'all calculation questions remain practice-only and pass the exam-style quality gate');
ok(calculationPractice.every(q=>!/기출|실제 출제|과거시험/.test(String(q.q||''))),'calculation practice makes no unsupported past-exam claim');
ok(V.LawQuestions119?.added===18,'eighteen current-law practice questions are loaded');
const lawPractice=(V.questions||[]).filter(q=>/^119-law-/.test(q.id||''));
ok(lawPractice.length===18&&lawPractice.every(q=>q.grade==='P'&&V.QuestionQuality119.isExamStyle(q)),'current-law questions stay practice-only and pass the exam-style gate');
ok(lawPractice.every(q=>!/기출|실제 출제|과거시험/.test(String(q.q||''))),'current-law practice makes no unsupported past-exam claim');
ok(V.SpecialCombustibleQuestions119?.added===6,'six current-law special-combustible practice questions are loaded');
const specialCombustiblePractice=(V.questions||[]).filter(q=>/^119-specialcomb-/.test(q.id||''));
ok(specialCombustiblePractice.length===6&&specialCombustiblePractice.every(q=>q.grade==='P'&&V.QuestionQuality119.isExamStyle(q)),'special-combustible questions stay practice-only and pass the exam-style gate');
ok(V.EMSGapPractice119?.added===10,'ten CBRN and pediatric-resuscitation source-backed practice questions are loaded');
const emsGapPractice=(V.questions||[]).filter(q=>/^119-(cbrn|pals)-\d/.test(q.id||''));
ok(emsGapPractice.length===10&&emsGapPractice.every(q=>q.grade==='P'&&V.QuestionQuality119.isExamStyle(q)),'CBRN/PALS questions stay practice-only and pass the exam-style gate');
ok(emsGapPractice.every(q=>!/기출|실제 출제|과거시험/.test(String(q.q||''))),'CBRN/PALS practice makes no unsupported past-exam claim');
ok(V.FinalGapQuestions119?.added===86,'eighty-six building ECG rhythm electrical-therapy disaster CBRN transport cardiovascular shock endocrine sepsis toxicology newborn trauma burn respiratory GI drug infection ACLS and post-ROSC source-backed practice questions are loaded');
const finalGapPractice=(V.questions||[]).filter(q=>/^119-finalgap-/.test(q.id||''));
ok(finalGapPractice.length===86&&finalGapPractice.every(q=>q.grade==='P'&&V.QuestionQuality119.isExamStyle(q)),'final-gap questions remain practice-only and pass the exam-style gate');
ok(finalGapPractice.every(q=>!/기출|실제 출제|과거시험/.test(String(q.q||''))),'final-gap practice makes no unsupported past-exam claim');
const adultAclsExamStandard=finalGapPractice.filter(q=>/^119-finalgap-acls-0[1-4]$/.test(q.id||''));
ok(adultAclsExamStandard.length===4&&adultAclsExamStandard.every(q=>/2020년 한국심폐소생술 가이드라인 140~145쪽/.test(String(q.source||''))),'four adult arrest-algorithm drills are bound to the 2020 KACPR source mandated by the 2026 exam plan');
const postRoscExamStandard=finalGapPractice.filter(q=>/^119-finalgap-acls-0[5-9]$/.test(q.id||''));
ok(postRoscExamStandard.length===5&&postRoscExamStandard.every(q=>/2020년 한국심폐소생술 가이드라인/.test(String(q.source||''))),'five reversible-cause/post-ROSC drills are bound to the 2020 KACPR exam-standard source');
ok(V.questionById['119-finalgap-acls-09']?.difficulty==='low'&&/5H/.test(V.questionById['119-finalgap-acls-09']?.q||''),'E11-C03 retains an explicit low-difficulty exam-standard recall item');
ok((V.contentPacks.authored['E11-C03']?.must||[]).some(x=>/5H/.test(x)&&/저혈량/.test(x))&&(V.contentPacks.authored['E11-C03']?.must||[]).some(x=>/5T/.test(x)&&/긴장성 기흉/.test(x)),'E-ACLS-05 exposes the current 5H/5T reversible-cause checklist');
ok((V.contentPacks.authored['E11-C03']?.must||[]).some(x=>/94~98%/.test(x))&&(V.contentPacks.authored['E11-C03']?.must||[]).some(x=>/SBP.*90mmHg.*MAP.*65mmHg.*SBP.*100mmHg/.test(x))&&(V.contentPacks.authored['E11-C03']?.must||[]).some(x=>/32~36℃/.test(x)&&/24시간/.test(x)),'post-ROSC lesson carries 2020 exam-standard oxygen, blood-pressure and TTM targets');
ok((V.contentPacks.authored['E11-C03']?.officialLinks||[]).some(x=>/kacpr\.org\/download\/2020/.test(x.url||'')),'post-ROSC lesson links the official 2020 KACPR exam-standard source');
ok((V.contentPacks.authored['E11-C03']?.compare||[]).some(x=>x?.[0]==='VF')&&(V.contentPacks.authored['E11-C03']?.compare||[]).some(x=>x?.[0]==='PEA'),'adult arrest lesson explicitly compares shockable and non-shockable rhythms');
ok((V.contentPacks.authored['E11-C03']?.flow||[]).some(x=>/VF\/pVT → 제세동/.test(x))&&(V.contentPacks.authored['E11-C03']?.flow||[]).some(x=>/PEA\/무수축 → CPR\+조기 에피네프린/.test(x)),'adult arrest lesson exposes both 2020 exam-standard algorithm branches');
ok((V.contentPacks.authored['E11-C03']?.officialLinks||[]).some(x=>/kacpr\.org\/download\/2020/.test(x.url||'')),'adult ACLS lesson links the official 2020 KACPR source mandated by the 2026 exam plan');
ok(V.PALSAdvancedQuestions119?.added===7,'seven official-2020 pediatric ALS practice questions are loaded');
const palsAdvanced=(V.questions||[]).filter(q=>/^119-pals-adv-/.test(q.id||''));
ok(palsAdvanced.length===7&&palsAdvanced.every(q=>q.grade==='P'&&V.QuestionQuality119.isExamStyle(q)),'advanced pediatric ALS questions remain practice-only and pass the exam-style gate');
ok(palsAdvanced.every(q=>/2020년 한국심폐소생술 가이드라인/.test(String(q.source||''))),'advanced pediatric ALS practice is bound to the official 2020 KACPR source');
ok(generated119.every(q=>!/(다음 심화 설명을 가장 정확히|교재형 상세 설명|30초 핵심 설명|학습노드)/.test(String(q.q||''))),'generated practice stems use concise exam language without internal/meta wording');

const questionContractRows=V.curriculum.concepts.map(c=>{const qs=V.QuestionQuality119.forConcept(c.id),d={low:0,mid:0,high:0};for(const q of qs)d[q.difficulty]=(d[q.difficulty]||0)+1;return{id:c.id,n:qs.length,...d}});
ok(questionContractRows.every(x=>x.n>=6&&x.low>=1&&x.mid>=2&&x.high>=1),'all 176 concepts satisfy >=6 exam-style questions with low>=1 mid>=2 high>=1');
ok(V.QuestionQuality119.audit().duplicateTexts.length===0,'post-factory exam-style question text duplicates = 0');
ok(new Set(V.curriculum.concepts.map(x=>x.id)).size===176,'unique concept ids');
ok(V.curriculum.concepts.every(x=>x.sourceRanges.length>0),'all concepts have official source ranges');
ok(V.curriculum.fire.length===7,'seven complete fire scopes');
ok(V.curriculum.ems.length===24,'twenty-four EMS scopes');
ok(V.questions.every(q=>q.choices.length===4),'all questions have four choices');
ok(V.questions.every(q=>new Set(q.choices).size===4),'no duplicate choices inside a question');
ok(new Set(V.questions.map(q=>q.id)).size===V.questions.length,'unique question ids');
ok(V.questions.every(q=>Number.isInteger(q.a)&&q.a>=0&&q.a<4),'single valid answer index');
ok(V.questions.every(q=>!/(기출|실제 출제|과거시험)/.test(String(q.q||''))),'no generated question is mislabeled as past exam');
const contentAudit=V.ContentContract119.audit();
ok(contentAudit.total===176&&contentAudit.complete===176&&contentAudit.incomplete===0,'current 176-node curriculum contract is internally complete');
ok(Object.keys(contentAudit.blockers||{}).length===0,'119 content contract has no remaining blockers');
ok(!contentAudit.blockers.questionsEnough&&!contentAudit.blockers.difficultyLow&&!contentAudit.blockers.difficultyMid&&!contentAudit.blockers.difficultyHigh&&!contentAudit.blockers.choiceExplanations,'question-count, difficulty-mix and option-explanation blockers are closed without weakening the contract');
ok(V.TextbookGrounded119?.targetChars===900&&V.curriculum.concepts.every(x=>V.contentPacks.authored[x.id]?.textbookGrounded119===true),'grounded textbook layer closes whatever depth/section/trap/memory shortfalls remain after source-backed enrichment');
ok(!contentAudit.blockers.textbookDepth&&!contentAudit.blockers.structuredSections&&!contentAudit.blockers.examTraps&&!contentAudit.blockers.memoryPoints&&!contentAudit.blockers.comparison,'textbook depth, structure, traps, memory and required comparisons are closed');
ok(V.VisualCompletion119?.targets?.length===27,'visual completion tracks the audited 27 remaining visual concepts');
ok(V.VisualCompletion119.targets.every(id=>{
  const p=V.contentPacks.authored[id];
  return (p?.visuals||[]).length>0&&(p.visuals||[]).some(v=>!!V.Visual119.render(v));
}),'all 27 required visual concepts render at least one real Visual119 diagram');
ok(!contentAudit.blockers.visual,'visual blocker remains closed');
ok(V.CalculationContract119?.requiredIds?.length===10&&V.CalculationContract119.requiredIds.includes('F03-C03')&&V.CalculationContract119.requiredIds.includes('F04-C04')&&V.CalculationContract119.requiredIds.includes('E14-C03'),'calculation contract tracks foam hazardous-material combustion-air and Parkland source-applicable concepts');
ok(V.CalculationContract119.requiredIds.every(id=>(V.contentPacks.authored[id]?.calculations||[]).length>0),'all source-applicable calculation concepts expose a real calculation contract');
ok(V.CalculationContract119.falsePositiveRemoved.every(id=>V.ContentContract119.evaluateConcept(id).needsCalc===false),'former keyword-only calculation false positives are no longer required');
ok(!contentAudit.blockers.calculation,'calculation blocker is closed by source-applicable contracts, not keyword padding');
const fullCoverage=V.CoverageMap119?.audit?.();
ok(!!fullCoverage&&fullCoverage.total>70,'full exam Coverage Map is loaded as a separate truth layer');
ok(fullCoverage.missing===0&&fullCoverage.partial>0&&fullCoverage.implementationPercent<100,'full exam Coverage Map has no fully missing topic but still exposes partial areas before 100-point release');
ok(fullCoverage.rows.find(x=>x.id==='F-SCI-04')?.status==='partial'&&fullCoverage.rows.find(x=>x.id==='F-BLD-02')?.status==='covered','fire-science gas-law work remains partial while building fire compartmentation is source-closed');
ok(fullCoverage.rows.find(x=>x.id==='F-SCI-02')?.status==='covered','Phase A chemical-bond/reaction/redox row closes only after direct official-page evidence');
ok(fullCoverage.rows.find(x=>x.id==='F-SCI-03')?.status==='covered','Phase A state-change sensible/latent-heat row closes only after exact textbook examples and calculations');
ok(['F-SCI-01','F-SCI-04','F-SCI-05','F-SCI-06'].every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='partial'),'remaining unresolved fire-science rows stay fail-closed after F-SCI-02/F-SCI-03 closure');
ok(fullCoverage.rows.find(x=>x.id==='E-MCI-01')?.status==='covered','mass-casualty START triage closes only after exact 2026 textbook RPM thresholds and focused drills');
ok(fullCoverage.rows.find(x=>x.id==='E-ECG-01')?.status==='covered','cardiac-arrest ECG rhythm recognition closes only after four-rhythm source-backed content and waveform study visual');
ok(fullCoverage.rows.find(x=>x.id==='E-ACLS-01')?.status==='covered','adult shockable/non-shockable cardiac-arrest algorithm closes on the 2020 KACPR source mandated by the 2026 exam plan');
ok(['E-ECG-02','E-ACLS-02'].every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='partial'),'non-arrest ECG and full brady/tachy algorithm rows remain fail-closed');
ok(fullCoverage.rows.find(x=>x.id==='E-ACLS-03')?.status==='covered','defibrillation synchronized cardioversion and transcutaneous pacing close only after exam-standard source separation and direct comparison');
ok(fullCoverage.rows.find(x=>x.id==='E-ACLS-05')?.status==='covered','reversible causes and post-ROSC care close only on the 2020 KACPR source mandated by the 2026 exam plan');
const newlyClosedFireRows=['F-COMB-02','F-FIRE-03','F-EXP-01','F-BLD-01','F-BLD-02','F-BLD-03'];
ok(newlyClosedFireRows.every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'six source-backed fire rows are promoted only after explicit evidence closure');
const phaseACombustionRows=['F-COMB-03','F-COMB-04','F-COMB-05','F-COMB-06','F-COMB-07'];
ok(phaseACombustionRows.every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'Phase A ignition-natural-range-MOC rows are promoted only after exact-page source closure');
const fireBehaviorClosureRows=['F-FIRE-04','F-FIRE-05','F-EXP-02','F-BLD-04'];
ok(fireBehaviorClosureRows.every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'fuel/ventilation control smoke dynamics explosion-type and stack-effect rows close only after exact-page source evidence');
ok(['F-FIRE-08','F-EXP-03'].every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'BLEVE pool/jet fire and VCE/explosion-protection rows close only after NFA textbook plus official KOSHA evidence');
ok(fullCoverage.rows.find(x=>x.id==='F-BLD-05')?.status==='covered','kitchen electrical gas and metal special-fire row closes only after direct fire-class and suppression evidence');
ok(fullCoverage.rows.find(x=>x.id==='F-SUP-03')?.status==='covered','foam concentration expansion-ratio and concentrate-quantity calculation row closes only after direct textbook ratio definitions');
ok(V.FireTerminologyQuestions119?.added===55,'fifty-five exact-page fire terminology/science/behavior/calculation/special-fire practice questions are loaded');
const phaseAFireTermIds=['119-fireterm-01','119-fireterm-02','119-fireterm-03','119-fireterm-04','119-fireterm-05','119-fireterm-06','119-fireterm-07','119-fireterm-08','119-fireterm-09','119-fireterm-10','119-fireterm-11','119-fireterm-12','119-fireterm-13','119-fireterm-14','119-fireterm-15','119-fireterm-16','119-fireterm-17','119-fireterm-18','119-fireterm-19','119-fireterm-20','119-fireterm-21','119-fireterm-22','119-fireterm-23','119-fireterm-24','119-fireterm-25','119-fireterm-26','119-fireterm-27','119-fireterm-28','119-fireterm-29','119-fireterm-30','119-fireterm-31','119-fireterm-32','119-fireterm-33','119-fireterm-34','119-fireterm-35','119-fireterm-36','119-fireterm-37','119-fireterm-38','119-fireterm-39','119-fireterm-40','119-fireterm-41','119-fireterm-42','119-fireterm-43','119-fireterm-44','119-fireterm-45','119-fireterm-46','119-fireterm-47','119-fireterm-48','119-fireterm-49','119-fireterm-50','119-fireterm-51','119-fireterm-52','119-fireterm-53','119-fireterm-54','119-fireterm-55'];
ok(phaseAFireTermIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'Phase A ignition-range-MOC focused questions remain P-grade exam-style practice');
ok(['119-fireterm-01','119-fireterm-02','119-fireterm-07','119-fireterm-08'].every(id=>/화재2\) 303~306쪽/.test(V.questionById[id]?.source||'')),'flash-fire-autoignition closure is bound to exact textbook pages 303~306');
ok(['119-fireterm-03','119-fireterm-04'].every(id=>/화재2\) 306~307쪽/.test(V.questionById[id]?.source||'')),'flammability-range closure is bound to exact textbook pages 306~307');
ok(['119-fireterm-05','119-fireterm-06'].every(id=>/화재2\) 226쪽/.test(V.questionById[id]?.source||'')),'MOC closure is bound to exact textbook page 226');
ok(/화재2\) 295쪽/.test(V.questionById['119-fireterm-09']?.source||''),'minimum-ignition-energy closure is bound to exact textbook page 295');
ok(['119-fireterm-10','119-fireterm-11'].every(id=>/화재2\) 316쪽/.test(V.questionById[id]?.source||'')),'spontaneous-ignition closure is bound to exact textbook page 316');
const ignitionPack=V.contentPacks.authored['F03-C03'],mocPack=V.contentPacks.authored['F04-C06'];
ok((ignitionPack?.must||[]).some(x=>/최소점화에너지/.test(x))&&(ignitionPack?.must||[]).some(x=>/내부 발열.*축열.*발화점/.test(x)),'natural-ignition closure contains minimum ignition energy and the heat-accumulation-to-ignition sequence');
ok(['분해열','산화열','발효열','흡착열','중합열'].every(k=>(ignitionPack?.must||[]).some(x=>String(x).includes(k))),'natural-ignition closure keeps all five textbook heat-source categories');
ok((ignitionPack?.traps||[]).some(x=>/최소점화에너지와 발화점/.test(x))&&(ignitionPack?.compare||[]).some(x=>x?.[0]==='자연발화'),'natural-ignition closure separates energy, temperature and spontaneous ignition concepts');
ok(fullCoverage.rows.find(x=>x.id==='F-COMB-07')?.status==='covered','combustion-products and smoke-toxicity row closes only after direct HCN combustion-product evidence is found');
ok(/화재2\) 332쪽/.test(V.questionById['119-fireterm-12']?.source||''),'HCN incomplete-combustion question is bound to exact textbook page 332');
ok(/화재2\) 334쪽/.test(V.questionById['119-fireterm-13']?.source||''),'toxic-gas source pairing question is bound to exact textbook page 334');
ok(/화재2\) 330·334쪽/.test(V.questionById['119-fireterm-14']?.source||''),'smoke-toxicity question is bound to exact textbook pages 330 and 334');
ok(/화재2\) 299쪽/.test(V.questionById['119-fireterm-15']?.source||''),'complete-vs-incomplete combustion question is bound to exact textbook page 299');
ok(/화재2\) 191쪽/.test(V.questionById['119-fireterm-16']?.source||''),'chemical-bond practice is bound to exact textbook page 191');
ok(/화재1\) 16쪽/.test(V.questionById['119-fireterm-17']?.source||''),'redox practice is bound to exact textbook page 16');
ok(/화재2\) 299쪽/.test(V.questionById['119-fireterm-18']?.source||''),'chemical-equation practice is bound to exact textbook page 299');
ok(/화재1\) 12·40쪽/.test(V.questionById['119-fireterm-19']?.source||''),'oxidation/combustion comparison is bound to exact textbook pages 12 and 40');
ok(/화재2\) 309쪽/.test(V.questionById['119-fireterm-20']?.source||''),'latent-heat definition practice is bound to exact textbook page 309');
ok(/화재2\) 190·309·345쪽/.test(V.questionById['119-fireterm-21']?.source||''),'sensible-vs-latent comparison is bound to exact textbook pages 190, 309 and direct sensible-heat page 345');
ok(['119-fireterm-22','119-fireterm-23'].every(id=>/화재2\) 190쪽/.test(V.questionById[id]?.source||'')),'heat calculation drills are bound to the textbook worked values on page 190');
ok(['119-fireterm-24','119-fireterm-25'].every(id=>/화재1\) 18/.test(V.questionById[id]?.source||''))&&/화재1\) 33쪽/.test(V.questionById['119-fireterm-26']?.source||''),'fuel/ventilation-control and Flow Path drills are bound to exact fire1 pages');
ok(['119-fireterm-28','119-fireterm-29','119-fireterm-30','119-fireterm-31'].every(id=>/2026 소방전술1/.test(V.questionById[id]?.source||'')),'plume ceiling-jet smoke-layer visibility drills are exact-source practice');
ok(['119-fireterm-32','119-fireterm-33','119-fireterm-34','119-fireterm-35'].every(id=>/화재2\) 34[5-8]쪽/.test(V.questionById[id]?.source||'')),'gas decomposition and dust explosion drills are bound to exact pages 345-348');
ok(['119-fireterm-36','119-fireterm-37','119-fireterm-38','119-fireterm-39'].every(id=>/2026 소방전술1/.test(V.questionById[id]?.source||'')),'stack-effect neutral-plane and evacuation drills remain exact-source practice');
ok((V.contentPacks.authored['F03-C05']?.compare||[]).some(x=>x?.[0]==='연료지배')&&(V.contentPacks.authored['F03-C05']?.compare||[]).some(x=>x?.[0]==='환기지배'),'F-FIRE-04 lesson directly distinguishes fuel- and ventilation-controlled fire');
ok((V.contentPacks.authored['F03-C07']?.compare||[]).some(x=>x?.[0]==='플룸')&&(V.contentPacks.authored['F03-C07']?.compare||[]).some(x=>x?.[0]==='천장제트')&&(V.contentPacks.authored['F03-C07']?.must||[]).some(x=>/시야/.test(x)),'F-FIRE-05 lesson connects plume ceiling jet smoke layer and visibility');
ok((V.contentPacks.authored['F03-C08']?.compare||[]).some(x=>x?.[0]==='가스폭발')&&(V.contentPacks.authored['F03-C08']?.compare||[]).some(x=>x?.[0]==='분해폭발')&&(V.contentPacks.authored['F03-C08']?.compare||[]).some(x=>x?.[0]==='분진폭발'),'F-EXP-02 lesson directly compares all three required explosion mechanisms');
ok((V.contentPacks.authored['F03-C07']?.must||[]).some(x=>/연돌효과/.test(x))&&(V.contentPacks.authored['F03-C07']?.must||[]).some(x=>/피난계획/.test(x)),'F-BLD-04 lesson binds stack effect smoke movement and evacuation planning');
ok(['119-fireterm-40','119-fireterm-41','119-fireterm-42','119-fireterm-43'].every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four kitchen/electrical/gas/metal-fire drills remain P-grade exam-style practice');
const specialFireIds=['119-fireterm-48','119-fireterm-49','119-fireterm-50','119-fireterm-51','119-fireterm-52','119-fireterm-53','119-fireterm-54','119-fireterm-55'];
ok(specialFireIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'eight BLEVE pool jet VCE and explosion-protection drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['F03-C15']?.compare||[]).some(x=>x?.[0]==='BLEVE')&&(V.contentPacks.authored['F03-C15']?.compare||[]).some(x=>x?.[0]==='Pool Fire')&&(V.contentPacks.authored['F03-C15']?.compare||[]).some(x=>x?.[0]==='Jet Fire'),'special-fire lesson directly compares BLEVE pool fire and jet fire');
ok((V.contentPacks.authored['F03-C16']?.officialLinks||[]).some(x=>/kosha\.or\.kr/.test(x.url||'')),'pool/jet-fire layer is bound to an official KOSHA source instead of unsupported textbook attribution');
ok((V.contentPacks.authored['F03-C08']?.must||[]).some(x=>/환기/.test(x))&&(V.contentPacks.authored['F03-C08']?.must||[]).some(x=>/불활성/.test(x))&&(V.contentPacks.authored['F03-C08']?.must||[]).some(x=>/안전밸브.*파열판/.test(x)),'VCE/explosion-protection lesson covers concentration oxygen ignition and overpressure controls');
ok(['119-fireterm-44','119-fireterm-45','119-fireterm-46','119-fireterm-47'].every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four foam ratio/calculation drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['F03-C01']?.compare||[]).some(x=>/식용유/.test(String(x?.[0])))&&(V.contentPacks.authored['F03-C01']?.compare||[]).some(x=>/금속화재/.test(String(x?.[0]))),'special-fire lesson compares kitchen and metal fire classes');
ok((V.contentPacks.authored['F04-C04']?.calculations||[]).some(x=>/원액량 = 포수용액량/.test(x?.formula||''))&&(V.contentPacks.authored['F04-C04']?.calculations||[]).some(x=>/팽창비 = 생성된 포 체적/.test(x?.formula||'')),'foam lesson exposes transparent concentration and expansion calculations');
ok((V.contentPacks.authored['F04-C04']?.detail||[]).some(x=>/6%.*원액 6%.*물 94%/.test(x)),'foam concentration arithmetic is anchored to the textbook 6-percent composition definition');
ok((ignitionPack?.must||[]).some(x=>/극성 공유결합/.test(x))&&(ignitionPack?.detail||[]).some(x=>/산화.*반응|산화.*환원/.test(x)),'F-SCI-02 content exposes chemical-bond and oxidation/reduction evidence in the student lesson');
const heatPack=V.contentPacks.authored['F03-C02'];
ok((heatPack?.compare||[]).some(x=>x?.[0]==='감열')&&(heatPack?.compare||[]).some(x=>x?.[0]==='잠열'),'F-SCI-03 lesson directly compares sensible and latent heat');
ok((heatPack?.detail||[]).some(x=>/현열\(Sensible Heat\)|현열/.test(x)),'F-SCI-03 sensible-heat wording is directly tied to textbook page 345 instead of inference-only wording');
ok((heatPack?.calculations||[]).some(x=>/Q = m × c × ΔT/.test(x?.formula||''))&&(heatPack?.calculations||[]).some(x=>/Q = m × L/.test(x?.formula||'')),'F-SCI-03 lesson exposes separate temperature-change and phase-change calculation contracts');
ok((heatPack?.must||[]).some(x=>/79\.7cal\/g/.test(x))&&(heatPack?.must||[]).some(x=>/539\.6cal\/g/.test(x)),'F-SCI-03 keeps the exact textbook water latent-heat values');
const smokePack=V.contentPacks.authored['F03-C07'];
ok((smokePack?.must||[]).some(x=>/HCN/.test(x))&&(smokePack?.must||[]).some(x=>/완전연소.*CO₂.*불완전연소.*CO/.test(x)),'combustion-products closure covers HCN plus CO2/CO combustion-condition differences');
ok((smokePack?.compare||[]).some(x=>/사이안화수소/.test(String(x?.[0])))&&(smokePack?.traps||[]).some(x=>/모든 화재.*같은 종류/.test(x)),'smoke-toxicity closure compares source-specific toxic gases without pretending every fire produces the same mixture');
ok(['인화점','연소점','발화점','연소하한','연소상한'].every(k=>(ignitionPack?.compare||[]).some(x=>String(x?.[0]||'').includes(k))),'ignition-temperature and flammability-range content keeps the required direct comparison');
ok((mocPack?.must||[]).some(x=>/MOC/.test(x))&&(mocPack?.traps||[]).some(x=>/호흡|안전 산소농도/.test(x)),'MOC content keeps the combustion-limit definition and human-oxygen trap separated');
const combustionCalc=V.contentPacks.authored['F03-C03']?.calculations||[];
ok(['이론공기량','이론산소량','과잉공기량','공기비'].every(k=>combustionCalc.some(x=>String(x.title||'').includes(k))),'combustion-air lesson contains all four calculation contracts');
ok(['119-calc-comb-01','119-calc-comb-02','119-calc-comb-03','119-calc-comb-04'].every(id=>!!V.questionById[id]),'combustion-air closure has four source-backed calculation drills');
const neutralPack=V.contentPacks.authored['F03-C07'];
ok((neutralPack?.must||[]).some(x=>/중성대 위/.test(x))&&(neutralPack?.must||[]).some(x=>/중성대 아래/.test(x))&&(neutralPack?.detail||[]).some(x=>/개구부/.test(x)),'middle-plane closure covers pressure/opening-driven inflow and exhaust');
const explosionPack=V.contentPacks.authored['F03-C08'];
ok((explosionPack?.compare||[]).some(x=>x?.[0]==='폭연')&&(explosionPack?.compare||[]).some(x=>x?.[0]==='폭굉'),'deflagration/detonation closure contains an explicit comparison');
const buildingPack=V.contentPacks.authored['F03-C05'];
ok((buildingPack?.compare||[]).some(x=>/목조건축물/.test(String(x?.[0])))&&(buildingPack?.compare||[]).some(x=>/내화/.test(String(x?.[0]))),'wood-vs-fire-resistant building closure contains a direct comparison');
ok(['119-finalgap-bld-01','119-finalgap-bld-02','119-finalgap-bld-03'].every(id=>!!V.questionById[id]),'building-fire closure has three focused exam-style drills');
const passivePack=V.contentPacks.authored['F07-C01'];
ok((passivePack?.compare||[]).some(x=>x?.[0]==='방화구획')&&(passivePack?.compare||[]).some(x=>x?.[0]==='방화벽'),'passive-fire closure distinguishes compartmentation and fire walls');
ok(['내화구조','불연재료','준불연재료','난연재료'].every(k=>(passivePack?.compare||[]).some(x=>x?.[0]===k)),'passive-fire closure distinguishes structural fire resistance from material combustibility classes');
ok((passivePack?.officialLinks||[]).length>=3,'passive-fire closure keeps current Building Act source links');
const hazmatIds=['F05-C02','F05-C03','F05-C04','F05-C05','F05-C06','F05-C07'];
ok(hazmatIds.every(id=>{const p=V.contentPacks.authored[id];const body=(p?.deepSections||[]).map(x=>String(x.title||'')+' '+String(x.body||'')).join(' ');return /저장·취급/.test(body)&&/소화방법/.test(body)&&(p?.traps||[]).length>=1;}),'hazmat closure requires storage/handling, extinguishing and trap coverage for all six hazard classes');
ok(['119-h1-2','119-h2-2','119-h3-2','119-h4-2','119-h4-3','119-h5-2','119-h6-2'].every(id=>!!V.questionById[id]),'hazmat handling closure has focused exam-style drills including class-specific exceptions');
const detection=V.contentPacks.authored['F07-C11'],alarms=V.contentPacks.authored['F07-C12'];
ok((detection?.compare||[]).some(x=>x?.[0]==='열감지')&&(detection?.compare||[]).some(x=>x?.[0]==='연기감지')&&(detection?.deepSections||[]).some(x=>/감지기가.*수신기.*경보/.test(String(x.body||''))),'detection closure covers detector types and detector-to-receiver-to-alarm flow');
ok((alarms?.compare||[]).some(x=>/비상방송/.test(String(x?.[0])))&&(alarms?.compare||[]).some(x=>/자동화재속보/.test(String(x?.[0]))),'alarm closure distinguishes occupant broadcast and automatic external reporting');
ok(['119-fac-11a','119-fac-11b','119-fac-12a'].every(id=>!!V.questionById[id]),'detection/alarm closure has sequence and comparison drills');
const evacuation=V.contentPacks.authored['F07-C13'],water=V.contentPacks.authored['F07-C14'],activity=V.contentPacks.authored['F07-C15'];
ok((evacuation?.must||[]).some(x=>/유도등/.test(x))&&(evacuation?.must||[]).some(x=>/비상조명/.test(x))&&(evacuation?.must||[]).some(x=>/피난기구/.test(x)),'facility support closure covers evacuation guidance, lighting and escape equipment');
ok((water?.compare||[]).some(x=>x?.[0]==='소화용수설비')&&(activity?.compare||[]).some(x=>x?.[0]==='연결송수관')&&(activity?.compare||[]).some(x=>x?.[0]==='제연')&&(activity?.compare||[]).some(x=>x?.[0]==='무선통신보조'),'facility support closure distinguishes water supply, standpipe, smoke control and radio assist');
ok(['119-fac-13a','119-fac-14a','119-fac-15a','119-fac-15b'].every(id=>!!V.questionById[id]),'evacuation/water/firefighter-support closure has focused comparison and purpose drills');
ok(['F-HAZ-03','F-FAC-04','F-FAC-05'].every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'hazmat handling and both facility-operation rows are promoted only after evidence checks pass');
ok(fullCoverage.calcMissing.length===0&&fullCoverage.rows.find(x=>x.id==='E-CALC-01')?.status==='partial'&&fullCoverage.rows.find(x=>x.id==='E-CALC-02')?.status==='partial'&&fullCoverage.rows.find(x=>x.id==='E-BURN-02')?.status==='covered','no calculation topic is blank: oxygen/drip remain partial while Parkland is source-backed covered');

ok(contentAudit.complete===176&&contentAudit.incomplete===0&&contentAudit.averageScore===100,'current 176-node content contract reaches 176/176 without claiming full exam coverage');
const mock=V.examReadiness();
const restoredVerifiedIds=['119-ver-f05-c04-a','119-ver-f05-c05-a','119-ver-f06-c01-a','119-ver-f06-c03-a','119-ver-f07-c05-a','119-ver-f07-c11-a'];
const restoredVerified=restoredVerifiedIds.map(id=>V.questionById[id]);
ok(restoredVerified.every(q=>q&&q.grade==='B'&&q.pageVerified===true&&q.reviewStatus==='manual-reviewed'&&V.QuestionQuality119.isExamStyle(q)),'six restored-scope questions are manually reviewed B-grade page-verified exam-style questions');
ok(restoredVerified.every(q=>/PDF\s+[0-9]+(?:[·~][0-9]+)?쪽/.test(q.source)&&!/기출|실제 출제|과거시험/.test(q.q)),'restored-scope B questions cite exact PDF pages without past-exam claims');
ok(new Set(restoredVerified.map(q=>q.scopeId)).size===3&&['F05','F06','F07'].every(s=>restoredVerified.some(q=>q.scopeId===s)),'page-verified B questions cover F05 F06 F07');
ok(mock.ready===(mock.fire>=25&&mock.ems>=40&&mock.scopeComplete),'real mock gate remains count + all-subject scope fail-closed contract');
ok(Array.isArray(mock.missingFireScopes)&&Array.isArray(mock.missingEmsScopes),'real mock readiness exposes both fire and EMS uncovered verified scopes');
ok(mock.scopeComplete===(mock.missingFireScopes.length===0&&mock.missingEmsScopes.length===0),'real mock scopeComplete requires both fire and EMS coverage');
ok(mock.ready||mock.missingFireScopes.length>0||mock.missingEmsScopes.length>0||mock.fireNeed>0||mock.emsNeed>0,'real mock never reports false readiness when verified evidence is incomplete');
ok(mock.ready===true&&mock.missingFireScopes.length===0&&mock.missingEmsScopes.length===0,'page-verified EMS gap repair closes all verified-scope blockers for the 65-question real mock');
ok(V.scopePractice2026?.questions===27&&V.questions.filter(q=>q.grade==='P').length>=27,'27 practice-only restored-scope questions remain P-grade and separate from real-exam credit');
ok(V.QuestionDifficulty?.levels?.high&&V.QuestionDifficulty?.profiles?.hard,'question difficulty is independent from evidence grade');
ok(V.Hazmat2026?.grade2?.items?.length===7,'official grade-2 hazardous-material item table is loaded');
ok(V.Hazmat2026?.multiple([{quantity:100,designated:100},{quantity:250,designated:500}])===1.5,'hazardous-material designated-quantity multiple calculator works');
const coverage=V.contentPacks.coverage();
const missing=V.curriculum.concepts.filter(c=>V.contentPacks.authored[c.id]?.status!=='verified').map(c=>c.id);
const scopeVerified=V.curriculum.concepts.filter(c=>V.contentPacks.authored[c.id]?.status==='scope-verified').map(c=>c.id);
const extra=Object.keys(V.contentPacks.authored).filter(id=>!V.curriculum.byId[id]);
console.log('VERIFIED_COVERAGE',coverage);
console.log('MISSING_VERIFIED_CONCEPTS',missing);
console.log('EXTRA_AUTHORED_CONCEPTS',extra);
ok(coverage.total===176,'content coverage denominator is 176');
const exactAnchorBatch={'F07-C05':284,'F07-C16':288,'F07-C17':288,'F07-C18':284,'F07-C19':284,'F07-C20':302,'F07-C21':287};
ok(Object.entries(exactAnchorBatch).every(([id,page])=>{
  const r=V.curriculum.byId[id]?.sourceRanges?.[0],p=V.contentPacks.authored[id];
  return Number(r?.from)===page&&Number(r?.to)===page&&p?.status==='verified'&&p?.sourcePrecision==='exact-pdf-page-anchor';
}),'seven sprinkler concepts are exact-page verified from 2026 prevention1 PDF');
const exactFirePhenomenaBatch={'F03-C09':37,'F03-C10':40,'F03-C11':453,'F03-C12':319,'F03-C13':320,'F03-C14':319,'F03-C15':326,'F03-C16':453};
ok(Object.entries(exactFirePhenomenaBatch).every(([id,page])=>{
  const r=V.curriculum.byId[id]?.sourceRanges?.[0],p=V.contentPacks.authored[id];
  return Number(r?.from)===page&&Number(r?.to)===page&&p?.status==='verified'&&p?.sourcePrecision==='exact-pdf-page-anchor';
}),'eight fire-phenomena concepts are exact-page verified from 2026 fire1 PDF');
const exactHazmatBatch={'F05-C02':385,'F05-C03':407,'F05-C04':428,'F05-C05':449,'F05-C06':496,'F05-C07':523};
ok(Object.entries(exactHazmatBatch).every(([id,page])=>{
  const r=V.curriculum.byId[id]?.sourceRanges?.[0],p=V.contentPacks.authored[id];
  return r?.doc==='prevention2'&&Number(r?.from)===page&&Number(r?.to)===page&&p?.status==='verified'&&p?.sourcePrecision==='exact-pdf-page-anchor';
}),'hazardous-material classes 1-6 are exact-page verified from 2026 prevention2 PDF');
const haz01=V.curriculum.byId['F05-C01']?.sourceRanges||[],haz08=V.curriculum.byId['F05-C08']?.sourceRanges||[];
ok(haz01.length===2&&haz01[0]?.doc==='prevention2'&&Number(haz01[0]?.from)===345&&Number(haz01[1]?.from)===385&&V.contentPacks.authored['F05-C01']?.status==='verified','hazardous-material definition/classification keeps both exact official pages');
ok(haz08.length===2&&haz08[0]?.doc==='fire1'&&Number(haz08[0]?.from)===319&&haz08[1]?.doc==='prevention2'&&Number(haz08[1]?.from)===536&&V.contentPacks.authored['F05-C08']?.status==='verified','hazardous-material fire principles keep exact special-phenomenon and response pages');
const inv=Object.fromEntries(['F06-C01','F06-C02','F06-C03','F06-C04'].map(id=>[id,V.curriculum.byId[id]?.sourceRanges||[]]));
ok(inv['F06-C01']?.length===2&&inv['F06-C01'].every(r=>r.doc==='fire2')&&Number(inv['F06-C01'][0].from)===269&&Number(inv['F06-C01'][1].from)===270&&V.contentPacks.authored['F06-C01']?.status==='verified','fire-investigation purpose keeps exact fire2 pages 269 and 270');
ok(inv['F06-C02']?.length===2&&inv['F06-C02'].every(r=>r.doc==='fire2')&&Number(inv['F06-C02'][0].from)===276&&Number(inv['F06-C02'][1].from)===282&&V.contentPacks.authored['F06-C02']?.status==='verified','fire-investigation preservation/procedure keeps exact fire2 pages 276 and 282');
ok(inv['F06-C03']?.length===2&&inv['F06-C03'].every(r=>r.doc==='fire2')&&Number(inv['F06-C03'][0].from)===282&&Number(inv['F06-C03'][1].from)===297&&V.contentPacks.authored['F06-C03']?.status==='verified','fire-investigation origin/cause keeps exact fire2 pages 282 and 297');
ok(inv['F06-C04']?.length===2&&inv['F06-C04'].every(r=>r.doc==='fire2')&&Number(inv['F06-C04'][0].from)===287&&Number(inv['F06-C04'][1].from)===294&&V.contentPacks.authored['F06-C04']?.status==='verified','fire-damage investigation/records keep exact fire2 pages 287 and 294');
const facilitySingles={'F07-C01':17,'F07-C02':207,'F07-C03':247,'F07-C04':273,'F07-C07':328,'F07-C08':347,'F07-C09':432,'F07-C10':415,'F07-C11':23,'F07-C12':18,'F07-C13':465,'F07-C14':201};
ok(Object.entries(facilitySingles).every(([id,page])=>{
  const rows=V.curriculum.byId[id]?.sourceRanges||[],p=V.contentPacks.authored[id];
  return rows.length===1&&rows[0].doc==='prevention1'&&Number(rows[0].from)===page&&Number(rows[0].to)===page&&p?.status==='verified'&&p?.sourcePrecision==='exact-pdf-page-anchor';
}),'twelve single-page non-sprinkler facility concepts keep exact Prevention1 evidence');
const f06=V.curriculum.byId['F07-C06']?.sourceRanges||[];
ok(f06.length===2&&f06.every(r=>r.doc==='prevention1')&&Number(f06[0].from)===321&&Number(f06[1].from)===333&&V.contentPacks.authored['F07-C06']?.status==='verified'&&V.contentPacks.authored['F07-C06']?.sourcePrecision==='exact-pdf-page-anchor','simple + ESFR sprinkler concept keeps exact Prevention1 pages 321 and 333');
const f15=V.curriculum.byId['F07-C15']?.sourceRanges||[];
ok(f15.length===4&&f15.every(r=>r.doc==='prevention1')&&[167,174,433,482].every((p,i)=>Number(f15[i]?.from)===p)&&V.contentPacks.authored['F07-C15']?.status==='verified'&&V.contentPacks.authored['F07-C15']?.sourcePrecision==='exact-pdf-page-anchor','firefighter-support concept keeps exact Prevention1 pages 167,174,433,482');
ok(scopeVerified.length===0,'all 176 concepts now have exact official page evidence; page-anchor pending = 0');
ok(missing.length===0,'no curriculum concept remains in scope-verified/page-anchor-pending state');
ok(Object.keys(V.contentPacks.authored).filter(id=>V.curriculum.byId[id]).length===176,'exactly 176 valid authored concept packs');
ok(coverage.verified===176&&coverage.pending===0,'page-evidence truth reaches 176 page-verified + 0 page-anchor-pending');
ok(extra.length===0,`no authored concept IDs outside curriculum; extra=${extra.join(',')||'none'}`);
ok(Object.values(V.contentPacks.authored).every(p=>p.status==='verified'||p.status==='scope-verified'),'every authored content pack has an explicit verified/scope-verified truth state');
ok(V.curriculum.concepts.every(c=>V.contentPacks.authored[c.id]),'every curriculum concept has an authored study pack');
ok(V.curriculum.byId['F05-C05']&&V.curriculum.byId['F07-C05'],'hazardous materials and sprinkler scopes exist');
ok(V.contentPacks.authored['F05-C05']?.deepSections?.length>0&&V.contentPacks.authored['F07-C05']?.deepSections?.length>0,'new fire scopes have rich detail sections');
ok(V.curriculumExpansion2026?.addedConcepts===27,'official missing fire scope expansion adds 27 concepts');
ok(V.curriculumDepth119?.addedConcepts===14,'119 depth syllabus adds 14 granular fire/sprinkler concepts');
ok(V.FireDepth119?.concepts?.length===14,'14 new deep fire concepts have textbook packs');
ok(V.curriculum.byId['F03-C10']?.title==='플레임오버','flameover is a separate curriculum concept instead of being conflated with rollover');
ok((V.contentPacks.authored['F03-C06']?.compare||[]).map(x=>x?.[0]).join('|').includes('플레임오버')&&(V.contentPacks.authored['F03-C06']?.compare||[]).map(x=>x?.[0]).join('|').includes('롤오버'),'fire-phenomena comparison distinguishes flameover and rollover');
ok((V.contentPacks.authored['F03-C10']?.visuals||[]).includes('flameover-flow')&&!!V.Visual119.render('flameover-flow'),'flameover has its own learning flow diagram');
ok(V.FireQuestions119?.added===13,'deep fire batch adds 13 sourced practice questions with option explanations');
ok(V.GovernanceDepth119?.concepts?.length===12,'all fire-organization and disaster-management concepts receive textbook-depth enrichment');
ok(V.GovernanceQuestions119?.added===24,'governance batch adds twenty-four exam-style questions');
ok(V.GovernanceDepth119.concepts.every(id=>V.contentPacks.authored[id]?.visuals?.length>0),'governance concepts have learning diagrams');
ok(V.InvestigationDepth119?.concepts?.length===4,'all fire-investigation concepts receive textbook-depth enrichment');
ok(V.InvestigationQuestions119?.added===8,'fire-investigation batch adds eight exam-style questions');
ok(V.InvestigationDepth119.concepts.every(id=>V.contentPacks.authored[id]?.visuals?.length>0),'fire-investigation concepts have learning diagrams');
ok(V.SuppressionDepth119?.concepts?.length===8,'all eight suppression theory concepts receive textbook-depth enrichment');
ok(V.SuppressionQuestions119?.added===16,'suppression batch adds sixteen exam-style questions with option explanations');
ok(V.SuppressionDepth119.concepts.every(id=>V.contentPacks.authored[id]?.visuals?.length>0),'all suppression concepts have learning diagrams');
ok(V.FacilitiesDepth119?.concepts?.length===14,'fourteen non-sprinkler fire-protection concepts receive textbook-depth enrichment');
ok(V.FacilitiesQuestions119?.added>=17,'fire-protection depth batch adds exam-style questions with option explanations');
ok(V.FacilitiesDepth119.concepts.every(id=>V.contentPacks.authored[id]?.visuals?.length>0),'fire-protection depth concepts have learning diagrams');
ok(V.HazmatDepth119?.concepts?.length===6,'all six hazardous-material classes receive official common-rule depth');
ok(V.HazmatQuestions119?.added===7,'hazardous-material depth batch adds seven sourced questions');
ok(V.HazmatDepth119.concepts.every(id=>V.contentPacks.authored[id]?.calculations?.length>0),'all hazardous-material class lessons expose designated-quantity calculation contract');
ok(V.EMSDepth119?.concepts?.length===9,'nine high-yield EMS concepts receive textbook-depth enrichment');
const examGapIds=V.ExamGapEnrichment119?.conceptIds||[];
ok(['F03-C05','E11-C02','E03-C04','E03-C05','E21-C04','F05-C01','F07-C01','E01-C03','E05-C04','E20-C03','E14-C02','E14-C03','F03-C03','F04-C06','F03-C07','F03-C08','E09-C07','E11-C03','E11-C04','E11-C05'].every(id=>examGapIds.includes(id))&&new Set(examGapIds).size===examGapIds.length,'source-backed high-yield exam gap enrichment is loaded');
ok(V.curriculum.byId['E05-C04']?.title==='기록지·중증도 분류','E05-C04 student title includes START triage instead of hiding it under records only');
ok((V.contentPacks.authored['E14-C03']?.calculations||[]).some(x=>/4 mL/.test(x.formula||'')),'burn lesson exposes the source-backed Parkland calculation');
const burnIds=['119-finalgap-burn-01','119-finalgap-burn-02','119-finalgap-burn-03','119-finalgap-burn-04'];
const respIds=['119-finalgap-resp-01','119-finalgap-resp-02','119-finalgap-resp-03','119-finalgap-resp-04'];
const giIds=['119-finalgap-gi-01','119-finalgap-gi-02','119-finalgap-gi-03','119-finalgap-gi-04'];
ok(burnIds.every(id=>V.questionById[id]?.grade==='P'&&/2026 소방전술3\(구급\)/.test(String(V.questionById[id]?.source||''))),'four burn-depth/TBSA/special-burn drills remain P-grade and exact-textbook source-bound');
ok(respIds.every(id=>V.questionById[id]?.grade==='P'&&/2026 소방전술3\(구급\)/.test(String(V.questionById[id]?.source||''))),'four respiratory/COPD/inhalation drills remain P-grade and exact-textbook source-bound');
ok(giIds.every(id=>V.questionById[id]?.grade==='P'&&/2026 소방전술3\(구급\)/.test(String(V.questionById[id]?.source||''))),'four acute-abdomen/GI-bleeding drills remain P-grade and exact-textbook source-bound');
ok((V.contentPacks.authored['E14-C03']?.must||[]).some(x=>/손바닥.*1%/.test(x))&&(V.contentPacks.authored['E14-C03']?.must||[]).some(x=>/전기화상/.test(x))&&(V.contentPacks.authored['E14-C03']?.must||[]).some(x=>/화학화상/.test(x)),'burn lesson exposes TBSA small-area rule and special-burn distinctions');
ok((V.contentPacks.authored['E10-C03']?.must||[]).some(x=>/천식 ≠ COPD/.test(x))&&(V.contentPacks.authored['E10-C05']?.must||[]).some(x=>/흡입손상 3축/.test(x)),'respiratory lesson separates asthma/COPD and the three inhalation-injury mechanisms');
ok((V.contentPacks.authored['E12-C05']?.must||[]).some(x=>/토혈/.test(x)&&/혈변/.test(x))&&(V.contentPacks.authored['E12-C05']?.must||[]).some(x=>/배대동맥류/.test(x)),'GI lesson carries bleeding manifestations and high-risk abdominal emergency');
ok((V.contentPacks.authored['E09-C07']?.calculations||[]).some(x=>x.evidenceTier==='reconstructed-exam-practice'&&/P - R/.test(x.formula||'')),'oxygen-cylinder calculation is available only as clearly labeled reconstructed-exam practice');
ok((V.contentPacks.authored['E07-C03']?.calculations||[]).some(x=>x.evidenceTier==='standard-education-practice'&&/gtt\/min/.test(x.formula||'')),'IV-drip calculation is available only as clearly labeled standard-education practice');
ok((V.contentPacks.authored['E21-C04']?.detail||[]).some(x=>/0\.01mg\/kg/.test(x)&&/3~5분/.test(x))&&(V.contentPacks.authored['E21-C04']?.detail||[]).some(x=>/0\.1mg\/kg/.test(x)&&/0\.2mg\/kg/.test(x)),'pediatric ALS lesson includes official 2020 arrest and tachy drug anchors');
ok((V.contentPacks.authored['E14-C02']?.detail||[]).some(x=>/긴장성 기흉/.test(x)),'soft-tissue/chest lesson includes source-backed tension-pneumothorax deterioration and dressing response');
const abdTraumaIds=['119-finalgap-trauma-abd-01','119-finalgap-trauma-abd-02','119-finalgap-trauma-abd-03','119-finalgap-trauma-abd-04'];
ok(abdTraumaIds.every(id=>V.questionById[id]?.grade==='P'&&/2026 소방전술3\(구급\)/.test(String(V.questionById[id]?.source||''))),'four abdominal/pelvic severe-trauma drills remain P-grade and exact-textbook source-bound');
ok((V.contentPacks.authored['E14-C02']?.source||'').includes('250~251')&&(V.contentPacks.authored['E14-C02']?.source||'').includes('471~485'),'abdominal/pelvic trauma lesson binds both treatment and severe-trauma exact page ranges');
ok((V.contentPacks.authored['E14-C02']?.must||[]).some(x=>/SBP <90mmHg/.test(x))&&(V.contentPacks.authored['E14-C02']?.must||[]).some(x=>/골반골 골절/.test(x)),'severe-trauma physiologic threshold and pelvic-fracture criterion are explicit');
ok((V.contentPacks.authored['E14-C02']?.must||[]).some(x=>/생리식염수.*멸균드레싱/.test(x)),'evisceration care keeps exact moist sterile dressing rule');
ok(V.curriculum.byId['E01-C03']?.title==='응급구조사 법적책임·119구급대 법령','119-law content is visible in the EMS curriculum');
ok((V.contentPacks.authored['E01-C03']?.officialLinks||[]).length>=4,'119-law lesson exposes current official law source links');
ok((V.contentPacks.authored['E01-C03']?.officialLinks||[]).some(x=>/lsId=000218/.test(x.url||''))&&(V.contentPacks.authored['E01-C03']?.officialLinks||[]).some(x=>/144699215/.test(x.url||'')),'law lesson links current Emergency Medical Service Act and EMT scope Annex 14');
ok((V.contentPacks.authored['E01-C03']?.must||[]).some(x=>/심정지 에피네프린/.test(x))&&(V.contentPacks.authored['E01-C03']?.must||[]).some(x=>/비밀준수/.test(x)),'law lesson includes current first-level EMT expansion and confidentiality duty');
ok((V.contentPacks.authored['E05-C04']?.must||[]).some(x=>/3년 보관/.test(x))&&(V.contentPacks.authored['E05-C04']?.must||[]).some(x=>/이송거부/.test(x)),'record lesson includes current retention and refusal documentation rules');
const expandedLawIds=['119-law-ems-07','119-law-ems-08','119-law-ems-09','119-law-ems-10','119-law-ems-11','119-law-ems-12','119-law-ems-13','119-law-ems-14','119-law-ems-15','119-law-ems-16','119-law-ems-17','119-law-ems-18'];
ok(expandedLawIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'twelve expanded current-law drills remain P-grade exam-style practice');
const transportIds=['119-finalgap-trn-01','119-finalgap-trn-02','119-finalgap-trn-03','119-finalgap-trn-04','119-finalgap-trn-05','119-finalgap-trn-06','119-finalgap-trn-07','119-finalgap-trn-08'];
ok(transportIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'eight ground/air/international transport drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['E06-C01']?.must||[]).some(x=>/치료 적합성/.test(x)&&/최단 이송시간/.test(x)),'hospital-selection lesson exposes treatment suitability and minimum transport-time fallback');
ok((V.contentPacks.authored['E06-C04']?.must||[]).some(x=>/장비 선택/.test(x))&&(V.contentPacks.authored['E07-C04']?.must||[]).some(x=>/이송장비 사용 전/.test(x)),'transport equipment lessons connect equipment choice and pre-move safety checks');
ok((V.contentPacks.authored['E01-C03']?.must||[]).some(x=>/119항공대/.test(x))&&(V.contentPacks.authored['E01-C03']?.must||[]).some(x=>/국제구급대/.test(x))&&(V.contentPacks.authored['E01-C03']?.must||[]).some(x=>/선박\/항공기/.test(x)),'air/international lesson covers 119 aviation international EMS and ship/aircraft support');
const cardiacEmergencyIds=['119-finalgap-card-01','119-finalgap-card-02','119-finalgap-card-03','119-finalgap-card-04'];
ok(cardiacEmergencyIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four cardiovascular emergency drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['E11-C02']?.compare||[]).some(x=>x?.[0]==='STEMI')&&(V.contentPacks.authored['E11-C02']?.compare||[]).some(x=>x?.[0]==='NSTEMI'),'cardiac emergency lesson explicitly distinguishes STEMI and NSTEMI');
ok((V.contentPacks.authored['E11-C02']?.compare||[]).some(x=>x?.[0]==='심인성쇼크')&&(V.contentPacks.authored['E11-C02']?.compare||[]).some(x=>x?.[0]==='심인성 폐부종'),'cardiac emergency lesson directly compares cardiogenic shock and cardiogenic pulmonary edema');
ok((V.contentPacks.authored['E11-C02']?.officialLinks||[]).some(x=>/cntnts_sn=6770/.test(x.url||''))&&(V.contentPacks.authored['E11-C02']?.officialLinks||[]).some(x=>/cntnts_sn=3167/.test(x.url||'')),'cardiac emergency lesson links current KDCA AMI and pulmonary-edema sources');
const endoIds=['119-finalgap-endo-01','119-finalgap-endo-02','119-finalgap-endo-03','119-finalgap-endo-04'];
ok(endoIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four endocrine-emergency drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['E17-C02']?.compare||[]).some(x=>x?.[0]==='저혈당')&&(V.contentPacks.authored['E17-C02']?.compare||[]).some(x=>x?.[0]==='DKA')&&(V.contentPacks.authored['E17-C02']?.compare||[]).some(x=>x?.[0]==='HHS'),'endocrine lesson directly compares hypoglycemia DKA and HHS');
ok((V.contentPacks.authored['E17-C02']?.must||[]).some(x=>/15~20g/.test(x)&&/15분/.test(x))&&(V.contentPacks.authored['E17-C02']?.must||[]).some(x=>/쿠스마울/.test(x)),'endocrine lesson exposes hypoglycemia correction and DKA respiratory clue');
const sepsisIds=['119-finalgap-inf-03','119-finalgap-inf-04','119-finalgap-inf-05','119-finalgap-inf-06'];
ok(sepsisIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four expanded sepsis drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['E03-C04']?.must||[]).some(x=>/RR ≥22/.test(x)&&/SBP ≤100/.test(x)),'sepsis lesson exposes current KDCA respiratory-rate and systolic-pressure warning anchors');
ok((V.contentPacks.authored['E03-C04']?.compare||[]).some(x=>x?.[0]==='패혈증')&&(V.contentPacks.authored['E03-C04']?.compare||[]).some(x=>x?.[0]==='패혈성쇼크'),'infection lesson directly separates sepsis from septic shock');
ok((V.contentPacks.authored['E03-C04']?.officialLinks||[]).some(x=>/cntnts_sn=6755/.test(x.url||'')),'sepsis lesson links the current KDCA National Health Information Portal source');
const toxIds=['119-finalgap-tox-01','119-finalgap-tox-02','119-finalgap-tox-03','119-finalgap-tox-04'];
ok(toxIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four toxicology/anaphylaxis drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['E18-C01']?.must||[]).some(x=>/날록손/.test(x))&&(V.contentPacks.authored['E18-C01']?.must||[]).some(x=>/아트로핀.*2-PAM/.test(x)),'toxicology lesson exposes opioid and organophosphate antidote anchors');
ok((V.contentPacks.authored['E18-C01']?.compare||[]).some(x=>/오피오이드/.test(String(x?.[0])))&&(V.contentPacks.authored['E18-C01']?.compare||[]).some(x=>/콜린성/.test(String(x?.[0]))),'toxicology lesson compares opioid and cholinergic symptom patterns without claiming textbook toxidrome terminology');
ok((V.contentPacks.authored['E18-C02']?.must||[]).some(x=>/에피네프린 근육주사/.test(x))&&(V.contentPacks.authored['E18-C02']?.officialLinks||[]).some(x=>/cntnts_sn=6684/.test(x.url||'')),'anaphylaxis lesson binds intramuscular epinephrine to current KDCA evidence');
const shockIds=['119-finalgap-shock-01','119-finalgap-shock-02','119-finalgap-shock-03','119-finalgap-shock-04'];
ok(shockIds.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four multi-type shock drills remain P-grade exam-style practice');
ok(['저혈량성','심인성','폐쇄성','분포성'].every(k=>(V.contentPacks.authored['E13-C05']?.compare||[]).some(x=>x?.[0]===k)),'shock lesson directly compares all four required shock mechanisms');
ok((V.contentPacks.authored['E13-C05']?.must||[]).some(x=>/긴장성 기흉.*심장압전.*대량 폐색전증/.test(x)),'obstructive-shock lesson exposes all three high-yield mechanical causes');
ok((V.contentPacks.authored['E13-C05']?.officialLinks||[]).some(x=>/cntnts_sn=5259/.test(x.url||''))&&(V.contentPacks.authored['E13-C05']?.officialLinks||[]).some(x=>/cntnts_sn=6540/.test(x.url||'')),'shock comparison is bound to official KDCA hypotension and pulmonary-embolism sources');
ok(['E-LAW-01','E-LAW-02','E-LAW-03'].every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'all three EMS law rows close only after current official statute rule and annex evidence');
ok(['E-TRN-01','E-TRN-02'].every(id=>fullCoverage.rows.find(x=>x.id===id)?.status==='covered'),'ground ambulance hospital-selection and air/international transport rows close only after current-law and exact textbook evidence');
ok(fullCoverage.rows.find(x=>x.id==='F-HAZ-04')?.status==='covered','special-combustible gap is closed by current-law definition, quantity table and storage rules');
ok(fullCoverage.rows.find(x=>x.id==='F-BLD-02')?.status==='covered'&&fullCoverage.rows.find(x=>x.id==='F-BLD-03')?.status==='covered','building compartmentation and fire-material topics are source-closed by current Building Act evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-TRM-03')?.status==='covered','abdominal pelvic hemorrhage-risk and severe-trauma transport coverage closes only after exact-page evidence and focused drills');
ok(fullCoverage.rows.find(x=>x.id==='E-BURN-01')?.status==='covered','burn depth TBSA and special-burn coverage closes only after exact 2026 textbook evidence and focused drills');
ok(fullCoverage.rows.find(x=>x.id==='E-RESP-01')?.status==='covered','respiratory distress asthma COPD and inhalation-injury coverage closes on exact 2026 textbook evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-GI-01')?.status==='covered','acute abdominal pain GI bleeding and abdominal-emergency coverage closes on exact 2026 textbook evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-MCI-02')?.status==='covered','disaster command communications special-hazard CBRN and decontamination coverage closes only after official cross-source evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-PALS-01')?.status==='covered','pediatric resuscitation is covered by 2026 NFA basics plus official 2020 KACPR arrest/brady/tachy algorithms');
ok(fullCoverage.rows.find(x=>x.id==='F-BLD-01')?.status==='covered','wood-vs-fire-resistive building coverage is closed by direct textbook comparison and focused drills');
ok(fullCoverage.rows.find(x=>x.id==='E-ECG-02')?.status==='partial'&&fullCoverage.rows.find(x=>x.id==='E-ACLS-04')?.status==='covered','ECG remains partial while the named ACLS drug set is covered by 2026 NFA + official 2020 KACPR');
ok(fullCoverage.rows.find(x=>x.id==='E-ENDO-01')?.status==='covered','hypoglycemia DKA and HHS row closes only after current KDCA source comparison');
ok(fullCoverage.rows.find(x=>x.id==='E-INF-01')?.status==='covered','sepsis/infectious-emergency row closes only after current KDCA definition warning-sign and shock-progression evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-SHOCK-01')?.status==='covered','four-type shock comparison closes only after textbook plus official KDCA/KACPR evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-TOX-01')?.status==='covered','toxicology antidote toxidrome-pattern and anaphylaxis row closes only after NFA KDCA and E-GEN official evidence');
ok(fullCoverage.rows.find(x=>x.id==='E-TRM-02')?.status==='partial','chest-trauma row remains partial because hemothorax and cardiac-tamponade direct evidence is incomplete');
ok(fullCoverage.rows.find(x=>x.id==='E-CARD-01')?.status==='covered','ACS STEMI/NSTEMI pulmonary-edema and cardiogenic-shock row closes only after NFA textbook plus current KDCA evidence');
ok(fullCoverage.missing===0&&fullCoverage.rows.find(x=>x.id==='E-CALC-01')?.status==='partial'&&fullCoverage.rows.find(x=>x.id==='E-CALC-02')?.status==='partial','oxygen-cylinder and IV-drip calculations are no longer blank, but remain explicitly partial/nonverified');
ok(V.curriculum.byId['E03-C05']?.title==='위험물·CBRN 현장 구급·제독','CBRN/decontamination is visible in the EMS curriculum');
ok(V.curriculum.byId['E21-C04']?.title==='기도·호흡·소아소생 기초','pediatric resuscitation basics are visible in the EMS curriculum');
ok((V.contentPacks.authored['E03-C05']?.visuals||[]).includes('ems-hazmat-zones')&&!!V.Visual119.render('ems-hazmat-zones'),'CBRN three-zone/decon flow renders as a real study visual');
const mci2Ids=['119-finalgap-mci2-01','119-finalgap-mci2-02','119-finalgap-mci2-03','119-finalgap-mci2-04'];
ok(mci2Ids.every(id=>V.questionById[id]?.grade==='P'&&V.QuestionQuality119.isExamStyle(V.questionById[id])),'four disaster-command/CBRN drills remain P-grade exam-style practice');
ok((V.contentPacks.authored['E03-C05']?.must||[]).some(x=>/사고관리체계/.test(x))&&(V.contentPacks.authored['E03-C05']?.must||[]).some(x=>/현장 무선통신/.test(x)),'E-MCI-02 lesson explicitly covers command and disaster communications');
ok((V.contentPacks.authored['E03-C05']?.must||[]).some(x=>/CBRN 보강/.test(x))&&(V.contentPacks.authored['E03-C05']?.officialLinks||[]).some(x=>/106743/.test(x.url||'')),'CBRN layer is backed by the official NFSA CBRNE textbook');
ok((V.contentPacks.authored['E03-C05']?.officialLinks||[]).some(x=>/educationGuide/.test(x.url||'')),'CBRN layer links the current official SafeKorea chemical/biological/radiological education');
ok((V.contentPacks.authored['E21-C04']?.visuals||[]).includes('ems-pediatric-resuscitation')&&!!V.Visual119.render('ems-pediatric-resuscitation'),'pediatric resuscitation flow renders as a real study visual');
ok(V.curriculum.byId['F03-C05']?.title==='화재 진행 영향요인·건축구조'&&(V.contentPacks.authored['F03-C05']?.compare||[]).some(x=>/목조건축물/.test(String(x?.[0]))),'building-fire lesson compares wood and fire-resistive construction');
ok(V.curriculum.byId['E11-C02']?.title==='심질환·심전도 리듬'&&(V.contentPacks.authored['E11-C02']?.detail||[]).some(x=>/좁은 QRS/.test(x)&&/방실차단/.test(x)),'ECG lesson includes NFA three-lead categories and QRS-based rhythm approach');
const arrestEcgIds=['119-finalgap-ecg-arrest-01','119-finalgap-ecg-arrest-02','119-finalgap-ecg-arrest-03','119-finalgap-ecg-arrest-04'];
ok(arrestEcgIds.every(id=>V.questionById[id]?.grade==='P'&&/2020년 한국심폐소생술 가이드라인/.test(String(V.questionById[id]?.source||''))),'four cardiac-arrest ECG recognition drills stay practice-only and exam-standard source-bound');
ok((V.contentPacks.authored['E11-C04']?.visuals||[]).includes('ems-ecg-arrest-rhythms')&&(V.contentPacks.authored['E11-C05']?.visuals||[]).includes('ems-ecg-arrest-rhythms'),'VF/pVT and PEA/asystole lessons share the dedicated four-rhythm ECG visual');
ok(Array.isArray(V.Visual119?.data?.['ems-ecg-arrest-rhythms'])&&V.Visual119.data['ems-ecg-arrest-rhythms'].length===4,'ECG visual contract exposes exactly four arrest rhythms');
ok(/ecg-rhythm-grid/.test(V.Visual119.render('ems-ecg-arrest-rhythms')||'')&&/시험 판독용 학습 도식/.test(V.Visual119.render('ems-ecg-arrest-rhythms')||''),'dedicated ECG renderer produces waveform cards and labels them as study schematics');
ok((V.contentPacks.authored['E11-C05']?.must||[]).some(x=>/PEA.*맥박 없음/.test(x))&&(V.contentPacks.authored['E11-C05']?.traps||[]).some(x=>/전극.*리드|리드.*전극/.test(x)),'PEA pulse-check and asystole lead-check traps are explicit in the lesson');
const electricalIds=['119-finalgap-electrical-01','119-finalgap-electrical-02','119-finalgap-electrical-03','119-finalgap-electrical-04'];
ok(electricalIds.every(id=>V.questionById[id]?.grade==='P'&&/2020년 한국심폐소생술 가이드라인/.test(String(V.questionById[id]?.source||''))),'four electrical-therapy drills remain P-grade and exam-standard source-bound');
ok(V.questionById['119-finalgap-electrical-05']?.difficulty==='low'&&/경피 심장박동조율/.test(V.questionById['119-finalgap-electrical-05']?.q||''),'E11-C05 retains an explicit low-difficulty pacing recall item');
ok(Array.isArray(V.Visual119?.data?.['ems-electrical-therapy'])&&V.Visual119.data['ems-electrical-therapy'].length===3,'electrical-therapy visual exposes exactly three distinct modalities');
ok(/therapy-grid/.test(V.Visual119.render('ems-electrical-therapy')||'')&&/전기치료 3가지/.test(V.Visual119.render('ems-electrical-therapy')||''),'electrical-therapy renderer uses independent comparison cards instead of a false sequence');
ok((V.contentPacks.authored['E11-C05']?.must||[]).some(x=>/0\.5~1 J\/kg.*2 J\/kg/.test(x))&&(V.contentPacks.authored['E11-C05']?.must||[]).some(x=>/완전 AV block\/동기능부전/.test(x)),'synchronized cardioversion dose and pacing indication are explicit');
ok((V.contentPacks.authored['E11-C04']?.compare||[]).some(x=>x?.[0]==='제세동')&&(V.contentPacks.authored['E11-C05']?.compare||[]).some(x=>x?.[0]==='경피조율'),'defibrillation and pacing remain distinct in lesson comparisons');
ok((V.contentPacks.authored['E11-C03']?.detail||[]).some(x=>/2020.*에피네프린 1mg.*3~5분/.test(x))&&(V.contentPacks.authored['E11-C05']?.detail||[]).some(x=>/아데노신.*0\.1mg\/kg/.test(x)),'adult and pediatric ACLS dosing remains bound to the 2020 KACPR exam-standard source');
ok(V.curriculum.byId['E03-C04']?.title==='감염 관리·패혈증 주의'&&(V.contentPacks.authored['E03-C04']?.detail||[]).some(x=>/패혈증/.test(x)),'infection lesson adds conservative source-backed sepsis warning content');
ok(V.curriculum.byId['F07-C01']?.title==='소방시설 5분류·건축방재','building-fire fundamentals are visible in the facilities curriculum title');
ok((V.contentPacks.authored['F07-C01']?.officialLinks||[]).length>=3,'building-fire lesson exposes official Building Act source links');
ok((V.contentPacks.authored['F05-C01']?.specialCombustibles||[]).length===11,'special-combustible lesson exposes the eleven current law quantity rows');
ok(V.curriculum.byId['E20-C03']?.title==='정상분만·신생아 초기처치','newborn initial care is visible in the obstetric curriculum title');
ok((V.contentPacks.authored['E20-C03']?.detail||[]).some(x=>/아프가\(Apgar\).*1분.*5분/.test(x)),'newborn lesson includes exact-source Apgar 1- and 5-minute assessment');
ok((V.contentPacks.authored['E20-C03']?.must||[]).some(x=>/입 먼저.*코 다음/.test(x)),'newborn lesson preserves textbook mouth-before-nose suction order');
ok((V.contentPacks.authored['E20-C03']?.visuals||[]).includes('ems-newborn-initial')&&!!V.Visual119.render('ems-newborn-initial'),'newborn initial-care flow renders as a real study visual');
const startIds=['119-finalgap-start-01','119-finalgap-start-02','119-finalgap-start-03','119-finalgap-start-04'];
const nrpIds=['119-finalgap-nrp-01','119-finalgap-nrp-02','119-finalgap-nrp-03','119-finalgap-nrp-04'];
ok(startIds.every(id=>V.questionById[id]?.grade==='P'&&/2026 소방전술3\(구급\) 86(?:~87)?쪽/.test(String(V.questionById[id]?.source||''))),'four START drills remain P-grade and exact-textbook source-bound');
ok(nrpIds.every(id=>V.questionById[id]?.grade==='P'&&/2026 소방전술3\(구급\)/.test(String(V.questionById[id]?.source||''))),'four newborn-resuscitation drills remain P-grade and exact-textbook source-bound');
ok((V.contentPacks.authored['E05-C04']?.must||[]).some(x=>/RPM.*Respiration.*Pulse.*Mental Status/.test(x))&&(V.contentPacks.authored['E05-C04']?.must||[]).some(x=>/10.*30/.test(x)),'START lesson exposes RPM and exact textbook respiratory thresholds');
ok((V.contentPacks.authored['E05-C04']?.visuals||[]).includes('ems-start-triage')&&!!V.Visual119.render('ems-start-triage'),'START triage renders a dedicated study visual');
ok((V.contentPacks.authored['E20-C03']?.must||[]).some(x=>/맥박 <60/.test(x))&&(V.contentPacks.authored['E20-C03']?.must||[]).some(x=>/3 : 1/.test(x)),'newborn lesson exposes the exact pulse threshold and 3-to-1 compression ratio');
ok((V.contentPacks.authored['E20-C03']?.visuals||[]).includes('ems-newborn-resuscitation')&&!!V.Visual119.render('ems-newborn-resuscitation'),'newborn full resuscitation algorithm renders a dedicated study visual');
ok(V.questionById['119-finalgap-start-01']?.difficulty==='low'&&V.questionById['119-finalgap-nrp-01']?.difficulty==='low','START and newborn concepts retain explicit low-difficulty contract items');
ok(fullCoverage.rows.find(x=>x.id==='E-NRP-01')?.status==='covered','newborn resuscitation closes only after exact 2026 textbook ventilation pulse-threshold and 3-to-1 compression algorithm evidence');
ok((V.contentPacks.authored['F03-C07']?.compare||[]).some(x=>/굴뚝|연돌/.test(String(x?.[0]))),'smoke/Flow Path lesson compares stack-effect smoke movement');
ok((V.contentPacks.authored['F03-C08']?.compare||[]).some(x=>/UVCE/.test(String(x?.[0]))),'explosion lesson compares UVCE with other explosion mechanisms');
ok(V.EMSQuestions119?.added===9,'nine page-grounded EMS exam-style questions are loaded');
ok(V.EMSRestoredVerified119?.added===5&&V.EMSRestoredVerified119.scopes.join(',')==='E02,E03,E04,E05,E07','five page-verified EMS scope-gap questions are loaded without past-exam claims');
ok(V.EMSRestoredVerified119?.questions.every(id=>V.questionById[id]?.grade==='B'&&V.questionById[id]?.restoredVerified===true&&V.questionById[id]?.pastExamClaim===false),'restored EMS gap questions remain manually reviewed B-grade evidence');
ok(V.EMSDepth119.concepts.every(id=>V.contentPacks.authored[id]?.visuals?.length>0),'high-yield EMS depth concepts have learning diagrams');
ok(V.emsRich2026?.scopes===24&&V.emsRich2026?.concepts===107,'all 24 EMS chapters / 107 concepts receive structured rich detail');
ok((V.depthEnrichment?.conceptIds||[]).length>=19,'source-depth enrichment batch 1 is loaded');
ok(!!V.depthEnrichment2,'source-depth enrichment batch 2 is loaded');

const brandFiles=[
  fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),
  fs.readFileSync(new URL('./preview.html',import.meta.url),'utf8'),
  fs.readFileSync(new URL('./app.js',import.meta.url),'utf8'),
  fs.readFileSync(new URL('./selftest.js',import.meta.url),'utf8')
].join('\n');
ok(!brandFiles.includes('AI과외'),'legacy AI과외 brand is absent from v9 runtime surfaces');
ok(brandFiles.includes('119'),'119 brand is present in v9 runtime surfaces');
const manifest=JSON.parse(fs.readFileSync(new URL('./manifest.webmanifest',import.meta.url),'utf8'));
ok(manifest.start_url==='./'&&manifest.scope==='./','v9 PWA manifest is subpath-scoped');
ok(manifest.name==='119'&&manifest.short_name==='119','PWA install name is unified as 119');
const sw=fs.readFileSync(new URL('./sw.js',import.meta.url),'utf8');
ok(sw.includes("const PREFIX='ai-tutor-v9-'"),'v9 service worker uses a dedicated cache prefix');
ok(!sw.includes('ai-tutor-v8'),'v9 service worker never targets v8 cache names');
ok(sw.includes("'./sync-merge.js'")&&sw.includes("'./sync-ui.js'"),'v9 sync hardening files are offline-cached');
ok(sw.includes("'./depth-enrichment.js'")&&sw.includes("'./depth-enrichment-2.js'")&&sw.includes("'./content-rich-2026.js'")&&sw.includes("'./ems-rich-2026.js'"),'v9 depth enrichments are offline-cached');
ok(sw.includes("'./curriculum-complete-2026.js'"),'complete curriculum expansion is offline-cached');
ok(sw.includes("'./coverage-map-119.js'"),'full exam Coverage Map is offline-cached');
ok(sw.includes("'./questions-ems-restored-verified-119.js'"),'restored EMS verified questions are offline-cached');
ok(sw.includes("'./questions-final-gap-119.js'"),'final source-backed gap practice bank is offline-cached');
ok(sw.includes("'./questions-pals-advanced-119.js'"),'official pediatric ALS practice bank is offline-cached');
ok(sw.includes("'./questions-fire-terminology-119.js'"),'exact-page fire terminology practice bank is offline-cached');
ok(sw.includes("'./exam-gap-enrichment-119.js'"),'exam gap enrichment is offline-cached');
ok(sw.includes("'./questions-calculation-119.js'"),'calculation practice bank is offline-cached');
ok(sw.includes("'./questions-law-119.js'"),'current-law practice bank is offline-cached');
ok(sw.includes("'./questions-special-combustible-119.js'"),'special-combustible practice bank is offline-cached');
ok(sw.includes("'./questions-ems-gap-practice-119.js'"),'CBRN/PALS practice bank is offline-cached');

const v9index=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
ok(v9index.includes("register('./sw.js',{scope:'./'})"),'v9 service worker registers only at ./ scope');
ok(v9index.indexOf('./curriculum-complete-2026.js')>v9index.indexOf('./curriculum.js')&&v9index.indexOf('./curriculum-complete-2026.js')<v9index.indexOf('./content-packs.js'),'complete curriculum loads before content packs');
ok(v9index.indexOf('./depth-enrichment.js')>v9index.indexOf('./verified-final.js'),'depth enrichment loads after base verified packs');
ok(v9index.indexOf('./depth-enrichment-2.js')>v9index.indexOf('./depth-enrichment.js'),'depth enrichment batch 2 loads after batch 1');
ok(v9index.indexOf('./questions-fire-terminology-119.js')>v9index.indexOf('./questions-pals-advanced-119.js')&&v9index.indexOf('./questions-fire-terminology-119.js')<v9index.indexOf('./question-bank-119.js'),'exact-page fire terminology questions load before grounded question factory');
ok(v9index.indexOf('./sync-merge.js')<v9index.indexOf('./auth.js'),'conflict-safe merge loads before member auth');
ok(v9index.indexOf('./pdf.js')<v9index.indexOf('./auth.js'),'private document sync API loads before member auth');
ok(v9index.indexOf('./source-catalog-119.js')>v9index.indexOf('./pdf.js')&&v9index.indexOf('./source-catalog-119.js')<v9index.indexOf('./source-pdf.js'),'official source catalog loads before PDF engine');
ok(v9index.indexOf('./source-pdf.js')>v9index.indexOf('./source-catalog-119.js')&&v9index.indexOf('./source-pdf.js')<v9index.indexOf('./app.js'),'official PDF highlight engine loads before app UI');
ok(v9index.indexOf('./coverage-map-119.js')>v9index.indexOf('./calculation-contract-119.js')&&v9index.indexOf('./coverage-map-119.js')<v9index.indexOf('./store.js'),'full exam Coverage Map loads after content/question contracts and before runtime state');


const sql=fs.readFileSync(new URL('../supabase/v9-schema.sql',import.meta.url),'utf8');
const studyTables=['study_profiles','study_user_progress','study_user_answers','study_wrong_answers','study_review_schedule','study_personal_notes','study_private_documents','study_document_chunks','study_sessions','study_exam_history','study_tutor_preferences'];
for(const table of studyTables){
  ok(sql.includes(`alter table public.${table} enable row level security;`),`${table} RLS enabled`);
}
ok(!/create table if not exists public\.profiles\s*\(/.test(sql),'shared backend never creates or repurposes investment public.profiles');
ok(sql.includes("values('study-private-v9','study-private-v9',false"),'Study private storage bucket is non-public');
ok(sql.includes("bucket_id='study-private-v9'"),'Storage policies are isolated to the Study bucket');
ok(sql.includes('to authenticated'),'Study policies explicitly target authenticated users');
ok(sql.includes('(select auth.uid())'),'Study owner checks use cached auth.uid() form');
ok(!sql.toLowerCase().includes('public = true'),'schema never enables public storage');
ok((sql.match(/deleted_at timestamptz/g)||[]).length>=2,'personal notes and private documents support deletion tombstones');
ok(!sql.includes('create trigger on_ai_tutor_user_created')&&!sql.includes('handle_new_ai_tutor_user'),'shared backend adds no project-wide auth.users bootstrap trigger');
ok(!/^\s*alter\s+default\s+privileges\b/im.test(sql),'shared schema does not execute project-wide default-privilege changes');

const hardening=fs.readFileSync(new URL('../supabase/v9-owner-hardening.sql',import.meta.url),'utf8');
ok(hardening.includes('study_private_documents_id_user_id_key'),'private document identity constraint is Study-namespaced');
ok(hardening.includes('foreign key (document_id, user_id)'),'document chunks use an owner-bound composite foreign key');
ok(hardening.includes('public.study_private_documents'),'document hardening never targets investment tables');
ok(hardening.includes('d.id = document_id and d.user_id = (select auth.uid())'),'document chunk RLS verifies parent ownership');

const liveHardening=fs.readFileSync(new URL('../supabase/v9-live-backend-hardening.sql',import.meta.url),'utf8');
ok(liveHardening.includes('revoke all privileges on table public.%I from anon'),'anonymous Data API access is explicitly revoked for Study tables');
ok(liveHardening.includes('grant select, insert, update, delete on table public.%I to authenticated'),'authenticated Data API grants are explicit');
ok(liveHardening.includes("'study_profiles'")&&liveHardening.includes("'study_tutor_preferences'"),'live hardening is bound to Study-prefixed tables');
ok(!/^\s*alter\s+default\s+privileges\b/im.test(liveHardening),'live hardening does not execute investment-app default-privilege changes');
ok(!/^\s*create\s+(?:or\s+replace\s+)?function\b/im.test(liveHardening)&&!/^\s*create\s+trigger\b/im.test(liveHardening),'live hardening adds no project-wide trigger/function');
ok(liveHardening.includes('c.relrowsecurity'),'live hardening aborts if any Study private table lacks RLS');

const syncMerge=fs.readFileSync(new URL('./sync-merge.js',import.meta.url),'utf8');
ok(syncMerge.includes('{...clone(prev),...clone(row)}')&&syncMerge.includes('{...clone(row),...clone(prev)}'),'remote summary merges preserve richer local exam-analysis fields without DB mutation');

const auth=fs.readFileSync(new URL('./auth.js',import.meta.url),'utf8');
const appCode=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
ok(appCode.includes('data-doc-list')&&appCode.includes('refreshDocsList()'),'personal-doc hydration updates only the document list and preserves the file input');
ok(auth.includes("event==='SIGNED_OUT'")&&auth.includes('V.Store.switchOwner(V.Store.guestId)'), 'SIGNED_OUT auth events switch runtime ownership back to the guest namespace');
ok(auth.includes("'session-expired'")&&auth.includes("'manual-signout'"),'auth runtime distinguishes session expiry from explicit logout');
ok(appCode.includes('로그인 세션이 만료되어 게스트 모드로 전환되었습니다.')&&appCode.includes('로그인 세션 만료 · 다시 로그인해주세요'),'session expiry UX provides persistent and immediate re-login guidance');
ok(appCode.includes('examReportId')&&appCode.includes('오답·미응답 분석')&&appCode.includes('incorrectQuestionIds'),'post-exam analytics stores the local answer snapshot and renders wrong/unanswered analysis');
ok(appCode.includes('data-exam-report')&&appCode.includes('data-report-close'),'recent exam history exposes a reopenable local analysis flow');
for(const [logical,physical] of Object.entries({profiles:'study_profiles',user_progress:'study_user_progress',user_answers:'study_user_answers',wrong_answers:'study_wrong_answers',review_schedule:'study_review_schedule',personal_notes:'study_personal_notes',private_documents:'study_private_documents',document_chunks:'study_document_chunks',study_sessions:'study_sessions',exam_history:'study_exam_history',tutor_preferences:'study_tutor_preferences'})){
  ok(auth.includes(`${logical}:'${physical}'`),`member sync maps ${logical} -> ${physical}`);
}
ok(auth.includes('remoteFirstOnSignIn:true'),'existing-member sign-in is remote-first before local push');
ok(auth.includes('remoteFirstOnManualSync:true'),'manual sync is remote-first before local push');
ok(auth.includes('await pullRemoteIntoLocal(user.id);return syncAllInternal(user.id)'),'manual sync performs pull/merge before push');
ok(auth.includes('deleted_at:iso(d.deletedAt)'),'private document tombstones are uploaded');
ok(auth.includes('client.from(T.document_chunks).delete()'),'deleted private documents remove remote extracted chunks');
ok(auth.includes('originalFilesAutoUpload:false'),'original personal files are never auto-uploaded');
ok(!auth.includes('.storage.from('),'auth sync has no original-file storage upload path');
ok(auth.includes('sharedProjectNamespace:\'study_*\''),'sync contract records the Study shared-project namespace');
ok(auth.includes('supabasePublishableKey'),'browser auth prefers the Supabase publishable key');
ok(auth.includes('enableCloudSync===true'),'backend connection is feature-gated until explicitly enabled');
ok(auth.includes("client.auth.resend({type:'signup',email})"),'signup confirmation email can be resent without changing project-wide auth settings');
ok(auth.includes('pendingEmailConfirmation:true'),'unconfirmed signup is represented as a pending state instead of a false failure');
ok(appCode.includes('data-resend-confirmation'),'account UI exposes confirmation-email resend');
ok(appCode.includes('Email not confirmed'),'account UI explains unconfirmed-email sign-in failures');

const membershipSql=fs.readFileSync(new URL('../supabase/v9-study-membership-trigger.sql',import.meta.url),'utf8');
ok(membershipSql.includes('create table if not exists public.study_memberships'),'Study membership registry is migration-controlled');
ok(membershipSql.includes("source text not null default 'study-v9' check (source = 'study-v9')"),'Study membership source is constrained');
ok(membershipSql.includes('grant select on table public.study_memberships to authenticated'),'clients can only read their own membership through RLS');
ok(membershipSql.includes('revoke all on function public.handle_new_study_v9_user() from public, anon, authenticated'),'Study bootstrap SECURITY DEFINER is not client-callable');
ok(membershipSql.includes('create policy study_membership_gate on public.%I as restrictive for all to authenticated'),'every Study table receives a restrictive membership gate');
ok(membershipSql.includes("bucket_id='study-private-v9'")&&membershipSql.includes('from public.study_memberships m'),'Study Storage policies require both owner folder and Study membership');

const guard=fs.readFileSync(new URL('./auth-membership-guard.js',import.meta.url),'utf8');
ok(guard.includes("from('study_memberships')"),'browser session guard checks server-created Study membership');
ok(guard.includes('STUDY_ACCOUNT_REQUIRED'),'non-Study shared-auth sessions fail closed');
ok(auth.includes("V.Auth?.hasStudyMembership&&!(await V.Auth.hasStudyMembership(next.id))"),'member adopt checks Study membership before any remote pull/push');
ok(guard.includes('membershipPreflightBeforeAdopt:true'),'membership preflight contract is recorded in sync policy');
ok(v9index.indexOf('./auth.js')<v9index.indexOf('./auth-membership-guard.js')&&v9index.indexOf('./auth-membership-guard.js')<v9index.indexOf('./app.js'),'Study membership guard loads after auth and before app UI');
const preview=fs.readFileSync(new URL('./preview.html',import.meta.url),'utf8');
ok(preview.includes('enableCloudSync:true')&&preview.includes('previewOnly:true'),'preview keeps real cloud sync enabled and remains explicitly preview-only');
ok(preview.includes('./auth-membership-guard.js'),'preview uses the same membership guard as v9');
ok(preview.indexOf('./supabase-lite.js')<preview.indexOf('./auth.js'),'preview loads same-origin auth client before member auth');
ok(auth.includes("clientRuntime:'same-origin-lite'")&&auth.includes('externalSdkRequired:false'),'auth runtime contract forbids external SDK dependency');
ok(!auth.includes('esm.sh')&&!auth.includes('cdn.jsdelivr.net')&&!auth.includes('unpkg.com'),'member auth has no external runtime SDK dependency');
const supabaseLite=fs.readFileSync(new URL('./supabase-lite.js',import.meta.url),'utf8');
ok(supabaseLite.includes("/auth/v1/signup"),'same-origin auth client implements signup');
ok(supabaseLite.includes("/auth/v1/token?grant_type=password"),'same-origin auth client implements password sign-in');
ok(supabaseLite.includes("/auth/v1/resend"),'same-origin auth client implements confirmation resend');
ok(supabaseLite.includes("/rest/v1/"),'same-origin auth client implements RLS Data API calls');
ok(v9index.indexOf('./supabase-lite.js')<v9index.indexOf('./auth.js'),'same-origin auth client loads before member auth');
ok(!auth.includes('service_role')&&!auth.includes('sb_secret_'),'browser auth contains no privileged Supabase key');
const configExample=fs.readFileSync(new URL('./config.example.js',import.meta.url),'utf8');
ok(configExample.includes('supabasePublishableKey'),'config example uses a publishable key');
ok(!/supabase(?:ServiceRole|Secret|Service)_?Key\s*:/i.test(configExample)&&!/sb_secret_[A-Za-z0-9]/.test(configExample),'config example never configures a privileged key');
const config=fs.readFileSync(new URL('./config.js',import.meta.url),'utf8');
ok(config.includes('enableCloudSync:true'),'release-ready v9 config enables real Study cloud sync');
ok(config.includes("officialPdfProxyBase:'https://study-119-pdf-proxy.vercel.app'"),'release-ready v9 config pins the verified official PDF proxy');
ok(!config.includes('bawcbkoyovbeajkrnduq'),'release-ready v9 config never points at Investment Production');
ok(config.includes("supabaseUrl:'https://petlfbztqguuzkasfpug.supabase.co'"),'checked-in v9 config pins the approved shared Supabase URL');
ok(/supabasePublishableKey:'sb_publishable_[A-Za-z0-9_-]+'/.test(config),'checked-in v9 config uses a browser-safe publishable key');
ok(!/sb_secret_[A-Za-z0-9_-]+/.test(config)&&!/service_role/i.test(config),'checked-in v9 config contains no privileged Supabase key');

const sourceCatalog=fs.readFileSync(new URL('./source-catalog-119.js',import.meta.url),'utf8');
ok(sourceCatalog.includes('noUserUploadRequired:true'),'official source catalog forbids user-upload requirement');
ok(sourceCatalog.includes('officialPageFallback:true'),'official source catalog has official-page fallback');
ok(sourceCatalog.includes('const proxy=doc=>')&&['fire1','fire2','ems','prevention1','prevention2','law1','law2','law3','law4','law5'].every(k=>sourceCatalog.includes(`directPdf:proxy('${k}')`)),'all ten official textbooks use the configured PDF proxy resolver');
ok(sourceCatalog.includes('arbitraryUrlProxy:false')&&sourceCatalog.includes('allCatalogDocsProxyable:true')&&sourceCatalog.includes('crossOriginProxy:!!proxyBase'),'official source catalog supports dedicated proxy origin while forbidding arbitrary URL proxying');
const officialProxy=fs.readFileSync(new URL('./api/official-pdf.js',import.meta.url),'utf8');
ok(officialProxy.includes("const SOURCES=Object.freeze")&&['fire1','fire2','ems','prevention1','prevention2','law1','law2','law3','law4','law5'].every(k=>officialProxy.includes(k+":")),'official PDF proxy uses a fixed ten-document allowlist');
ok(!/req\.query\?\.url|req\.query\.url|new URL\(.*req\.query/i.test(officialProxy),'official PDF proxy accepts no arbitrary upstream URL');
ok(officialProxy.includes("req.headers.range")&&officialProxy.includes("'content-range'")&&officialProxy.includes("'accept-ranges'"),'official PDF proxy forwards byte-range semantics for PDF.js');
ok(officialProxy.includes('resolveSource(doc')&&officialProxy.includes('extractAttachmentCandidates')&&officialProxy.includes('selectWorkingCandidate')&&officialProxy.includes('pdfProbe')&&officialProxy.includes('jsessionid'),'official PDF proxy resolves and verifies session-bound NFA PDF endpoint candidates server-side');
ok(officialProxy.includes("const BASE='https://www.nfa.go.kr'")&&officialProxy.includes("/nfsa/releaseinformation/archive/materials/"),'official PDF proxy resolver is pinned to NFA official materials');

const sourcePdf=fs.readFileSync(new URL('./source-pdf.js',import.meta.url),'utf8');
ok(sourcePdf.includes('pdf-evidence-line')&&sourcePdf.includes('evidenceLines('),'official PDF evidence highlights scored evidence lines instead of every matching word');
ok(sourcePdf.includes('devicePixelRatio')&&sourcePdf.includes('outputScale'),'official PDF canvas uses device-pixel scaling for crisp mobile rendering');
ok(sourcePdf.includes('serverUpload:false')&&sourcePdf.includes('originalUnmodified:true'),'official source PDFs are never server-uploaded and remain unmodified');
ok(sourcePdf.includes('userUploadRequired:false')&&sourcePdf.includes('officialRemotePreferred:true'),'PDF evidence prefers official remote sources and never requires user upload');
ok(sourcePdf.includes('SOURCE_REMOTE_UNRESOLVED'),'unresolved direct PDFs fail closed to official-page fallback');
const pdf=fs.readFileSync(new URL('./pdf.js',import.meta.url),'utf8');
ok(pdf.includes('exportForSync')&&pdf.includes('importFromSync'),'private extracted text supports owner-scoped member sync');
ok(pdf.includes('deletedDocuments')&&pdf.includes('deletionTombstones:true'),'local private-document deletion uses owner-scoped tombstones');
ok(pdf.includes('serverUpload:false')&&pdf.includes('crossUserSharing:false'),'personal document defaults remain private/no-share');

const liveClosedLoop=fs.readFileSync(new URL('../supabase/tests/v9-live-closed-loop.sql',import.meta.url),'utf8');
for(const table of ['study_user_progress','study_user_answers','study_wrong_answers','study_review_schedule','study_personal_notes','study_private_documents','study_document_chunks','study_sessions','study_exam_history']){
  ok(liveClosedLoop.includes('public.'+table),`live closed-loop covers ${table}`);
}
ok(liveClosedLoop.includes("set_config('request.jwt.claim.sub', a::text, true)")&&liveClosedLoop.includes("set_config('request.jwt.claim.sub', b::text, true)"),'live closed-loop tests two distinct Study identities');
ok(liveClosedLoop.includes('B_CAN_READ_A_DOC')&&liveClosedLoop.includes('B_CAN_INSERT_FOR_A'),'live closed-loop locks cross-owner negative cases');
ok(liveClosedLoop.includes("delete from public.study_document_chunks where id like '__liveqa_%'"),'live closed-loop includes explicit cleanup');
const root=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
ok(!root.includes('/v9/')&&!root.includes('v9/app.js'),'production root remains v8.6 during development');
console.log(JSON.stringify({concepts:V.curriculum.totalConcepts,verifiedPacks:coverage.verified,enrichedPacks:Object.values(V.contentPacks.authored).filter(p=>p.depthEnriched).length,questions:V.questions.length,mock,studyTables},null,2));