import { chromium } from 'playwright';

const base='http://127.0.0.1:4173/v9/index.html';
function assert(cond,msg){if(!cond)throw new Error(msg);console.log('PASS',msg)}
async function noX(page,label){const r=await page.evaluate(()=>({doc:[document.documentElement.scrollWidth,document.documentElement.clientWidth],body:[document.body.scrollWidth,document.body.clientWidth]}));assert(r.doc[0]<=r.doc[1]+1&&r.body[0]<=r.body[1]+1,`${label}: no page horizontal overflow (${JSON.stringify(r)})`)}
async function errors(page){const arr=[];page.on('pageerror',e=>arr.push('pageerror:'+e.message));page.on('console',m=>{if(m.type()==='error'&&!/favicon/i.test(m.text()))arr.push('console:'+m.text())});return arr}

const browser=await chromium.launch({headless:true});
try{
  const desktop=await browser.newContext({viewport:{width:1440,height:900}});const p=await desktop.newPage();const err=await errors(p);
  await p.goto(base,{waitUntil:'domcontentloaded'});await p.waitForSelector('.app');await noX(p,'desktop home');
  await p.locator('[data-go="study"]').first().click();await p.waitForSelector('.workspace');await noX(p,'desktop study');
  assert(await p.locator('.actionbar').isVisible(),'desktop fixed study action bar visible');
  const action=await p.locator('.actionbar').boundingBox(),vp=p.viewportSize();assert(action&&action.y+action.height<=vp.height+1,'desktop action bar inside viewport');
  assert(await p.locator('.study-body').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'desktop study body has no horizontal overflow');
  await p.locator('[data-outline]').click();await p.waitForSelector('.outline.open');assert(await p.locator('.outline.open').isVisible(),'desktop TOC drawer opens');
  await p.locator('[data-concept="F03-C06"]').click();await p.waitForFunction(()=>window.AITUTOR_V9.Store.state.conceptId==='F03-C06');assert((await p.locator('.concept-head h2').textContent()).includes('플래시오버'),'TOC selects concept without permanent extra columns');
  await p.locator('[data-study-tab="compare"]').click();assert((await p.locator('.study-body').textContent()).includes('백드래프트'),'comparison tab renders rich concept content');
  const coverage=await p.evaluate(()=>window.AITUTOR_V9.contentPacks.coverage());assert(coverage.verified===135,'browser runtime sees 135/135 verified concept packs');

  const readiness=await p.evaluate(()=>window.AITUTOR_V9.examReadiness());
  await p.locator('[data-go="exam"]').first().click();await p.waitForSelector('.page');const examText=await p.locator('.page').textContent();assert(await p.locator('[data-exam-start="practice"]').count()===1,'practice mode remains available');
  if(readiness.ready){assert(!examText.includes('실전모드 잠금'),'real mock exam unlocks only after 25+40 coverage');assert(await p.locator('[data-exam-start="real"]').count()===1,'real exam start button appears after coverage gate');await p.locator('[data-exam-start="real"]').click();await p.waitForSelector('[data-exam-answer]');const integrity=await p.evaluate(()=>{const qs=window.AITUTOR_V9.App.runtime.exam.qs;return{total:qs.length,unique:new Set(qs.map(q=>q.id)).size,fire:qs.filter(q=>q.subject==='fire').length,ems:qs.filter(q=>q.subject==='ems').length}});assert(integrity.total===65&&integrity.unique===65&&integrity.fire===25&&integrity.ems===40,`real mock uses 65 distinct questions with 25+40 split (${JSON.stringify(integrity)})`);await p.evaluate(()=>{window.AITUTOR_V9.App.runtime.exam=null;window.AITUTOR_V9.App.render()})}else{assert(examText.includes('실전모드 잠금'),'real mock exam is visibly fail-closed');assert(await p.locator('[data-exam-start="real"]').count()===0,'real exam start button absent while coverage insufficient')}

  await p.evaluate(()=>{const V=window.AITUTOR_V9,q=V.questions.find(x=>x.conceptId==='F03-C06');V.Mastery.recordAnswer(q,(q.a+1)%4,'sure',8000);V.App.render()});await p.locator('[data-go="wrong"]').first().click();await p.waitForSelector('[data-concept="F03-C06"]');assert((await p.locator('.page').textContent()).includes('위험오답'),'confident wrong is marked dangerous');await p.locator('[data-concept="F03-C06"]').first().click();await p.waitForFunction(()=>window.AITUTOR_V9.Store.state.page==='study'&&window.AITUTOR_V9.Store.state.conceptId==='F03-C06');assert(true,'wrong answer treatment returns to exact concept');

  const isolation=await p.evaluate(async()=>{const V=window.AITUTOR_V9,owner=V.Store.ownerId;const file=new File(['내 개인 노트: 테스트 전용 내용'],'isolation-note.txt',{type:'text/plain'});await V.PrivateDocs.ingest(file,{kind:'personal'});const mine=(await V.PrivateDocs.listDocuments('personal')).length;V.Store.switchOwner('qa-other-user');const other=(await V.PrivateDocs.listDocuments('personal')).length;V.Store.switchOwner(owner);return{mine,other,privateRules:V.PrivateDocs.privacyRules}});assert(isolation.mine>=1&&isolation.other===0,'private documents are isolated per owner in local-first store');assert(isolation.privateRules.crossUserSharing===false&&isolation.privateRules.serverUpload===false,'personal docs are no-share/no-auto-upload by default');

  // Dedicated /v9 service worker must take control and support an offline shell without touching v8 caches.
  const sw=await p.evaluate(async()=>{const reg=await navigator.serviceWorker.ready;return{scope:reg.scope,controller:!!navigator.serviceWorker.controller,manifest:document.querySelector('link[rel="manifest"]')?.getAttribute('href')}});assert(sw.scope.endsWith('/v9/'),'v9 service worker scope is limited to /v9/');assert(sw.manifest==='./manifest.webmanifest','v9 manifest is linked');await p.reload({waitUntil:'domcontentloaded'});await p.waitForSelector('.app');assert(await p.evaluate(()=>!!navigator.serviceWorker.controller),'v9 service worker controls the page after reload');await desktop.setOffline(true);await p.reload({waitUntil:'domcontentloaded'});await p.waitForSelector('.app');assert(await p.locator('.app').isVisible(),'v9 PWA shell reloads while offline');await p.locator('[data-go="settings"]').first().click();await p.waitForSelector('.settings-page');assert(await p.locator('.settings-account').isVisible(),'desktop settings account controls are inline');assert(await p.locator('[data-profile-save]').isVisible(),'desktop profile-save visible');await noX(p,'desktop settings');await noX(p,'desktop offline PWA');await desktop.setOffline(false);
  assert(err.length===0,`desktop runtime errors = 0 (${err.join(' | ')})`);await desktop.close();

  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true});const m=await mobile.newPage();const merr=await errors(m);await m.goto(base,{waitUntil:'domcontentloaded'});await m.waitForSelector('.mobile-nav');await noX(m,'mobile home');await m.locator('[data-go="study"]').last().click();await m.waitForSelector('.actionbar');await noX(m,'mobile study');const boxes=await m.evaluate(()=>{const a=document.querySelector('.actionbar').getBoundingClientRect(),n=document.querySelector('.mobile-nav').getBoundingClientRect();return{a:{top:a.top,bottom:a.bottom},n:{top:n.top,bottom:n.bottom},vw:innerWidth}});assert(boxes.a.bottom<=boxes.n.top+1,`mobile study action bar sits above global nav (${JSON.stringify(boxes)})`);assert(await m.locator('.actionbar').isVisible(),'mobile AI/문제/근거 action bar visible');await m.locator('.mobile-nav [data-go="settings"]').click();await m.waitForSelector('.settings-page');assert(await m.locator('.settings-page').isVisible(),'mobile settings page opens directly');assert(await m.locator('.settings-account').isVisible(),'mobile account section is inline and visible');assert(await m.locator('[data-profile-save]').isVisible(),'mobile profile-save action is directly reachable');assert(await m.locator('#importBackup').isVisible(),'mobile restore file input is directly reachable');assert(merr.length===0,`mobile runtime errors = 0 (${merr.join(' | ')})`);await mobile.close();

  const cloudMobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true});const cm=await cloudMobile.newPage(),cmerr=await errors(cm);await cm.goto('http://127.0.0.1:4173/v9/preview.html',{waitUntil:'domcontentloaded'});await cm.waitForSelector('.mobile-nav');await cm.locator('.mobile-nav [data-go="settings"]').click();await cm.waitForSelector('.settings-page');assert(await cm.locator('.settings-account [data-signin]').isVisible(),'cloud-enabled mobile settings exposes sign-in directly');assert(await cm.locator('.settings-account [data-signup]').isVisible(),'cloud-enabled mobile settings exposes sign-up directly');assert(await cm.locator('.settings-account [data-resend-confirmation]').isVisible(),'cloud-enabled mobile settings exposes confirmation resend directly');await noX(cm,'cloud-enabled mobile settings');assert(cmerr.length===0,`cloud-enabled mobile runtime errors = 0 (${cmerr.join(' | ')})`);await cloudMobile.close();

  const migration=await browser.newContext({viewport:{width:1024,height:768}});await migration.addInitScript(()=>{if(location.protocol==='http:'){localStorage.setItem('rescue6:profile',JSON.stringify({examYear:'2031',daily:55,level:'재도전'}));localStorage.setItem('rescue6:notes',JSON.stringify([{id:'legacy-note',title:'기존노트',text:'이전 기록'}]))}});const g=await migration.newPage();await g.goto(base,{waitUntil:'domcontentloaded'});await g.waitForSelector('.app');const mig=await g.evaluate(()=>({year:window.AITUTOR_V9.Store.state.profile.examYear,notes:window.AITUTOR_V9.Store.state.notes.map(x=>x.id),legacyStill:localStorage.getItem('rescue6:notes')!==null,guest:window.AITUTOR_V9.Auth.isGuest}));assert(mig.year==='2031'&&mig.notes.includes('legacy-note'),'v8 guest study data migrates into v9 namespace');assert(mig.legacyStill&&mig.guest,'legacy source remains intact and migration stays guest-local before sign-in');await migration.close();
  console.log('V9_BROWSER_QA_SUCCESS');
} finally {await browser.close()}
