'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{};const day=86400000;const clamp=n=>Math.max(0,Math.min(100,n));
const delta=(correct,confidence,responseMs)=>{let d=correct?({sure:12,maybe:9,none:6}[confidence]||7):({sure:-22,maybe:-14,none:-8}[confidence]||-10);if(correct&&responseMs&&responseMs<15000)d+=1;if(correct&&responseMs&&responseMs>120000)d-=2;return d};
const intervalFor=mastery=>mastery>=90?30:mastery>=75?14:mastery>=60?7:mastery>=40?3:1;
function ensure(conceptId){const s=V.Store.state;return s.progress[conceptId]||(s.progress[conceptId]={conceptId,mastery:35,attempts:0,correct:0,streak:0,dangerousWrong:0,lastStudy:0,lastCorrect:0,nextReview:0})}
function schedule(conceptId,correct){const s=V.Store.state,p=ensure(conceptId);const days=correct?intervalFor(p.mastery):0;p.nextReview=correct?Date.now()+days*day:Date.now();s.reviewSchedule[conceptId]={conceptId,due:p.nextReview,intervalDays:days,mastery:p.mastery,updatedAt:Date.now()}}
function recordAnswer(question,choice,confidence='none',responseMs=null){if(!question)return null;const s=V.Store.state,correct=Number(choice)===question.a,p=ensure(question.conceptId);p.attempts++;if(correct){p.correct++;p.streak++;p.lastCorrect=Date.now()}else{p.streak=0;if(confidence==='sure')p.dangerousWrong=(p.dangerousWrong||0)+1}p.mastery=clamp((p.mastery||35)+delta(correct,confidence,responseMs));p.lastStudy=Date.now();schedule(question.conceptId,correct);s.answers[question.id]=Number(choice);s.confidence[question.id]=confidence;const event={eventId:crypto.randomUUID?crypto.randomUUID():'evt-'+Date.now()+'-'+Math.random(),questionId:question.id,conceptId:question.conceptId,scopeId:question.scopeId,subject:question.subject,correct,choice:Number(choice),confidence,responseMs,at:Date.now()};s.answerEvents.push(event);let w=s.wrongs.find(x=>x.questionId===question.id&&!x.resolved);if(!correct){if(!w){w={id:crypto.randomUUID?crypto.randomUUID():'w-'+Date.now(),questionId:question.id,conceptId:question.conceptId,scopeId:question.scopeId,confidence,due:Date.now(),intervalDays:0,resolved:false,createdAt:Date.now(),lastWrongAt:Date.now(),wrongCount:1};s.wrongs.push(w)}else{w.confidence=confidence;w.due=Date.now();w.lastWrongAt=Date.now();w.wrongCount=(w.wrongCount||1)+1}}else if(w){w.resolved=true;w.resolvedAt=Date.now()}V.Store.save();return{correct,event,progress:p}}
function markReviewed(conceptId,quality='good'){const p=ensure(conceptId),s=V.Store.state;if(quality==='again')p.mastery=clamp(p.mastery-8);if(quality==='good')p.mastery=clamp(p.mastery+4);if(quality==='easy')p.mastery=clamp(p.mastery+7);const days=quality==='again'?0:quality==='easy'?Math.max(7,intervalFor(p.mastery)):intervalFor(p.mastery);p.nextReview=days?Date.now()+days*day:Date.now();s.reviewSchedule[conceptId]={conceptId,due:p.nextReview,intervalDays:days,mastery:p.mastery,updatedAt:Date.now()};V.Store.save();return p}
function statsFor(id){const p=V.Store.state.progress[id]||{mastery:0,attempts:0,correct:0,dangerousWrong:0,lastStudy:0,nextReview:0};return{...p,accuracy:p.attempts?Math.round(p.correct/p.attempts*100):null,overdue:!!p.nextReview&&p.nextReview<=Date.now(),questions:V.questionsForConcept?.(id)?.length||0}}
function todayPlan(limit=8){const s=V.Store.state;return V.curriculum.concepts.map(c=>{const p=statsFor(c.id),w=s.wrongs.filter(x=>!x.resolved&&x.conceptId===c.id),danger=w.filter(x=>x.confidence==='sure').length;let score=0,reason='신규 학습';if(danger){score+=120+danger*10;reason='확신 오답'}if(p.overdue){score+=90;reason=danger?reason+' + 복습지연':'복습 예정'}if(p.attempts&&p.mastery<60){score+=60-p.mastery;reason=reason==='신규 학습'?'취약개념':reason}if(!p.attempts)score+=18;score+=Math.min(20,w.length*5);return{concept:c,progress:p,wrong:w.length,danger,score,reason}}).sort((a,b)=>b.score-a.score||a.concept.id.localeCompare(b.concept.id)).slice(0,limit)}
function readiness(){const cs=V.curriculum.concepts,s=V.Store.state,studied=cs.filter(c=>(s.progress[c.id]?.attempts||0)>0),covered=studied.length,questionConcepts=new Set(V.questions.filter(q=>q.grade==='A'||q.grade==='B').map(q=>q.conceptId)),retention=studied.length?Math.round(studied.reduce((a,c)=>a+(s.progress[c.id]?.mastery||0),0)/studied.length):0,dangerous=s.wrongs.filter(w=>!w.resolved&&w.confidence==='sure').length,overdue=Object.values(s.reviewSchedule).filter(r=>r.due<=Date.now()).length,mock=V.examReadiness();return{scopeCoverage:Math.round(covered/cs.length*100),covered,total:cs.length,verifiedQuestionCoverage:Math.round(questionConcepts.size/cs.length*100),questionConcepts:questionConcepts.size,retention,dangerous,overdue,mock}}
function conceptPriority(id){return todayPlan(135).findIndex(x=>x.concept.id===id)}
V.Mastery={ensure,recordAnswer,markReviewed,statsFor,todayPlan,readiness,conceptPriority,intervalFor};
})();
