'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{},day=86400000,clamp=n=>Math.max(0,Math.min(100,n));
const delta=(o,f,r)=>{let d=o?({sure:12,maybe:9,none:6}[f]||7):({sure:-22,maybe:-14,none:-8}[f]||-10);if(o&&r&&r<15000)d++;if(o&&r&&r>120000)d-=2;return d};
const intervalFor=mastery=>mastery>=90?30:mastery>=75?14:mastery>=60?7:mastery>=40?3:1;
const defaults=id=>({conceptId:id,mastery:35,attempts:0,correct:0,streak:0,dangerousWrong:0,lapses:0,reviews:0,lastStudy:0,lastCorrect:0,nextReview:0,lastIntervalDays:0});
function ensure(id){const s=V.Store.state,p=s.progress[id]||(s.progress[id]=defaults(id));for(const[k,v]of Object.entries(defaults(id)))if(p[k]===undefined)p[k]=v;return p}
function nextInterval(p,f='none',q='answer'){const b=intervalFor(p.mastery),s=Math.min(1.8,1+Math.max(0,(p.streak||0)-1)*.15),c=q==='easy'?1.25:q==='good'?1.05:f==='sure'?1.15:f==='maybe'?1:.8,l=1/(1+Math.min(4,p.lapses||0)*.08);return Math.max(1,Math.min(45,Math.round(b*s*c*l)))}
function schedule(id,ok,f='none',q='answer'){const s=V.Store.state,p=ensure(id),d=ok?nextInterval(p,f,q):0,n=Date.now();p.lastIntervalDays=d;p.nextReview=ok?n+d*day:n;s.reviewSchedule[id]={conceptId:id,due:p.nextReview,intervalDays:d,mastery:p.mastery,updatedAt:n,version:'v2'};return d}
function requiredRecoveries(w){return(w?.wrongCount||0)>=2||w?.confidence==='sure'?2:1}
function recordAnswer(q,c,f='none',r=null){if(!q)return null;const s=V.Store.state,correct=Number(c)===q.a,p=ensure(q.conceptId),now=Date.now();p.attempts++;if(correct){p.correct++;p.streak++;p.lastCorrect=now}else{p.streak=0;p.lapses=(p.lapses||0)+1;if(f==='sure')p.dangerousWrong=(p.dangerousWrong||0)+1}p.mastery=clamp((p.mastery||35)+delta(correct,f,r));p.lastStudy=now;const intervalDays=schedule(q.conceptId,correct,f,'answer');s.answers[q.id]=Number(c);s.confidence[q.id]=f;const event={eventId:crypto.randomUUID?crypto.randomUUID():'evt-'+now+'-'+Math.random(),questionId:q.id,conceptId:q.conceptId,scopeId:q.scopeId,subject:q.subject,correct,choice:Number(c),confidence:f,responseMs:r,intervalDays,at:now};s.answerEvents.push(event);let w=s.wrongs.find(x=>x.questionId===q.id&&!x.resolved);if(!correct){if(!w){w={id:crypto.randomUUID?crypto.randomUUID():'w-'+now,questionId:q.id,conceptId:q.conceptId,scopeId:q.scopeId,confidence:f,due:now,intervalDays:0,resolved:false,createdAt:now,lastWrongAt:now,wrongCount:1,recoveryCorrect:0,requiredRecoveries:f==='sure'?2:1};s.wrongs.push(w)}else{w.confidence=f;w.due=now;w.lastWrongAt=now;w.wrongCount=(w.wrongCount||1)+1;w.recoveryCorrect=0;w.requiredRecoveries=requiredRecoveries(w)}}else if(w){w.recoveryCorrect=(w.recoveryCorrect||0)+1;w.requiredRecoveries=requiredRecoveries(w);if(w.recoveryCorrect>=w.requiredRecoveries){w.resolved=true;w.resolvedAt=now}else w.due=now+day}V.Store.save();return{correct,event,progress:p,wrong:w||null}}
function markReviewed(id,q='good'){const p=ensure(id),s=V.Store.state,n=Date.now();p.reviews=(p.reviews||0)+1;p.lastStudy=n;if(q==='again'){p.mastery=clamp(p.mastery-8);p.streak=0;p.lapses=(p.lapses||0)+1}else if(q==='good'){p.mastery=clamp(p.mastery+4);p.streak=(p.streak||0)+1}else if(q==='easy'){p.mastery=clamp(p.mastery+7);p.streak=(p.streak||0)+1}schedule(id,q!=='again',q==='easy'?'sure':q==='good'?'maybe':'none',q);V.Store.save();return p}
function statsFor(id){const r=V.Store.state.progress[id],p=r?{...defaults(id),...r}:{...defaults(id),mastery:0},n=Date.now(),accuracy=p.attempts?Math.round(p.correct/p.attempts*100):null,ageDays=p.lastStudy?Math.max(0,(n-p.lastStudy)/day):null,overdueDays=p.nextReview?Math.max(0,(n-p.nextReview)/day):0;let retentionEstimate=p.attempts?p.mastery:0;if(p.attempts&&p.lastStudy&&p.lastIntervalDays>0){const x=ageDays/Math.max(1,p.lastIntervalDays);retentionEstimate=Math.round(clamp(p.mastery*Math.exp(-.35*Math.max(0,x-1))))}return{...p,accuracy,ageDays,overdueDays,retentionEstimate,overdue:!!p.nextReview&&p.nextReview<=n,questions:V.questionsForConcept?.(id)?.length||0}}
function riskFor(id){const s=V.Store.state,p=statsFor(id),w=s.wrongs.filter(x=>!x.resolved&&x.conceptId===id),d=w.filter(x=>x.confidence==='sure').length;let score=0;const r=[];if(d){score+=160+d*15;r.push('확신 오답')}if(w.length){score+=Math.min(80,w.length*16);r.push('오답 복구')}if(p.overdue){score+=100+Math.min(80,Math.ceil(p.overdueDays)*8);r.push('복습 지연')}if(p.attempts&&p.mastery<60){score+=80-p.mastery;r.push('취약개념')}if(p.attempts>=3&&p.accuracy<70){score+=Math.round((70-p.accuracy)*.8);r.push('정답률 보강')}if(p.lapses)score+=Math.min(30,p.lapses*5);if(!p.attempts){score+=20;r.push('신규 학습')}if(p.ageDays!=null&&p.ageDays>30){score+=Math.min(30,Math.round((p.ageDays-30)/3));r.push('장기 미학습')}return{score,reason:r.slice(0,2).join(' + ')||'신규 학습',wrong:w.length,danger:d,progress:p}}
function examPhase(){const m=V.OfficialMonitor119?.summary?.()||{},y=+(m.targetExamYear||V.Store.state.profile?.examYear||0),x=(m.items||[]).filter(x=>x?.schedule?.writtenExam&&(x.targetYearMatch===true||y&&(+x.noticeYear===y||+x.explicitYear===y))).sort((a,b)=>(a.changeState==='updated'?-1:0)-(b.changeState==='updated'?-1:0)||({change_notice:1,exam_schedule:2,recruitment_notice:3}[a.kind]||4)-({change_notice:1,exam_schedule:2,recruitment_notice:3}[b.kind]||4)||String(b.publishedAt||'').localeCompare(String(a.publishedAt||'')))[0],s=String(x?.schedule?.writtenExam||''),a=s.match(/^(20\d{2})-(\d{2})-(\d{2})$/);if(!a)return{phase:'normal',daysLeft:null,writtenExam:''};const t=Date.UTC(+a[1],+a[2]-1,+a[3]),d=new Date(t);if(d.getUTCFullYear()!=+a[1]||d.getUTCMonth()!=+a[2]-1||d.getUTCDate()!=+a[3])return{phase:'normal',daysLeft:null,writtenExam:''};const k=new Date(Date.now()+324e5),n=Date.UTC(k.getUTCFullYear(),k.getUTCMonth(),k.getUTCDate()),z=Math.round((t-n)/day);return{phase:z<0?'normal':z<=1?'D1':z<=7?'D7':z<=30?'D30':'normal',daysLeft:z,writtenExam:s}}
function todayPlan(limit=8){const exam=examPhase(),weight={D1:3,D7:2,D30:1}[exam.phase]||0;return V.curriculum.concepts.map(concept=>{const risk=riskFor(concept.id),p=risk.progress,phaseBoost=weight*((risk.danger?40:0)+(risk.wrong?30:0)+(p.overdue?25:0)+(p.attempts?Math.max(0,70-p.retentionEstimate):exam.phase==='D1'?-20:15));return{concept,...risk,score:risk.score+phaseBoost,phaseBoost,examPhase:exam.phase}}).sort((a,b)=>b.score-a.score||(a.progress.lastStudy||0)-(b.progress.lastStudy||0)||a.concept.id.localeCompare(b.concept.id)).slice(0,limit)}
function readiness(){const cs=V.curriculum.concepts,s=V.Store.state,studied=cs.filter(c=>(s.progress[c.id]?.attempts||0)>0),covered=studied.length,questionConcepts=new Set(V.questions.filter(q=>q.grade==='A'||q.grade==='B').map(q=>q.conceptId)),retention=studied.length?Math.round(studied.reduce((a,c)=>a+statsFor(c.id).retentionEstimate,0)/studied.length):0,dangerous=s.wrongs.filter(w=>!w.resolved&&w.confidence==='sure').length,recoveryPending=s.wrongs.filter(w=>!w.resolved&&(w.recoveryCorrect||0)<requiredRecoveries(w)).length,overdue=Object.values(s.reviewSchedule).filter(r=>r.due<=Date.now()).length,mock=V.examReadiness(),exam=examPhase();return{scopeCoverage:Math.round(covered/cs.length*100),covered,total:cs.length,verifiedQuestionCoverage:Math.round(questionConcepts.size/cs.length*100),questionConcepts:questionConcepts.size,retention,dangerous,recoveryPending,overdue,mock,examPhase:exam.phase,examDaysLeft:exam.daysLeft}}
function conceptPriority(id){return todayPlan(V.curriculum.concepts.length).findIndex(x=>x.concept.id===id)}
V.Mastery={version:'119-mastery-v2',ensure,recordAnswer,markReviewed,statsFor,todayPlan,readiness,conceptPriority,intervalFor,riskFor,requiredRecoveries,examPhase};
})();