'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{};const DB='aitutor-v9-private-docs',VER=1;let dbp=null;
function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('docs')){const s=d.createObjectStore('docs',{keyPath:'id'});s.createIndex('owner','ownerId');s.createIndex('kind','kind')}if(!d.objectStoreNames.contains('chunks')){const s=d.createObjectStore('chunks',{keyPath:'id'});s.createIndex('owner','ownerId');s.createIndex('doc','docId')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
const txDone=t=>new Promise((res,rej)=>{t.oncomplete=()=>res();t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error)});
const uuid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function tokens(s){return [...new Set(String(s||'').toLowerCase().replace(/[^0-9a-z가-힣 ]/g,' ').split(/\s+/).filter(x=>x.length>1))]}
function tombstones(){const s=V.Store.state;return s.deletedDocuments||(s.deletedDocuments={})}
async function putDocument(doc,chunks){const d=await db(),t=d.transaction(['docs','chunks'],'readwrite');t.objectStore('docs').put(doc);for(const c of chunks)t.objectStore('chunks').put(c);await txDone(t);return doc}
async function listDocuments(kind){const d=await db(),owner=V.Store.ownerId,t=d.transaction('docs','readonly'),idx=t.objectStore('docs').index('owner'),req=idx.getAll(owner);const rows=await new Promise((res,rej)=>{req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)});return kind?rows.filter(x=>x.kind===kind):rows}
async function chunksFor(docId){const d=await db(),t=d.transaction('chunks','readonly'),req=t.objectStore('chunks').index('doc').getAll(docId);return await new Promise((res,rej)=>{req.onsuccess=()=>res((req.result||[]).filter(x=>x.ownerId===V.Store.ownerId));req.onerror=()=>rej(req.error)})}
async function purge(docId){const d=await db(),chunks=await chunksFor(docId),t=d.transaction(['docs','chunks'],'readwrite');t.objectStore('docs').delete(docId);for(const c of chunks)t.objectStore('chunks').delete(c.id);await txDone(t)}
async function remove(docId){await purge(docId);tombstones()[docId]=Date.now();V.Store.save()}
async function createOcrWorker(){const T=await import('https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.esm.min.js');const create=T.createWorker||T.default?.createWorker||window.Tesseract?.createWorker;if(!create)throw Error('OCR_ENGINE_UNAVAILABLE');return create('kor+eng')}
async function ocrPdfPage(pg,worker){const base=pg.getViewport({scale:1}),maxWidth=1800,scale=Math.min(2,Math.max(1.35,maxWidth/base.width)),viewport=pg.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);await pg.render({canvasContext:ctx,viewport}).promise;const r=await worker.recognize(canvas);canvas.width=1;canvas.height=1;return String(r.data?.text||'').replace(/\s+/g,' ').trim()}
function pdfPageNeedsOcr(tc,text){const visible=(tc?.items||[]).filter(x=>String(x?.str||'').trim()).length,compact=String(text||'').replace(/\s+/g,'').length;return visible===0||compact===0}
async function pdfText(file,onProgress){const p=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.worker.min.mjs';const task=p.getDocument({data:await file.arrayBuffer()}),pdf=await task.promise,out=[];let worker=null;try{for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i),tc=await pg.getTextContent();let text=tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim(),ocr=false;if(pdfPageNeedsOcr(tc,text)){worker=worker||await createOcrWorker();text=await ocrPdfPage(pg,worker);ocr=true}out.push({page:i,text,ocr});onProgress?.(i,pdf.numPages,ocr?'ocr':'text')}}finally{if(worker)await worker.terminate().catch(()=>{});await task.destroy?.().catch?.(()=>{})}return out}
async function imageText(file,onProgress){onProgress?.(0,1,'ocr');const worker=await createOcrWorker();try{const r=await worker.recognize(file);onProgress?.(1,1,'ocr');return[{page:1,text:r.data.text||'',ocr:true}]}finally{await worker.terminate().catch(()=>{})}}
async function ingest(file,{kind='personal',title='',keepOriginal=false,onProgress}={}){if(!file)throw Error('FILE_REQUIRED');let pages=[];if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))pages=await pdfText(file,onProgress);else if(file.type?.startsWith('image/'))pages=await imageText(file,onProgress);else pages=[{page:1,text:await file.text(),ocr:false}];const extractedChars=pages.reduce((n,p)=>n+String(p.text||'').trim().length,0);if(!extractedChars)throw Error('NO_TEXT_EXTRACTED');const now=Date.now(),docId=uuid(),ownerId=V.Store.ownerId,doc={id:docId,ownerId,kind,title:title||file.name,fileName:file.name,mime:file.type||'',pageCount:pages.length,extractedChars,ocrPages:pages.filter(p=>p.ocr).map(p=>p.page),private:kind==='personal',createdAt:now,updatedAt:now,original:keepOriginal?file:null};const chunks=[];for(const p of pages){const text=(p.text||'').trim();if(!text)continue;const size=1300;for(let i=0;i<text.length;i+=size){chunks.push({id:`${docId}:${p.page}:${i}`,docId,ownerId,kind,page:p.page,chunkIndex:Math.floor(i/size),text:text.slice(i,i+size),tokenSet:tokens(text.slice(i,i+size))})}}await putDocument(doc,chunks);delete tombstones()[docId];V.Store.save();return{doc,chunks:chunks.length,extractedChars,ocrPages:doc.ocrPages}}
async function search(query,{kind,limit=8}={}){const qs=tokens(query);if(!qs.length)return[];const docs=await listDocuments(kind),docIds=new Set(docs.map(x=>x.id)),d=await db(),t=d.transaction('chunks','readonly'),req=t.objectStore('chunks').index('owner').getAll(V.Store.ownerId);const rows=await new Promise((res,rej)=>{req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)});return rows.filter(x=>docIds.has(x.docId)&&(!kind||x.kind===kind)).map(x=>{let score=0;for(const q of qs)if((x.tokenSet||[]).some(t=>t.includes(q)||q.includes(t)))score+=q.length;return{...x,score,doc:docs.find(d=>d.id===x.docId)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
async function privateGrounding(query,limit=5){const hits=await search(query,{kind:'personal',limit});return hits.map(h=>`[내 개인자료 · ${h.doc.title} · ${h.page}쪽]\n${h.text.slice(0,900)}`).join('\n\n')}
async function exportForSync(){const ownerId=V.Store.ownerId,docs=await listDocuments('personal'),outDocs=[],outChunks=[];for(const d of docs){const {original,...safe}=d;outDocs.push({...safe,ownerId,private:true,original:undefined});for(const c of await chunksFor(d.id))outChunks.push({...c,ownerId,kind:'personal'})}const deleted=Object.entries(tombstones()).map(([id,deletedAt])=>({id,ownerId,deletedAt:Number(deletedAt)||Date.now()}));return{ownerId,docs:outDocs,chunks:outChunks,deleted}}
async function importFromSync(remoteDocs=[],remoteChunks=[]){const ownerId=V.Store.ownerId,owned=(remoteDocs||[]).filter(x=>x&&x.ownerId===ownerId),deleted=owned.filter(x=>Number(x.deletedAt)>0),live=owned.filter(x=>!Number(x.deletedAt)),local=new Map((await listDocuments()).map(x=>[x.id,x])),ts=tombstones();let deletedCount=0;for(const row of deleted){const when=Number(row.deletedAt)||0,prev=local.get(row.id),localStamp=Math.max(Number(prev?.updatedAt||prev?.createdAt||0),Number(ts[row.id]||0));if(when<localStamp)continue;await purge(row.id);ts[row.id]=when;local.delete(row.id);deletedCount++}const allowed=new Set(live.map(x=>x.id));if(!live.length){V.Store.save();return{docs:0,chunks:0,deleted:deletedCount}}const accepted=new Set(),d=await db(),t=d.transaction(['docs','chunks'],'readwrite'),docStore=t.objectStore('docs'),chunkStore=t.objectStore('chunks');for(const row of live){const prev=local.get(row.id),remoteStamp=Number(row.updatedAt||row.createdAt||0),localStamp=Math.max(Number(prev?.updatedAt||prev?.createdAt||0),Number(ts[row.id]||0));if(localStamp>remoteStamp)continue;accepted.add(row.id);delete ts[row.id];const clean={...row,ownerId,kind:'personal',private:true,original:null,deletedAt:0};docStore.put(clean)}let chunkCount=0;for(const row of remoteChunks||[]){if(!row||row.ownerId!==ownerId||!allowed.has(row.docId)||(!accepted.has(row.docId)&&local.has(row.docId)))continue;chunkStore.put({...row,ownerId,kind:'personal',tokenSet:row.tokenSet||tokens(row.text)});chunkCount++}await txDone(t);V.Store.save();return{docs:accepted.size,chunks:chunkCount,deleted:deletedCount}}
V.PrivateDocs={db,ingest,listDocuments,chunksFor,remove,search,privateGrounding,exportForSync,importFromSync,pdfPageNeedsOcr,privacyRules:{defaultPrivate:true,serverUpload:false,extractedTextCloudSync:'manual-member-sync',originalCloudSyncOptIn:true,crossUserSharing:false,deletionTombstones:true}};
})();
