'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{};const DB='aitutor-v9-private-docs',VER=1;let dbp=null;
function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('docs')){const s=d.createObjectStore('docs',{keyPath:'id'});s.createIndex('owner','ownerId');s.createIndex('kind','kind')}if(!d.objectStoreNames.contains('chunks')){const s=d.createObjectStore('chunks',{keyPath:'id'});s.createIndex('owner','ownerId');s.createIndex('doc','docId')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
const txDone=t=>new Promise((res,rej)=>{t.oncomplete=()=>res();t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error)});
const uuid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function tokens(s){return [...new Set(String(s||'').toLowerCase().replace(/[^0-9a-z가-힣 ]/g,' ').split(/\s+/).filter(x=>x.length>1))]}
async function putDocument(doc,chunks){const d=await db(),t=d.transaction(['docs','chunks'],'readwrite');t.objectStore('docs').put(doc);for(const c of chunks)t.objectStore('chunks').put(c);await txDone(t);return doc}
async function listDocuments(kind){const d=await db(),owner=V.Store.ownerId,t=d.transaction('docs','readonly'),idx=t.objectStore('docs').index('owner'),req=idx.getAll(owner);const rows=await new Promise((res,rej)=>{req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)});return kind?rows.filter(x=>x.kind===kind):rows}
async function chunksFor(docId){const d=await db(),t=d.transaction('chunks','readonly'),req=t.objectStore('chunks').index('doc').getAll(docId);return await new Promise((res,rej)=>{req.onsuccess=()=>res((req.result||[]).filter(x=>x.ownerId===V.Store.ownerId));req.onerror=()=>rej(req.error)})}
async function remove(docId){const d=await db(),chunks=await chunksFor(docId),t=d.transaction(['docs','chunks'],'readwrite');t.objectStore('docs').delete(docId);for(const c of chunks)t.objectStore('chunks').delete(c.id);await txDone(t)}
async function pdfText(file,onProgress){const p=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.min.mjs');p.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.worker.min.mjs';const pdf=await p.getDocument({data:await file.arrayBuffer()}).promise,out=[];for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i),tc=await pg.getTextContent(),text=tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim();out.push({page:i,text});onProgress?.(i,pdf.numPages)}return out}
async function imageText(file,onProgress){onProgress?.(0,1);let T=await import('https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.esm.min.js');const create=T.createWorker||T.default?.createWorker||window.Tesseract?.createWorker;if(!create)throw Error('OCR_ENGINE_UNAVAILABLE');const worker=await create('kor+eng');const r=await worker.recognize(file);await worker.terminate();onProgress?.(1,1);return[{page:1,text:r.data.text||''}]}
async function ingest(file,{kind='personal',title='',keepOriginal=false,onProgress}={}){if(!file)throw Error('FILE_REQUIRED');let pages=[];if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))pages=await pdfText(file,onProgress);else if(file.type?.startsWith('image/'))pages=await imageText(file,onProgress);else pages=[{page:1,text:await file.text()}];const docId=uuid(),ownerId=V.Store.ownerId,doc={id:docId,ownerId,kind,title:title||file.name,fileName:file.name,mime:file.type||'',pageCount:pages.length,private:kind==='personal',createdAt:Date.now(),original:keepOriginal?file:null};const chunks=[];for(const p of pages){const text=(p.text||'').trim();if(!text)continue;const size=1300;for(let i=0;i<text.length;i+=size){chunks.push({id:`${docId}:${p.page}:${i}`,docId,ownerId,kind,page:p.page,text:text.slice(i,i+size),tokenSet:tokens(text.slice(i,i+size))})}}await putDocument(doc,chunks);return{doc,chunks:chunks.length}}
async function search(query,{kind,limit=8}={}){const qs=tokens(query);if(!qs.length)return[];const docs=await listDocuments(kind),docIds=new Set(docs.map(x=>x.id)),d=await db(),t=d.transaction('chunks','readonly'),req=t.objectStore('chunks').index('owner').getAll(V.Store.ownerId);const rows=await new Promise((res,rej)=>{req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)});return rows.filter(x=>docIds.has(x.docId)&&(!kind||x.kind===kind)).map(x=>{let score=0;for(const q of qs)if((x.tokenSet||[]).some(t=>t.includes(q)||q.includes(t)))score+=q.length;return{...x,score,doc:docs.find(d=>d.id===x.docId)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
async function privateGrounding(query,limit=5){const hits=await search(query,{kind:'personal',limit});return hits.map(h=>`[내 개인자료 · ${h.doc.title} · ${h.page}쪽]\n${h.text.slice(0,900)}`).join('\n\n')}
V.PrivateDocs={db,ingest,listDocuments,chunksFor,remove,search,privateGrounding,privacyRules:{defaultPrivate:true,serverUpload:false,originalCloudSyncOptIn:true,crossUserSharing:false}};
})();
