'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{};
const Q=[
{id:'a-fire-scope-1',grade:'A',subject:'fire',scopeId:'F01',conceptId:'F01-C01',q:'소방학개론의 공식 상위 출제범위에 포함되는 것은?',choices:['소방조직','산부인과','소아','기본소생술'],a:0,ex:'소방학개론의 공식 상위 범위에는 소방조직이 포함됩니다.',source:'소방공무원 임용령'},
{id:'a-fire-scope-2',grade:'A',subject:'fire',scopeId:'F02',conceptId:'F02-C01',q:'소방학개론의 공식 상위 출제범위에 포함되는 것은?',choices:['응급의료 개론','재난관리','중독','행동응급'],a:1,ex:'소방학개론의 공식 상위 범위에는 재난관리가 포함됩니다.',source:'소방공무원 임용령'},
{id:'a-fire-scope-3',grade:'A',subject:'fire',scopeId:'F03',conceptId:'F03-C01',q:'소방학개론의 공식 상위 출제범위에 포함되는 것은?',choices:['기도유지','연소·화재이론','환자평가','소아'],a:1,ex:'소방학개론의 공식 상위 범위에는 연소·화재이론이 포함됩니다.',source:'소방공무원 임용령'},
{id:'a-fire-scope-4',grade:'A',subject:'fire',scopeId:'F04',conceptId:'F04-C01',q:'소방학개론의 공식 상위 출제범위에 포함되는 것은?',choices:['소화이론','노인','환경응급','산부인과'],a:0,ex:'소방학개론의 공식 상위 범위에는 소화이론이 포함됩니다.',source:'소방공무원 임용령'},
{id:'a-exam-fire-count',grade:'A',subject:'fire',scopeId:'F01',conceptId:'F01-C01',q:'2026 구급 경채 필기에서 소방학개론 문항 수는?',choices:['20','25','40','65'],a:1,ex:'2026 시행계획상 소방학개론은 25문항입니다.',source:'2026 소방공무원 채용시험 시행계획 변경공고'},
{id:'a-exam-ems-count',grade:'A',subject:'ems',scopeId:'E01',conceptId:'E01-C01',q:'2026 구급 경채 필기에서 응급처치학개론 문항 수는?',choices:['20','25','40','65'],a:2,ex:'2026 시행계획상 응급처치학개론은 40문항입니다.',source:'2026 소방공무원 채용시험 시행계획 변경공고'},
{id:'a-exam-time',grade:'A',subject:'ems',scopeId:'E01',conceptId:'E01-C01',q:'2026 구급 경채 필기시험 총 시간은?',choices:['50분','60분','65분','75분'],a:2,ex:'2026 시행계획상 구급 경채 필기시험은 65분입니다.',source:'2026 소방공무원 채용시험 시행계획 변경공고'},
{id:'b-f01-org-1',grade:'B',subject:'fire',scopeId:'F01',conceptId:'F01-C01',q:'시·도에서 소방업무를 수행하기 위하여 시·도지사 직속으로 두는 조직은?',choices:['119안전센터','소방본부','의용소방대','한국소방안전원'],a:1,ex:'교재는 시·도에서 소방업무를 수행하기 위하여 시·도지사 직속으로 소방본부를 둔다고 설명합니다.',source:'소방법령2 · 소방기본법 42쪽'},
{id:'b-f01-org-2',grade:'B',subject:'fire',scopeId:'F01',conceptId:'F01-C01',q:'소방서장 소속으로 둘 수 있는 조직에 해당하는 것은?',choices:['119안전센터','중앙안전관리위원회','국가안전관리위원회','한국소방안전원'],a:0,ex:'교재는 소방서장 소속으로 119안전센터·119구조대·119구급대 등을 둘 수 있다고 제시합니다.',source:'소방법령2 · 소방기본법 46쪽'},
{id:'b-f02-disaster-1',grade:'B',subject:'fire',scopeId:'F02',conceptId:'F02-C01',q:'재난 및 안전관리 기본법상 재난관리의 의미로 맞는 것은?',choices:['재난의 예방·대비·대응·복구를 위하여 하는 모든 활동','재난 발생 후 복구만 하는 활동','자연재난만 예방하는 활동','통계 작성만을 위한 활동'],a:0,ex:'공식 교재는 재난관리를 예방·대비·대응·복구를 위하여 하는 모든 활동으로 정의합니다.',source:'소방법령5 · 재난 및 안전관리 기본법 510쪽'},
{id:'b-f02-disaster-2',grade:'B',subject:'fire',scopeId:'F02',conceptId:'F02-C01',q:'다음 중 사회재난의 예로 공식 교재가 제시하는 유형은?',choices:['화재·붕괴·폭발','태풍·홍수만','대설·한파만','지진만'],a:0,ex:'교재는 화재·붕괴·폭발·교통사고 등으로 인한 일정 규모 이상의 피해를 사회재난에 포함합니다.',source:'소방법령5 · 재난 및 안전관리 기본법 510쪽'},
{id:'b-f03-fire-1',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C01',q:'공식 교재의 화재 개념에 가장 부합하는 것은?',choices:['소화할 필요가 있는 연소현상 또는 사람의 의도에 반해 발생·확대된 화학적 폭발현상','사람의 의도와 무관하게 발생한 모든 연소현상과 물리적 파열현상을 일괄해 화재로 본다','연기나 열이 발생하면 소화 필요성이나 연소 여부와 관계없이 모두 화재로 분류한다','화학적 폭발은 제외하고 육안으로 불꽃이 확인되는 연소현상만 화재로 본다'],a:0,ex:'공식 교재는 소화 필요성이 있는 연소현상과 일정한 화학적 폭발현상을 화재의 범주로 설명합니다.',source:'소방전술1(화재1) 3쪽'},
{id:'b-f03-fire-2',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C01',q:'소화적응성에 따른 화재 분류 연결로 맞는 것은?',choices:['A급-일반화재','B급-금속화재','C급-유류화재','D급-전기화재'],a:0,ex:'교재는 A 일반, B 유류, C 전기, D 금속 화재로 설명합니다.',source:'소방전술1(화재1) 4쪽'},
{id:'b-f03-special-1',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C06',q:'백드래프트의 악화요인으로 교재가 강조하는 것은?',choices:['신선한 공기의 유입','냉각수의 증발','가연물 완전 제거','산소 농도 감소'],a:0,ex:'백드래프트는 산소가 부족한 공간에 신선한 공기가 유입될 때 폭발적 발화가 일어날 수 있습니다.',source:'소방전술1(화재1) 25~27쪽'},
{id:'b-f03-special-2',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C06',q:'백드래프트와 플래시오버 비교로 맞는 것은?',choices:['백드래프트는 폭발현상이고 플래시오버는 폭발로 분류하지 않는다','둘 다 반드시 폭굉이다','플래시오버는 산소부족 때문에만 생긴다','백드래프트는 열 집적만으로 발생한다'],a:0,ex:'공식 비교표는 백드래프트를 폭발현상, 플래시오버를 폭발이 아닌 현상으로 구분합니다.',source:'소방전술1(화재1) 26~27쪽'},
{id:'b-f03-special-3',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C06',q:'플래시오버의 대표적 전조현상으로 제시되는 것은?',choices:['롤오버','동결','응축','침전'],a:0,ex:'교재는 고온의 연기와 롤오버를 플래시오버의 대표적 전조로 제시합니다.',source:'소방전술1(화재1) 30~33쪽'},
{id:'b-f03-flow-1',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C07',q:'Flow Path 설명으로 가장 적절한 것은?',choices:['화점실의 열·연기가 압력이 더 낮은 개구부 쪽으로 이동하는 흐름','연기가 반드시 바닥으로만 이동하는 현상','소화약제가 배관을 따라 이동하는 현상','화염 없이 온도만 낮아지는 현상'],a:0,ex:'교재는 양압의 화점실에서 열·연기가 압력이 낮은 문·창문 등으로 이동하는 흐름으로 설명합니다.',source:'소방전술1(화재1) 33~34쪽'},
{id:'b-f03-explosion-1',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C08',q:'폭연과 폭굉의 전파속도 비교로 맞는 것은?',choices:['폭연은 음속보다 느리고 폭굉은 음속보다 빠르다','둘 다 항상 음속과 같다','폭연이 음속보다 빠르고 폭굉이 느리다','전파속도로는 구분하지 않는다'],a:0,ex:'공식 교재는 폭연을 음속보다 느린 전파, 폭굉을 음속보다 빠른 충격파 전파로 구분합니다.',source:'소방전술1(화재2) 352~353쪽'},
{id:'b-f03-explosion-2',grade:'B',subject:'fire',scopeId:'F03',conceptId:'F03-C08',q:'공식 교재가 구분한 폭발 영향 4가지 조합은?',choices:['압력·비산·열·지진','냉각·질식·제거·부촉매','예방·대비·대응·복구','압축·팽창·응축·증발'],a:0,ex:'폭발의 영향은 압력, 비산, 열, 지진으로 구분되어 설명됩니다.',source:'소방전술1(화재2) 350~351쪽'},
{id:'b-f04-ext-1',grade:'B',subject:'fire',scopeId:'F04',conceptId:'F04-C01',q:'연쇄반응을 지배하는 라디칼 반응을 억제하는 소화원리는?',choices:['부촉매소화','냉각소화','제거소화','유화소화'],a:0,ex:'부촉매소화는 화학적 연쇄반응을 차단하는 소화방법입니다.',source:'소방전술1(화재2) 184쪽'},
{id:'b-f04-ext-2',grade:'B',subject:'fire',scopeId:'F04',conceptId:'F04-C01',q:'가연물을 제거·격리하거나 공급을 차단하는 소화원리는?',choices:['제거소화','질식소화','냉각소화','부촉매소화'],a:0,ex:'제거소화는 가연물을 화원에서 격리하거나 공급을 차단하는 방식입니다.',source:'소방전술1(화재2) 183쪽'},
{id:'b-f04-powder-1',grade:'B',subject:'fire',scopeId:'F04',conceptId:'F04-C08',q:'제3종 분말 소화약제의 주성분과 적응화재 조합으로 맞는 것은?',choices:['제1인산암모늄 · A/B/C급','탄산수소나트륨 · A급만','탄산수소칼륨 · A급만','이산화탄소 · D급만'],a:0,ex:'제3종 분말은 제1인산암모늄을 주성분으로 하고 A·B·C급 화재에 적응합니다.',source:'소방전술1(화재2) 241쪽 · 표 2-16'},
{id:'b-f04-powder-2',grade:'B',subject:'fire',scopeId:'F04',conceptId:'F04-C08',q:'다음 중 ABC 분말에 해당하는 것은?',choices:['제3종 분말','제1종 분말','제2종 분말','제4종 분말'],a:0,ex:'교재는 제3종 분말을 ABC 분말로, 제1·2·4종을 BC 분말로 구분합니다.',source:'소방전술1(화재2) 241쪽'},
{id:'b-e01-ems-1',grade:'B',subject:'ems',scopeId:'E01',conceptId:'E01-C01',q:'응급의료서비스 체계에 대한 설명으로 맞는 것은?',choices:['응급상황에서 필요한 인력·장비 등을 효과적으로 조직하여 운영하는 체계','병원 내부 진료만을 뜻한다','구급차 운전만을 뜻한다','환자 발견 이전 단계만을 뜻한다'],a:0,ex:'공식 교재는 응급상황에서 환자를 치료하기 위한 인력·장비 등을 효과적으로 조직·운영하는 체계로 설명합니다.',source:'소방전술3(구급) 4쪽'},
{id:'b-e06-position-1',grade:'B',subject:'ems',scopeId:'E06',conceptId:'E06-C05',q:'공식 구급 교재에서 쇼크 환자 이송 자세로 제시하는 것은?',choices:['다리를 약 20~30cm 올린 바로누운 자세','항상 엎드린 자세','무조건 좌위','머리를 가장 높인 자세'],a:0,ex:'교재는 쇼크 환자 이송 시 다리를 약 20~30cm 올린 바로누운 자세를 제시합니다.',source:'소방전술3(구급) 102쪽'},
{id:'b-e11-arrest-1',grade:'B',subject:'ems',scopeId:'E11',conceptId:'E11-C03',q:'공식 교재가 설명하는 심장마비 환자의 대표 상태 조합은?',choices:['맥박 없음·호흡 없음·무의식','맥박 정상·호흡 정상·완전 의식','맥박만 증가·의식 명료','호흡만 빠르고 맥박 정상'],a:0,ex:'교재는 심장마비 환자에서 맥박과 호흡이 없고 무의식 상태가 나타난다고 설명합니다.',source:'소방전술3(구급) 205~206쪽'},
{id:'b-e12-abd-1',grade:'B',subject:'ems',scopeId:'E12',conceptId:'E12-C03',q:'급성 복통 환자 정보 수집에 교재가 제시하는 문진 방식은?',choices:['OPQRST와 SAMPLE','RACE와 PASS','START만','CAB만'],a:0,ex:'급성 복통 장의 학습목표에는 OPQRST와 SAMPLE을 이용한 정보 및 병력 수집이 포함됩니다.',source:'소방전술3(구급) 216쪽'},
{id:'b-e13-bleed-1',grade:'B',subject:'ems',scopeId:'E13',conceptId:'E13-C03',q:'동맥 출혈의 특징으로 가장 적절한 것은?',choices:['선홍색 혈액이 심박동에 맞춰 뿜어져 나올 수 있다','항상 검붉고 천천히 스며 나온다','지혈이 항상 매우 쉽다','찰과상에서만 발생한다'],a:0,ex:'교재는 동맥 출혈을 선홍색 혈액이 심박동에 맞춰 뿜어져 나올 수 있는 형태로 설명합니다.',source:'소방전술3(구급) 228쪽'},
{id:'b-e17-seizure-1',grade:'B',subject:'ems',scopeId:'E17',conceptId:'E17-C03',q:'경련 환자 응급처치로 적절한 것은?',choices:['입에 물건을 강제로 넣지 않고 신체를 억지로 구속하지 않는다','혀 보호를 위해 단단한 물건을 넣는다','사지를 강하게 고정한다','기도와 호흡 확인을 하지 않는다'],a:0,ex:'교재는 경련 환자의 입에 물건을 강제로 넣거나 신체를 억지로 구속하지 않도록 제시합니다.',source:'소방전술3(구급) 314쪽'},
{id:'b-e24-bls-1',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C01',q:'무반응 환자에서 기본소생술 초기 흐름으로 맞는 것은?',choices:['119 신고와 AED 요청으로 연결한다','먼저 10분간 기다린다','반드시 병력문진을 끝낸 뒤 신고한다','호흡이 비정상이어도 관찰만 한다'],a:0,ex:'교재는 무반응이면 즉시 119 신고와 AED 요청으로 연결하도록 제시합니다.',source:'소방전술3(구급) 404~406쪽'},
{id:'b-e24-bls-2',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C01',q:'의료제공자가 심정지 의심 환자의 호흡과 목동맥 맥박을 확인하는 시간 기준은?',choices:['5~10초 이내','30초 이상','1분 이상','시간 제한 없음'],a:0,ex:'교재는 의료제공자가 호흡과 맥박을 5~10초 이내에 확인하도록 제시합니다.',source:'소방전술3(구급) 406쪽'},
{id:'b-e24-airway-1',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C02',q:'머리·목·척추 손상이 의심되는 환자의 기도개방법으로 적절한 것은?',choices:['턱 밀어올리기법','과도한 머리젖힘','복부밀어내기만 시행','기도개방을 하지 않는다'],a:0,ex:'교재는 머리·목·척추 손상이 의심되면 턱 밀어올리기법을 사용하도록 설명합니다.',source:'소방전술3(구급) 409쪽'},
{id:'b-e24-breath-1',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C02',q:'기본소생술 인공호흡 권장으로 맞는 것은?',choices:['1회 약 1초씩 총 2회, 가슴 상승이 보일 정도','한 번에 10초씩 강하게','가슴 상승과 관계없이 최대량','항상 과환기를 유도'],a:0,ex:'교재는 1회 1초간 총 2회, 가슴 상승이 보일 정도로 시행하고 과환기를 피하도록 제시합니다.',source:'소방전술3(구급) 409쪽'},
{id:'b-e24-compress-1',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C03',q:'성인 가슴압박 속도 기준으로 맞는 것은?',choices:['분당 100~120회','분당 40~60회','분당 60~80회','분당 150회 이상'],a:0,ex:'교재는 성인 가슴압박 속도를 분당 100~120회로 제시합니다.',source:'소방전술3(구급) 407·412쪽'},
{id:'b-e24-compress-2',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C03',q:'성인 가슴압박 깊이로 교재가 제시하는 값은?',choices:['약 5cm','약 1cm','약 10cm','깊이는 고려하지 않음'],a:0,ex:'교재는 보통 체격의 성인에서 가슴압박 깊이를 약 5cm로 제시합니다.',source:'소방전술3(구급) 412쪽'},
{id:'b-e24-cpr-1',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C04',q:'성인 심폐소생술에서 가슴압박과 인공호흡 비율은?',choices:['30:2','15:1','5:1','10:2'],a:0,ex:'교재는 성인의 경우 구조자 수와 관계없이 30:2를 유지하도록 제시합니다.',source:'소방전술3(구급) 413~414쪽'},
{id:'b-e24-cpr-2',grade:'B',subject:'ems',scopeId:'E24',conceptId:'E24-C04',q:'필수 처치로 가슴압박 중단이 필요할 때 교재가 제시하는 원칙은?',choices:['10초 이상 중단하지 않도록 한다','1분 이상 중단한다','중단시간은 중요하지 않다','매 주기 30초 중단한다'],a:0,ex:'교재는 맥박확인·제세동 등으로 중단이 불가피해도 10초 이상 중단하지 않도록 제시합니다.',source:'소방전술3(구급) 413~414쪽'}
];
const norm=s=>String(s||'').toLowerCase().replace(/\s+/g,' ').trim();
const fingerprints=new Set();
V.questions=Q.filter(q=>{const fp=norm(q.q);if(fingerprints.has(fp))return false;fingerprints.add(fp);return q.choices.length===4&&Number.isInteger(q.a)&&q.a>=0&&q.a<q.choices.length&&new Set(q.choices.map(norm)).size===q.choices.length});
V.questionById=Object.fromEntries(V.questions.map(q=>[q.id,q]));
V.questionsForConcept=id=>V.questions.filter(q=>q.conceptId===id);
V.examReadiness=()=>{const verified=V.questions.filter(q=>q.grade==='A'||q.grade==='B');const fire=new Set(verified.filter(q=>q.subject==='fire').map(q=>q.id)).size,ems=new Set(verified.filter(q=>q.subject==='ems').map(q=>q.id)).size;return{fire,ems,ready:fire>=25&&ems>=40,fireNeed:Math.max(0,25-fire),emsNeed:Math.max(0,40-ems)}};
})();
