'use strict';
(()=>{
const V=window.AITUTOR_V9=window.AITUTOR_V9||{};if(!Array.isArray(V.questions))return;
const source='국가법령정보센터 · 119구조ㆍ구급에 관한 법률 및 시행령';
const Q=[
  {id:'119-law-ems-01',grade:'P',subject:'ems',scopeId:'E01',conceptId:'E01-C03',difficulty:'mid',type:'법령형',source,q:'119법 시행령상 구급대원 자격에 관한 설명으로 옳은 것은?',choices:['소방공무원이면 별도 자격 없이 모두 구급대원이 된다','의료인·1급·2급 응급구조사 또는 소방청 구급교육 이수자가 자격 대상이다','간호사는 구급대원이 될 수 없다','2급 응급구조사는 구급대원 자격 대상이 아니다'],a:1,choiceExplanations:['시행령은 소방공무원이라는 신분 외에 별도의 자격기준을 규정한다.','정답. 의료인, 1급·2급 응급구조사 또는 소방청 구급업무 교육 이수자가 자격 대상이다.','간호사를 포함한 의료인은 법령상 자격 대상에 포함될 수 있다.','시행령은 2급 응급구조사도 구급대원 자격 대상에 포함한다.']},
  {id:'119-law-ems-02',grade:'P',subject:'ems',scopeId:'E01',conceptId:'E01-C03',difficulty:'high',type:'예외형',source,q:'소방청장이 실시하는 구급업무 교육만 받은 구급대원의 업무범위로 옳은 것은?',choices:['모든 전문응급처치를 독자적으로 시행한다','구급차 운전과 구급에 관한 보조업무만 할 수 있다','의료기관에서 의사의 업무를 대신한다','1급 응급구조사와 법적으로 완전히 동일하다'],a:1,choiceExplanations:['교육 이수자에게 모든 전문응급처치를 독자 시행하도록 규정하지 않는다.','정답. 시행령은 해당 자격의 구급대원을 구급차 운전과 구급 보조업무로 제한한다.','구급대원 자격은 의료기관 의사 업무를 대체하는 자격이 아니다.','교육 이수자는 1급 응급구조사와 동일한 업무범위로 규정되지 않는다.']},
  {id:'119-law-ems-03',grade:'P',subject:'ems',scopeId:'E01',conceptId:'E01-C03',difficulty:'low',type:'법령형',source,q:'119법 시행령상 일반구급대의 설치 원칙으로 옳은 것은?',choices:['전국에 하나만 설치한다','소방서마다 원칙적으로 1개 대 이상 설치한다','병원마다 반드시 설치한다','시·도청 본청에만 설치한다'],a:1,choiceExplanations:['일반구급대를 전국 단일 조직으로 두는 규정이 아니다.','정답. 일반구급대는 원칙적으로 소방서마다 1개 대 이상 설치하도록 규정한다.','일반구급대는 병원 설치조직으로 규정되지 않는다.','시·도청 본청에만 설치하도록 제한한 규정이 아니다.']},
  {id:'119-law-ems-04',grade:'P',subject:'ems',scopeId:'E01',conceptId:'E01-C03',difficulty:'mid',type:'운영형',source,q:'119구급상황관리센터의 인력 운영에 관한 설명으로 옳은 것은?',choices:['자격과 무관한 인력만 배치한다','의료인 또는 1·2급 응급구조사 자격 인력을 배치해 24시간 근무체제를 유지한다','평일 낮에만 운영한다','구급차 운전면허만 있으면 자격요건이 충족된다'],a:1,choiceExplanations:['시행령은 구급상황관리센터에 자격을 갖춘 인력을 배치하도록 규정한다.','정답. 의료인 또는 1·2급 응급구조사 자격 인력을 배치해 24시간 근무체제를 유지한다.','시행령은 평일 주간만이 아니라 24시간 근무체제를 규정한다.','운전면허만으로 구급상황관리센터 자격요건을 충족한다고 규정하지 않는다.']},
  {id:'119-law-ems-05',grade:'P',subject:'ems',scopeId:'E01',conceptId:'E01-C03',difficulty:'high',type:'상황형',source,q:'비응급환자의 구급출동 요청을 거절할 수 있는 경우에 대한 설명으로 옳은 것은?',choices:['비응급으로 보이면 환자 상태 확인 없이 즉시 거절한다','병력·증상·주변상황을 종합적으로 평가해 응급 여부를 판단해야 한다','술을 마신 사람은 의식과 외상 여부와 관계없이 항상 거절한다','38℃ 이상 고열이 있는 감기환자도 예외 없이 거절한다'],a:1,choiceExplanations:['시행령은 상태 확인 없는 자동 거절이 아니라 종합적인 응급 여부 판단을 요구한다.','정답. 병력·증상·주변상황을 종합적으로 평가해 응급 여부를 판단하도록 규정한다.','음주자라도 강한 자극에 의식이 회복되지 않거나 외상이 있으면 단순 거절 대상 예외가 된다.','단순 감기환자라도 38℃ 이상 고열 또는 호흡곤란이 있으면 거절 대상 예외가 된다.']},
  {id:'119-law-ems-06',grade:'P',subject:'ems',scopeId:'E01',conceptId:'E01-C03',difficulty:'mid',type:'비교형',source,q:'119법상 항공구조구급대의 운영 목적에 가장 가까운 것은?',choices:['일반 행정문서 운송만 담당한다','초고층 등 인명구조와 도서·벽지 응급환자의 긴급 이송을 지원한다','소방시설 점검만 담당한다','병원 내 입원환자 이동만 담당한다'],a:1,choiceExplanations:['항공구조구급대의 법정 목적을 일반 행정문서 운송으로 규정하지 않는다.','정답. 초고층 등에서의 인명구조와 도서·벽지 응급환자의 의료기관 긴급 이송이 핵심 목적이다.','소방시설 점검 전담 조직으로 규정된 것이 아니다.','병원 내부 환자 이동만을 담당하는 조직이 아니다.']}
];
const seenId=new Set(V.questions.map(x=>x.id)),seenText=new Set(V.questions.map(x=>String(x.q||'').replace(/\s+/g,' ').trim().toLowerCase()));let added=0;
for(const q of Q){const k=String(q.q).replace(/\s+/g,' ').trim().toLowerCase();if(seenId.has(q.id)||seenText.has(k))continue;q.ex=q.choiceExplanations[q.a];q.examStyle=V.QuestionQuality119?.isExamStyle?.(q)!==false;q.questionClass='exam-style';V.questions.push(q);seenId.add(q.id);seenText.add(k);added++}
V.questionById=Object.fromEntries(V.questions.map(q=>[q.id,q]));V.questionsForConcept=id=>V.questions.filter(q=>q.conceptId===id);V.QuestionDifficulty?.annotate?.(V.questions);
V.LawQuestions119={version:'119-current-law-practice-v1',added,ids:Q.map(x=>x.id),pastExamClaim:false,sourcePolicy:'current official law text only'};
})();